"use client";
// components/whiteboard/TldrawCanvas.tsx
// Interactive tldraw whiteboard canvas — the professor-performance teaching
// engine. tldraw is ONLY the renderer here (strokes, arrows, shapes, labels,
// camera movement, progressive visibility); everything about WHAT gets drawn
// and WHEN comes from a ProfessorLessonPlan (lib/whiteboard/
// professorLessonPlan.ts), built once per page/concept by useProfessorLesson
// and never regenerated by playback controls.
//
//   TEACHING LAYER — locked (isLocked: true), created LAZILY: a shape does
//     not exist on the canvas until the action that draws it has been
//     reached. This is the fix for "reveals completed cards instead of
//     visibly constructing the idea" — the canvas starts nearly blank and
//     shapes are born as the professor writes/draws them, not pre-placed and
//     faded in.
//   STUDENT LAYER — tldraw's own native (always-visible) toolbar draws on
//     top of the teaching layer, but the editor itself is READ-ONLY by
//     default: locked while playing, and locked even while paused/finished
//     until the student explicitly clicks "Edit a copy" (editingEnabled
//     state below). A fresh lesson always resets this back to locked.
//
// Every entry point (autoplay's forward step, Next, Previous, Restart, "Show
// complete diagram") funnels through ONE function, applyStateAtStep, which
// recomputes the canvas state FROM SCRATCH via the pure
// computeCanvasStateAtStep(actions, index) and diffs it against whatever
// currently exists — so Previous/Restart are always exact-state jumps, never
// incremental undo.

import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Tldraw, createShapeId, toRichText, type Editor } from "@tldraw/tldraw";
import "@tldraw/tldraw/tldraw.css";
import type { NoteCard } from "@/lib/insights/synthesizeTeachingOutput";
import {
  computeVSGState, noteCardsToCanonicalEntries, type VisualSceneGraph,
} from "@/lib/whiteboard/visualSceneGraph";
import { useProfessorLesson } from "@/components/whiteboard/useProfessorLesson";
import {
  computeCanvasStateAtStep, resolveCameraTargetAtStep, resolveActiveSegmentIdAtStep,
  type ShapeVisualState,
} from "@/lib/whiteboard/professorTimelineEngine";
import type { ProfessorTeachingAction, NarrationSegment, Bounds } from "@/lib/whiteboard/professorLessonPlan";
import { useReadingFocusStore } from "@/lib/readingFocus/readingFocusStore";
import {
  claimSpeech, isSpeechStale, registerActiveAudio, registerActiveUtterance,
  notifySpeechStart, notifySpeechEnd, notifySpeechError, stopAllSpeech,
} from "@/lib/speech/speechController";

const SPEECH_OWNER = "whiteboard" as const;
// A warm, deliberate voice for a "professor" delivery — see pages/api/tts.ts;
// falls back to browser speech automatically when OPENAI_API_KEY is unset.
const PROFESSOR_VOICE = "onyx";

// ── Tier colors (unchanged semantics: red=danger/trap, gold=master, …) ─────
const TIER_COLOR: Record<string, string> = {
  master: "yellow", step: "green", decision: "blue", danger: "red", pearl: "light-blue",
};
const EDGE_COLOR: Record<string, string> = {
  causation: "green", contrast: "red", elaboration: "blue", sequence: "grey", reference: "grey",
};

// ── Speed config ──────────────────────────────────────────────────────────────
const SPEED_FACTOR = { slow: 0.6, normal: 1, fast: 2.2 } as const;
type PlaybackSpeed = keyof typeof SPEED_FACTOR;
const PACE_TO_TTS_SPEED: Record<string, number> = { slow: 0.85, normal: 1.0 };

// ── Shared styles ─────────────────────────────────────────────────────────────
const BTN_BASE: React.CSSProperties = { fontSize: 11, padding: "3px 9px", borderRadius: 4, cursor: "pointer", lineHeight: "16px", userSelect: "none" };
const BTN_PRIMARY: React.CSSProperties = { ...BTN_BASE, background: "rgba(134,239,172,0.18)", color: "#86efac", border: "1px solid rgba(134,239,172,0.35)" };
const BTN_MUTED: React.CSSProperties = { ...BTN_BASE, background: "rgba(148,163,184,0.08)", color: "#94a3b8", border: "1px solid rgba(148,163,184,0.2)" };
const BTN_DISABLED: React.CSSProperties = { ...BTN_MUTED, opacity: 0.35, cursor: "default" };
const BTN_ACTIVE: React.CSSProperties = { ...BTN_BASE, background: "rgba(96,165,250,0.22)", color: "#93c5fd", border: "1px solid rgba(96,165,250,0.45)" };
const SELECT_STYLE: React.CSSProperties = { fontSize: 10, padding: "2px 4px", borderRadius: 4, cursor: "pointer", background: "rgba(15,23,42,0.95)", color: "#64748b", border: "1px solid rgba(148,163,184,0.2)" };

// ── Props ─────────────────────────────────────────────────────────────────────
interface Props {
  noteCards:          NoteCard[];
  pageTitle?:         string | null;
  whiteboardGrammar?: string;
  onAnchorClick?:     (nodeId: string) => void;
  vsg?:               VisualSceneGraph;
  activeAnchorId?:    string | null;
  storageKey?:        string;
  /** Professor Lesson Planner identity — documentId + pageTruthKey +
   *  activeCanonicalUnitId, per lib/whiteboard/professorLessonPlan.ts's
   *  cache key. Falls back to storageKey/"unknown" when omitted so the
   *  planner still works for existing call sites during rollout. */
  documentId?:             string;
  pageTruthKey?:           string;
  activeCanonicalUnitId?:  string | null;
  /** The current page's classifier value (SurgeonAnnotationPlan.pageRole) —
   *  passed straight through to the Professor Lesson Planner so it teaches
   *  in a style that matches what kind of page this actually is. */
  pageTeachingType?:       string | null;
}

function mergeBounds(list: Bounds[]): Bounds | null {
  if (list.length === 0) return null;
  const x0 = Math.min(...list.map(b => b.x));
  const y0 = Math.min(...list.map(b => b.y));
  const x1 = Math.max(...list.map(b => b.x + b.w));
  const y1 = Math.max(...list.map(b => b.y + b.h));
  return { x: x0, y: y0, w: x1 - x0, h: y1 - y0 };
}

function shapeIdOf(raw: string): ReturnType<typeof createShapeId> {
  return raw as unknown as ReturnType<typeof createShapeId>;
}

// Every tldraw shape id MUST start with "shape:" (createShapeId enforces
// this). A plain string-concat id like `emphasis-${primaryShapeId}` fails
// that validation and crashes the whole editor — createShapeId already
// prefixes whatever string it's given, so the primary id's own "shape:"
// prefix must be stripped first or it ends up embedded mid-string instead
// of at the start. Keyed by treatment too — a shape can carry more than one
// simultaneous emphasis (e.g. circled AND numbered), each needs its own id.
function emphasisShapeId(primaryShapeId: string, treatment: string): string {
  return String(createShapeId(`emphasis-${treatment}-${primaryShapeId.replace(/^shape:/, "")}`));
}

type EmphasisTreatment = "circle" | "underline" | "pulse" | "highlight" | "number";

/** One overlay shape spec per emphasis treatment. Pure — bounds in, tldraw
 *  shape spec out, no editor access. */
function emphasisOverlaySpec(treatment: EmphasisTreatment, bounds: Bounds, sequenceNumber: number | undefined): { type: "geo"; x: number; y: number; props: Record<string, unknown>; opacity: number } {
  switch (treatment) {
    case "underline":
      // A thin bar just under the box — reads as "underline this", not a
      // full second outline.
      return {
        type: "geo", x: bounds.x, y: bounds.y + bounds.h + 4,
        props: { geo: "rectangle", w: bounds.w, h: 4, fill: "solid", dash: "solid", size: "s", color: "orange" },
        opacity: 1,
      };
    case "highlight":
      // A translucent wash behind the shape — a warm color for "pay
      // attention here" (used for danger-tier/trap points), not the strong
      // orange ring reserved for the single "decisive point" circle.
      return {
        type: "geo", x: bounds.x - 6, y: bounds.y - 6,
        props: { geo: "rectangle", w: bounds.w + 12, h: bounds.h + 12, fill: "solid", color: "red", size: "m" },
        opacity: 0.22,
      };
    case "number": {
      const label = String(sequenceNumber ?? "");
      return {
        type: "geo", x: bounds.x - 14, y: bounds.y - 14,
        props: { geo: "ellipse", w: 26, h: 26, fill: "solid", color: "violet", size: "s", richText: toRichText(label), font: "sans" },
        opacity: 1,
      };
    }
    case "pulse":
    case "circle":
    default:
      // tldraw shapes are static — there is no built-in pulsing animation,
      // so "pulse" deliberately renders identically to "circle" (a ring)
      // rather than silently doing nothing. A true pulse would need an
      // external rAF loop layered outside the deterministic action model.
      return {
        type: "geo", x: bounds.x - 8, y: bounds.y - 8,
        props: { geo: "ellipse", w: bounds.w + 16, h: bounds.h + 16, fill: "none", dash: "draw", size: "m", color: "orange" },
        opacity: 1,
      };
  }
}

export default function TldrawCanvas({
  noteCards, pageTitle, whiteboardGrammar = "flow",
  onAnchorClick, vsg, activeAnchorId, storageKey,
  documentId, pageTruthKey, activeCanonicalUnitId, pageTeachingType,
}: Props) {
  const licenseKey = process.env.NEXT_PUBLIC_TLDRAW_LICENSE_KEY;
  const licenseMissingInProduction = process.env.NODE_ENV === "production" && !licenseKey;
  const DEV = process.env.NODE_ENV === "development";

  // Dev-only visible readout of [WHITEBOARD_STEP_DIAGNOSTIC] — the same
  // counts as the console log, but visible without opening devtools, so
  // "is the drawing layer actually keeping up with the narration" is a
  // glance, not a log search. Never rendered in production.
  const [stepDiagnostic, setStepDiagnostic] = useState<{
    step: number; total: number; nodeCount: number; generated: number; visible: number;
  } | null>(null);

  useEffect(() => {
    console.log("[WHITEBOARD_LICENSE_DIAGNOSTIC]", {
      licenseConfigured: Boolean(licenseKey),
      licensePrefixPresent: licenseKey?.startsWith("tldraw-") ?? false,
      nodeEnv: process.env.NODE_ENV,
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const [canvasInitFailure, setCanvasInitFailure] = useState<string | null>(null);
  const editorRef = useRef<Editor | null>(null);
  const mountCountRef = useRef(0);

  // ── Fallback VSG: derive one from noteCards when no vsg prop was given.
  //    The professor engine ALWAYS operates on a VisualSceneGraph — there is
  //    no separate "paragraph card" rendering path anymore. ────────────────
  const derivedVsg = useMemo(() => {
    if (vsg && vsg.nodes.length > 0) return vsg;
    if (noteCards.length === 0) return undefined;
    const state = computeVSGState(noteCardsToCanonicalEntries(noteCards), whiteboardGrammar);
    return state.status === "ready" ? state.vsg : undefined;
  }, [vsg, noteCards, whiteboardGrammar]);

  const effectiveDocumentId = documentId ?? storageKey ?? "unknown-document";
  const effectivePageTruthKey = pageTruthKey ?? derivedVsg?.id ?? "unknown-page";

  const { lessonPlan, status: lessonStatus, errorMessage: lessonErrorMessage, errorCode: lessonErrorCode, reanalyze } = useProfessorLesson({
    vsg: derivedVsg,
    documentId: effectiveDocumentId,
    pageTruthKey: effectivePageTruthKey,
    activeCanonicalUnitId: activeCanonicalUnitId ?? null,
    pageTeachingType: pageTeachingType ?? null,
    enabled: !!derivedVsg,
  });

  // ── Playback state ─────────────────────────────────────────────────────
  const [totalSteps, setTotalSteps] = useState(0);
  const [stepIndex, setStepIndexState] = useState(-1);
  const stepIndexRef = useRef(-1);
  const [isPlaying, setIsPlaying] = useState(false);
  // The teaching canvas is READ-ONLY by default — locked while playing AND
  // while paused/finished, until the student explicitly clicks "Edit a
  // copy." A fresh lesson (new pageTruthKey/documentId/activeCanonicalUnitId
  // — see the rebuild effect below) always resets this back to false, so
  // editing access from a PRIOR page's lesson never carries over.
  const [editingEnabled, setEditingEnabled] = useState(false);
  const [speed, setSpeed] = useState<PlaybackSpeed>("normal");
  const [narrationEnabled, setNarrationEnabled] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [activeSegmentId, setActiveSegmentId] = useState<string | null>(null);

  const planRef = useRef(lessonPlan);
  planRef.current = lessonPlan;
  const vsgForColorsRef = useRef(derivedVsg);
  vsgForColorsRef.current = derivedVsg;

  const createdShapeIdsRef  = useRef<Set<string>>(new Set());
  const targetIdToShapeIdRef = useRef<Map<string, string>>(new Map());
  const shapeIdToTargetIdRef = useRef<Map<string, string>>(new Map());
  const onAnchorClickRef = useRef(onAnchorClick);
  useEffect(() => { onAnchorClickRef.current = onAnchorClick; }, [onAnchorClick]);
  const storeUnsubRef = useRef<(() => void) | null>(null);

  // ── Color lookup: node/edge tier is on the VSG, not the lesson script —
  //    threaded through at render time so semantic color-coding survives. ──
  const colorForTarget = useCallback((targetId: string | undefined, fallback: string): string => {
    const v = vsgForColorsRef.current;
    if (!v || !targetId) return fallback;
    const node = v.nodes.find(n => n.sourceId === targetId);
    if (node) return TIER_COLOR[node.tier] ?? fallback;
    // targetId is an edge id for a draw-arrow action (registerAnchors below
    // registers edge.id the same way it registers a node's sourceId) — was
    // previously never reached because draw-arrow never carried a targetId
    // at all, leaving EDGE_COLOR entirely dead code and every arrow grey.
    const edge = v.edges.find(e => e.id === targetId);
    if (edge) return EDGE_COLOR[edge.kind] ?? fallback;
    return fallback;
  }, []);

  // ── The ONLY function that decides what the canvas should look like at a
  //    given action index — creates/updates/deletes shapes as a diff against
  //    the pure reconstructed state, exactly like the old applyVisualStates
  //    but creation-aware (lazy) instead of opacity-only. ──────────────────
  const applyStateAtStep = useCallback((editor: Editor, index: number) => {
    const plan = planRef.current;
    if (!plan) return;
    const state = computeCanvasStateAtStep(plan.actions, index);

    const wantedPrimaryIds = new Set(state.keys());
    const wantedEmphasisIds = new Set(
      Array.from(state.values()).flatMap(s => s.emphasisTreatments.map(t => emphasisShapeId(s.shapeId, t.treatment))),
    );
    const wantedIds = new Set<string>([...wantedPrimaryIds, ...wantedEmphasisIds]);

    // Remove anything that shouldn't exist yet (only fires on a backward jump).
    for (const id of Array.from(createdShapeIdsRef.current)) {
      if (!wantedIds.has(id)) {
        try { editor.deleteShapes([shapeIdOf(id)]); } catch { /* already gone */ }
        createdShapeIdsRef.current.delete(id);
      }
    }

    const creates: any[] = [];
    const updates: any[] = [];

    for (const s of state.values()) {
      const targetId = shapeIdToTargetIdRef.current.get(s.shapeId);
      const shapeSpec = toTldrawShapeSpec(s, colorForTarget(targetId, s.kind === "arrow" ? "grey" : "blue"));
      if (!shapeSpec) continue;
      if (createdShapeIdsRef.current.has(s.shapeId)) {
        updates.push({ id: shapeIdOf(s.shapeId), type: shapeSpec.type, x: shapeSpec.x, y: shapeSpec.y, props: shapeSpec.props });
      } else {
        creates.push({ id: shapeIdOf(s.shapeId), type: shapeSpec.type, x: shapeSpec.x, y: shapeSpec.y, props: shapeSpec.props, opacity: 1, isLocked: true });
        createdShapeIdsRef.current.add(s.shapeId);
      }

      if (s.emphasized && s.bounds) {
        // One overlay shape PER treatment — a shape can be circled AND
        // numbered at once, each gets its own id so neither is dropped.
        for (const { treatment, sequenceNumber } of s.emphasisTreatments) {
          const emphId = emphasisShapeId(s.shapeId, treatment);
          const emphSpec = emphasisOverlaySpec(treatment, s.bounds, sequenceNumber);
          if (createdShapeIdsRef.current.has(emphId)) {
            updates.push({ id: shapeIdOf(emphId), type: emphSpec.type, x: emphSpec.x, y: emphSpec.y, props: emphSpec.props });
          } else {
            creates.push({ id: shapeIdOf(emphId), type: emphSpec.type, x: emphSpec.x, y: emphSpec.y, props: emphSpec.props, opacity: emphSpec.opacity, isLocked: true });
            createdShapeIdsRef.current.add(emphId);
          }
        }
      }
    }

    for (const c of creates) editor.createShape(c as any);
    if (updates.length > 0) {
      // Same unlock -> apply -> relock sequence as the prior engine: tldraw
      // does not visually repaint an update on a locked shape even though it
      // accepts the change into the store.
      editor.updateShapes(updates.map((u: any) => ({ id: u.id, type: u.type, isLocked: false })));
      editor.updateShapes(updates);
      editor.updateShapes(updates.map((u: any) => ({ id: u.id, type: u.type, isLocked: true })));
    }

    // Privacy-safe per-step diagnostic — no narration/label/quote text, only
    // ids and counts. The one signal previously missing to answer "narration
    // is progressing but the canvas looks blank": editorShapeCount is
    // queried directly from tldraw's OWN store (ground truth — not this
    // component's own createdShapeIdsRef bookkeeping, which could silently
    // drift from what the editor actually has), so a real discrepancy
    // between "we called createShape" and "tldraw actually has the shape"
    // is visible here, not just inferred.
    const vsgNow = vsgForColorsRef.current;
    console.log("[WHITEBOARD_STEP_DIAGNOSTIC]", {
      pageTruthKey:        plan.sourceSnapshot?.pageTruthKey ?? null,
      sceneGraphId:        vsgNow?.id ?? null,
      currentTeachingStep: index,
      totalTeachingSteps:  plan.actions.length,
      // "draw" actions specifically (draw-shape/draw-arrow) — a subset of
      // totalTeachingSteps, which also counts write/speak/pause/move-camera/
      // emphasize/erase actions that never create a shape on their own.
      drawActionCount:     plan.actions.filter(a => a.type === "draw-shape" || a.type === "draw-arrow").length,
      nodeCount:           vsgNow?.nodes.length ?? 0,
      edgeCount:           vsgNow?.edges.length ?? 0,
      shapeRecordsGenerated: wantedIds.size,
      shapeRecordsCreated:   creates.length,
      currentStepShapeIds:   Array.from(state.values()).map(s => s.shapeId),
      editorShapeCount:      editor.getCurrentPageShapeIds().size,
      visibleShapeCount:     createdShapeIdsRef.current.size,
    });
    if (DEV) {
      setStepDiagnostic({
        step: index + 1, total: plan.actions.length, nodeCount: vsgNow?.nodes.length ?? 0,
        generated: wantedIds.size, visible: createdShapeIdsRef.current.size,
      });
    }

    const cameraTargets = resolveCameraTargetAtStep(plan.actions, index);
    if (cameraTargets && cameraTargets.length > 0) {
      const bounds = cameraTargets
        .map(id => editor.getShapePageBounds(shapeIdOf(id)))
        .filter((b): b is NonNullable<typeof b> => !!b)
        .map(b => ({ x: b.x, y: b.y, w: b.w, h: b.h }));
      const merged = mergeBounds(bounds);
      if (merged) {
        // A single node's bounds are ~290x56 — a flat 40px pad on that made
        // the per-step camera crop tight enough to read as "punched in on a
        // random screenshot" rather than a professor stepping back a little
        // between points. Padding now scales with content size, with a
        // floor big enough to keep a single small node from filling the
        // whole frame, and is deliberately taller than it is wide (nodes are
        // wide/short, so the pad needs the most room on the axis the
        // content itself doesn't already fill) — the goal is "still visibly
        // zoomed to the active point" while showing meaningfully more of
        // its surrounding context than before, per rule "fit the complete
        // active teaching region, zoom only to emphasize a detail."
        const padX = Math.max(100, merged.w * 0.3);
        const padY = Math.max(140, merged.h * 1.2);
        editor.zoomToBounds(
          { x: merged.x - padX, y: merged.y - padY, w: merged.w + padX * 2, h: merged.h + padY * 2 } as any,
          { animation: { duration: 300 } } as any,
        );
      }
    } else if (index === -1) {
      editor.zoomToFit();
    }

    // A second small log for cameraBounds specifically — the camera call
    // above animates (300ms), so this is the viewport at the MOMENT the
    // step was applied, not necessarily the final settled position; still a
    // real, directly-queried value (not the internally-computed target) for
    // answering "are shapes being drawn outside what the camera can see."
    const vpBounds = editor.getViewportPageBounds();
    console.log("[WHITEBOARD_CAMERA_DIAGNOSTIC]", {
      currentTeachingStep: index,
      cameraBounds: { x: Math.round(vpBounds.x), y: Math.round(vpBounds.y), w: Math.round(vpBounds.w), h: Math.round(vpBounds.h) },
    });

    setActiveSegmentId(resolveActiveSegmentIdAtStep(plan.actions, index));
  }, [colorForTarget]);

  const setStepIndex = useCallback((n: number) => {
    stepIndexRef.current = n;
    setStepIndexState(n);
    const editor = editorRef.current;
    if (editor) applyStateAtStep(editor, n);
  }, [applyStateAtStep]);

  // ── Narration: real neural TTS (pages/api/tts.ts), falling back to browser
  //    speech only when OpenAI is unavailable — the direct fix for "the voice
  //    sounds like standard text-to-speech." ────────────────────────────────
  const playSegment = useCallback(async (segment: NarrationSegment) => {
    if (!narrationEnabled) return;
    const token = claimSpeech(SPEECH_OWNER);
    setIsSpeaking(true);
    try {
      const res = await fetch("/api/tts", {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "application/json" },
        body: JSON.stringify({ script: segment.text, voice: PROFESSOR_VOICE, format: "mp3" }),
      });
      if (isSpeechStale(token)) return;
      const data = await res.json();
      if (isSpeechStale(token)) return;

      if (data?.useBrowserSpeech) {
        if (typeof window === "undefined" || !("speechSynthesis" in window)) { setIsSpeaking(false); return; }
        const utter = new SpeechSynthesisUtterance(data.script || segment.text);
        utter.rate = PACE_TO_TTS_SPEED[segment.pace] ?? 1;
        registerActiveUtterance(token, utter, () => setIsSpeaking(false));
        utter.onstart = () => notifySpeechStart(token, SPEECH_OWNER);
        utter.onend   = () => { notifySpeechEnd(token, SPEECH_OWNER); setIsSpeaking(false); };
        utter.onerror = (e) => { notifySpeechError(token, SPEECH_OWNER, e.error); setIsSpeaking(false); };
        window.speechSynthesis.speak(utter);
        return;
      }

      if (data?.audioBase64) {
        const bin = atob(data.audioBase64);
        const arr = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
        const blob = new Blob([arr], { type: data.mimeType || "audio/mpeg" });
        const url = URL.createObjectURL(blob);
        const audio = new Audio(url);
        audio.playbackRate = PACE_TO_TTS_SPEED[segment.pace] ?? 1;
        registerActiveAudio(token, audio, () => { audio.pause(); setIsSpeaking(false); });
        audio.onplay  = () => notifySpeechStart(token, SPEECH_OWNER);
        audio.onended = () => { notifySpeechEnd(token, SPEECH_OWNER); setIsSpeaking(false); URL.revokeObjectURL(url); };
        audio.onerror = () => { notifySpeechError(token, SPEECH_OWNER, "audio-error"); setIsSpeaking(false); URL.revokeObjectURL(url); };
        await audio.play().catch(() => setIsSpeaking(false));
        return;
      }
      setIsSpeaking(false);
    } catch {
      if (!isSpeechStale(token)) setIsSpeaking(false);
    }
  }, [narrationEnabled]);

  const stopNarration = useCallback(() => {
    stopAllSpeech("whiteboard-step-change");
    setIsSpeaking(false);
  }, []);

  // ── Anchor / One Brain sync map, rebuilt whenever the plan changes ──────
  const registerAnchors = useCallback((actions: ProfessorTeachingAction[]) => {
    const t2s = new Map<string, string>();
    const s2t = new Map<string, string>();
    for (const a of actions) {
      // "draw-arrow" carries an edge id as targetId (buildProfessorTeachingActions.ts)
      // — registering it here is what lets colorForTarget resolve an edge's
      // kind and apply EDGE_COLOR instead of always falling back to grey.
      if ((a.type === "write" || a.type === "draw-shape" || a.type === "draw-arrow") && a.targetId && a.shapeId) {
        t2s.set(a.targetId, a.shapeId);
        s2t.set(a.shapeId, a.targetId);
      }
    }
    targetIdToShapeIdRef.current = t2s;
    shapeIdToTargetIdRef.current = s2t;
  }, []);

  // Clears every LOCKED (teaching-layer) shape currently on the canvas — the
  // student's own unlocked annotations survive. Called unconditionally
  // whenever the lesson identity changes AND whenever no valid lesson is
  // available, so a page/document/pageTruthKey mismatch — or a plan that
  // simply failed to generate — can never leave a PRIOR page's shapes (or
  // whatever tldraw's own persistenceKey happened to restore from IndexedDB)
  // visible behind the retry state. "A failure state is acceptable. A false
  // lesson from another page is not."
  const clearTeachingLayer = useCallback((editor: Editor) => {
    const existingLocked = editor.getCurrentPageShapes().filter(s => s.isLocked);
    if (existingLocked.length > 0) {
      editor.updateShapes(existingLocked.map(s => ({ id: s.id, type: s.type, isLocked: false })));
      editor.deleteShapes(existingLocked.map(s => s.id));
    }
    createdShapeIdsRef.current = new Set();
  }, []);

  // ── Rebuild: fires on every lessonPlan reference change — INCLUDING a
  //    transition to null (page change with no plan yet, or a failed/
  //    ungroundable generation). The canvas is cleared FIRST, unconditionally,
  //    before checking whether there's anything new to draw — never on a
  //    play/pause/next/previous/restart call, and never from an AI call
  //    itself (this component never calls OpenAI; useProfessorLesson already
  //    resolved the plan — or the lack of one — before this effect runs). ──
  useEffect(() => {
    const editor = editorRef.current;
    if (!editor) return;

    try {
      clearTeachingLayer(editor);
      setIsPlaying(false);
      stopAllSpeech("whiteboard-rebuild");
      setIsSpeaking(false);
      stepIndexRef.current = -1;
      setStepIndexState(-1);
      setCanvasInitFailure(null);

      if (!lessonPlan) {
        // Nothing valid to draw right now (loading, or a failure the retry
        // UI is about to cover) — the canvas is genuinely blank, not holding
        // onto whatever was there before.
        setTotalSteps(0);
        return;
      }

      registerAnchors(lessonPlan.actions);
      setTotalSteps(lessonPlan.actions.length);
      applyStateAtStep(editor, -1);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.error("[WHITEBOARD_CANVAS_INIT_FAILURE]", message);
      setCanvasInitFailure(message);
    }
    // A new lesson always starts read-only — see editingEnabled above.
    setEditingEnabled(false);
    editor.updateInstanceState({ isReadonly: true });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [lessonPlan]);

  // Keeps the editor's actual readonly flag in sync with isPlaying/
  // editingEnabled on every change — separate from the two "reset to
  // readonly" call sites above (mount, lesson change) because those fire
  // BEFORE this effect would otherwise run for the very first render.
  useEffect(() => {
    const editor = editorRef.current;
    if (!editor) return;
    editor.updateInstanceState({ isReadonly: isPlaying || !editingEnabled });
  }, [isPlaying, editingEnabled]);

  // ── Mount handler ─────────────────────────────────────────────────────────
  // Runs the SAME unconditional-clear-first sequence as the rebuild effect —
  // tldraw's own persistenceKey may have just restored shapes from IndexedDB
  // (a prior session's content for this storageKey) before React's lessonPlan
  // state is known to be valid for THIS load; those restored shapes are never
  // trusted as ground truth, only what the current, validated lessonPlan says.
  const handleMount = useCallback((editor: Editor) => {
    mountCountRef.current += 1;
    const isDuplicateMount = editor === editorRef.current;
    console.log("[WHITEBOARD_MOUNT_DIAGNOSTIC]", { mountCount: mountCountRef.current, editorIdentity: isDuplicateMount ? "same" : "different" });
    // React 18 StrictMode (next.config.js: reactStrictMode: true) double-
    // invokes onMount in dev — confirmed via the log above (mountCount
    // reaches 2 for the SAME editor instance on a normal load). Re-running
    // clearTeachingLayer + applyStateAtStep(editor, -1) a second time for an
    // editor we already fully initialized is redundant, unnecessary risk in
    // an async multi-step sequence — skip the duplicate work, but still keep
    // the ref assignment (harmless no-op when it's the same value) and the
    // listener re-subscription below, since StrictMode's real contract is
    // "effects must be safe to run twice," not "skip the second call
    // entirely" — only the parts of this callback that are NOT idempotent
    // (full state rebuild) are the ones being skipped here.
    editorRef.current = editor;
    if (!isDuplicateMount) {
      clearTeachingLayer(editor);
      // Read-only by default (see editingEnabled) — the isPlaying/editingEnabled
      // effect above can't apply this on its own for the very first mount,
      // since editorRef.current is still null when that effect's first run
      // fires (this callback is what SETS editorRef.current).
      editor.updateInstanceState({ isReadonly: true });
      if (lessonPlan) {
        registerAnchors(lessonPlan.actions);
        setTotalSteps(lessonPlan.actions.length);
        applyStateAtStep(editor, -1);
      } else {
        setTotalSteps(0);
      }
    }

    // Listener (re-)subscription is idempotent and safe to redo on a
    // duplicate mount — unlike the full clear+rebuild above, there's no
    // async multi-step sequence here to race against.
    storeUnsubRef.current?.();
    storeUnsubRef.current = editor.store.listen(
      () => {
        const selected = editor.getSelectedShapes();
        if (selected.length !== 1) return;
        const targetId = shapeIdToTargetIdRef.current.get(String(selected[0].id));
        if (targetId) {
          onAnchorClickRef.current?.(targetId);
          useReadingFocusStore.getState().setThoughtUnit(targetId);
        }
      },
      { scope: "session", source: "user" },
    );
  }, [lessonPlan, registerAnchors, applyStateAtStep, clearTeachingLayer]);

  useEffect(() => () => {
    storeUnsubRef.current?.();
    stopAllSpeech("whiteboard-unmount");
  }, []);

  // ── Playback: the ONLY code that advances the timeline during Play ───────
  const advanceForPlayback = useCallback(() => {
    const plan = planRef.current;
    if (!plan) return;
    const next = stepIndexRef.current + 1;
    if (next >= plan.actions.length) { setIsPlaying(false); return; }
    setStepIndex(next);
    const action = plan.actions[next];
    if (action.type === "speak") {
      const segment = plan.segments.find(s => s.id === action.segmentId);
      if (segment) playSegment(segment);
    }
  }, [setStepIndex, playSegment]);

  useEffect(() => {
    if (!isPlaying) return;
    const plan = planRef.current;
    if (!plan) return;
    const next = stepIndexRef.current + 1;
    if (next >= plan.actions.length) { setIsPlaying(false); return; }
    const duration = Math.max(plan.actions[next].durationMs, 200) / SPEED_FACTOR[speed];
    const t = window.setTimeout(advanceForPlayback, duration);
    return () => clearTimeout(t);
  }, [isPlaying, stepIndex, speed, advanceForPlayback]);

  // ── Manual controls — always instant, exact-state jumps, never audio ────
  const handleNext = useCallback(() => {
    setIsPlaying(false);
    stopNarration();
    const plan = planRef.current;
    if (!plan) return;
    setStepIndex(Math.min(stepIndexRef.current + 1, plan.actions.length - 1));
  }, [setStepIndex, stopNarration]);

  const handlePrev = useCallback(() => {
    setIsPlaying(false);
    stopNarration();
    setStepIndex(Math.max(stepIndexRef.current - 1, -1));
  }, [setStepIndex, stopNarration]);

  const handleRestart = useCallback(() => {
    stopNarration();
    setStepIndex(-1);
    setIsPlaying(true);
  }, [setStepIndex, stopNarration]);

  const handleShowComplete = useCallback(() => {
    setIsPlaying(false);
    stopNarration();
    const plan = planRef.current;
    if (!plan) return;
    setStepIndex(plan.actions.length - 1);
  }, [setStepIndex, stopNarration]);

  const handlePlayPause = useCallback(() => {
    if (isPlaying) { setIsPlaying(false); stopNarration(); return; }
    const plan = planRef.current;
    const atEnd = !!plan && plan.actions.length > 0 && stepIndexRef.current >= plan.actions.length - 1;
    if (atEnd) {
      // "Play after completion must replay the entire teaching performance."
      stopNarration();
      setStepIndex(-1);
    }
    setIsPlaying(true);
  }, [isPlaying, setStepIndex, stopNarration]);

  // ── World -> canvas: external anchor focus selects + centers the shape ──
  useEffect(() => {
    const editor = editorRef.current;
    if (!editor) return;
    if (!activeAnchorId) { editor.selectNone(); return; }
    const sid = targetIdToShapeIdRef.current.get(activeAnchorId);
    if (!sid) return;
    const shape = editor.getShape(shapeIdOf(sid));
    if (!shape) return;
    editor.select(shapeIdOf(sid));
    const bounds = editor.getShapePageBounds(shapeIdOf(sid));
    if (bounds) editor.centerOnPoint({ x: bounds.midX, y: bounds.midY });
  }, [activeAnchorId]);

  // ── SVG export ────────────────────────────────────────────────────────────
  const handleExport = useCallback(async () => {
    const editor = editorRef.current;
    if (!editor) return;
    try {
      const shapeIds = [...editor.getCurrentPageShapeIds()];
      if (!shapeIds.length) return;
      const result = await (editor as any).getSvgString(shapeIds, { background: false });
      const svgStr: string | undefined = typeof result === "string" ? result : result?.svg;
      if (!svgStr) return;
      const blob = new Blob([svgStr], { type: "image/svg+xml" });
      const url = URL.createObjectURL(blob);
      const a = Object.assign(document.createElement("a"), { href: url, download: `${storageKey ?? "whiteboard"}.svg` });
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      // export not supported — silently ignore
    }
  }, [storageKey]);

  // ── Render ────────────────────────────────────────────────────────────────
  const atStart = stepIndex < 0;
  const atEnd = totalSteps > 0 && stepIndex >= totalSteps - 1;
  const segments = lessonPlan?.segments ?? [];

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%", minHeight: 480, background: "#0f172a" }}>

      {/* ── Controls bar ──────────────────────────────────────────────────── */}
      <div style={{ display: "flex", alignItems: "center", gap: 6, padding: "7px 12px", borderBottom: "1px solid rgba(255,255,255,0.08)", flexWrap: "wrap" }}>
        <span style={{ fontSize: 12, color: "#94a3b8", fontFamily: "monospace", flexShrink: 0 }}>
          {lessonPlan?.title || pageTitle || "Whiteboard"}
        </span>
        {/* Dev-only visible readout — see [WHITEBOARD_STEP_DIAGNOSTIC] above.
            Never rendered in production; a glance answer to "is the drawing
            layer actually keeping up with the narration," not a log search. */}
        {DEV && stepDiagnostic && (
          <span style={{ fontSize: 10, color: "#64748b", fontFamily: "monospace", flexShrink: 0 }}>
            Step {stepDiagnostic.step}/{stepDiagnostic.total} · {stepDiagnostic.nodeCount} scene nodes · {stepDiagnostic.generated} generated shapes · {stepDiagnostic.visible} visible
          </span>
        )}
        <span style={{ marginLeft: "auto", display: "flex", gap: 5, alignItems: "center" }}>
          {totalSteps > 0 && (
            <span style={{ fontSize: 10, color: "#475569", fontVariantNumeric: "tabular-nums", marginRight: 2 }}>
              {Math.max(stepIndex + 1, 0)} / {totalSteps}
            </span>
          )}

          <button onClick={handleRestart} title="Restart" style={BTN_MUTED}>&#x23EE;</button>
          <button onClick={handlePrev} disabled={atStart} title="Previous" style={atStart ? BTN_DISABLED : BTN_MUTED}>&#x25C4;</button>
          <button onClick={handlePlayPause} style={BTN_PRIMARY}>{isPlaying ? "⏸ Pause" : "▶ Play"}</button>
          <button onClick={handleNext} disabled={atEnd} title="Next" style={atEnd ? BTN_DISABLED : BTN_MUTED}>&#x25BA;</button>
          <button onClick={handleShowComplete} title="Show complete diagram" style={BTN_MUTED}>All</button>

          <select value={speed} onChange={e => setSpeed(e.target.value as PlaybackSpeed)} style={SELECT_STYLE} title="Speed">
            <option value="slow">Slow</option>
            <option value="normal">Normal</option>
            <option value="fast">Fast</option>
          </select>

          <button
            onClick={() => { const next = !narrationEnabled; setNarrationEnabled(next); if (!next) stopNarration(); }}
            title={narrationEnabled ? "Mute narration" : "Enable voice narration"}
            style={narrationEnabled ? BTN_ACTIVE : BTN_MUTED}
          >
            {isSpeaking ? "🔊" : narrationEnabled ? "🔉" : "🔇"}
          </button>

          <button onClick={handleExport} title="Export SVG" style={BTN_MUTED}>&#x2193; SVG</button>

          {/* Read-only by default (locked during playback AND while paused/
              finished) — this is the explicit, deliberate opt-in to draw on
              top of the diagram. Disabled while playing (editing mid-lesson
              would fight with the locked teaching layer's own updates) and
              once already enabled (nothing left to opt into). */}
          <button
            onClick={() => setEditingEnabled(true)}
            disabled={isPlaying || editingEnabled}
            title={editingEnabled ? "Editing enabled" : "Unlock this canvas for your own annotations"}
            style={isPlaying || editingEnabled ? BTN_DISABLED : BTN_MUTED}
          >
            {editingEnabled ? "✓ Editing" : "✎ Edit a copy"}
          </button>
        </span>
      </div>

      <div style={{ flex: 1, display: "flex", minHeight: 0 }}>
        {/* ── Canvas ────────────────────────────────────────────────────── */}
        <div style={{ flex: 1, position: "relative" }}>
          {licenseMissingInProduction ? (
            <div role="alert" style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 8, background: "#0f172a", color: "#94a3b8", fontFamily: "ui-monospace, monospace", fontSize: 13, textAlign: "center", padding: 24 }}>
              <span style={{ fontSize: 20 }}>⚠</span>
              <span>Whiteboard configuration is unavailable. Missing: tldraw license key.</span>
            </div>
          ) : (
            <Tldraw licenseKey={licenseKey} persistenceKey={storageKey || undefined} onMount={handleMount} />
          )}

          {!licenseMissingInProduction && canvasInitFailure && (
            <div role="alert" style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 8, zIndex: 20, background: "rgba(15,23,42,0.92)", color: "#94a3b8", fontFamily: "ui-monospace, monospace", fontSize: 13, textAlign: "center", padding: 24, pointerEvents: "none" }}>
              <span style={{ fontSize: 20 }}>⚠</span>
              <span>Whiteboard configuration is unavailable. Canvas initialization failed.</span>
            </div>
          )}

          {/* No fallback: a failed/ungroundable Professor Lesson Planner
              response shows a visible retry state, never a silently-
              substituted generic diagram — see useProfessorLesson.ts.
              clearTeachingLayer() above already guarantees the canvas holds
              no stale shapes by the time this renders; the background is
              still fully OPAQUE (not translucent) as defense-in-depth so
              nothing could show through even if that guarantee were ever
              violated by a future change. */}
          {!licenseMissingInProduction && !lessonPlan && lessonStatus === "error" && (
            <div role="alert" style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", background: "#0f172a", zIndex: 10, gap: 14, padding: 24, textAlign: "center" }}>
              <span style={{ fontSize: 20 }}>⚠</span>
              <span style={{ fontSize: 13, color: "#94a3b8", fontFamily: "ui-monospace, monospace" }}>
                {lessonErrorMessage ?? "Unable to generate Whiteboard for this page."}
              </span>
              {lessonErrorCode && (
                <span style={{ fontSize: 10, color: "#64748b", fontFamily: "ui-monospace, monospace" }}>
                  code: {lessonErrorCode}
                </span>
              )}
              <button onClick={reanalyze} style={BTN_PRIMARY}>Retry</button>
            </div>
          )}

          {!licenseMissingInProduction && !lessonPlan && lessonStatus !== "error" && (
            <div style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", background: "rgba(15,23,42,0.88)", zIndex: 10, gap: 16 }}>
              <span style={{ fontSize: 13, color: "#94a3b8", fontFamily: "ui-monospace, monospace" }}>
                {lessonStatus === "loading" ? "Reading the current page…" : "Preparing visual lesson…"}
              </span>
              <div style={{ display: "flex", flexDirection: "column", gap: 12, alignItems: "center", opacity: 0.35 }}>
                {[280, 220, 250].map((w, i) => (
                  <div key={i} style={{ width: w, height: 52, borderRadius: 8, background: "linear-gradient(90deg, #1e293b 25%, #334155 50%, #1e293b 75%)", backgroundSize: "200% 100%", animation: "wb-shimmer 1.4s ease-in-out infinite", animationDelay: `${i * 0.2}s` }} />
                ))}
              </div>
              <style>{`@keyframes wb-shimmer{0%{background-position:200% 0}100%{background-position:-200% 0}}`}</style>
            </div>
          )}
        </div>

        {/* ── Side transcript — the complete spoken explanation, never
              crammed into the diagram itself. ─────────────────────────── */}
        {segments.length > 0 && (
          <div style={{ width: 220, flexShrink: 0, borderLeft: "1px solid rgba(255,255,255,0.08)", background: "rgba(15,23,42,0.97)", overflowY: "auto", padding: "10px 12px" }}>
            <div style={{ fontSize: 10, color: "#64748b", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 8 }}>Transcript</div>
            {segments.map(seg => (
              <div
                key={seg.id}
                style={{
                  fontSize: 11.5, lineHeight: 1.5, marginBottom: 10, padding: "4px 6px", borderRadius: 4,
                  color: seg.id === activeSegmentId ? "#e2e8f0" : "#64748b",
                  background: seg.id === activeSegmentId ? "rgba(96,165,250,0.12)" : "transparent",
                  borderLeft: seg.id === activeSegmentId ? "2px solid #60a5fa" : "2px solid transparent",
                }}
              >
                {seg.text}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

// ── Pure state -> tldraw shape props ─────────────────────────────────────────
function toTldrawShapeSpec(s: ShapeVisualState, color: string): { type: "geo" | "arrow" | "text"; x: number; y: number; props: Record<string, unknown> } | null {
  if (s.kind === "arrow") {
    if (!s.from || !s.to) return null;
    return {
      type: "arrow", x: s.from.x, y: s.from.y,
      props: { kind: "arc", start: { x: 0, y: 0 }, end: { x: s.to.x - s.from.x, y: s.to.y - s.from.y }, richText: toRichText(s.text ?? ""), size: "s", color },
    };
  }
  if (s.kind === "line") {
    // A short, thin filled bar rather than a full outline — reads as "a
    // drawn line/connector," distinct from a box/circle's outlined shape.
    if (!s.bounds) return null;
    return {
      type: "geo", x: s.bounds.x, y: s.bounds.y,
      props: { geo: "rectangle", w: s.bounds.w, h: Math.min(6, s.bounds.h), fill: "solid", dash: "draw", size: "s", color },
    };
  }
  if (s.kind === "box" || s.kind === "circle" || s.kind === "brace" || s.kind === "diamond" || s.kind === "hexagon" || s.kind === "cloud") {
    if (!s.bounds) return null;
    // dash:"draw" gives tldraw's sketchy hand-drawn stroke; fill:"none" so the
    // performance reads as strokes being drawn, not solid cards being placed.
    // "diamond"/"hexagon"/"cloud" map 1:1 to tldraw's own built-in geo shapes
    // (decision points, warnings, and clinical pearls each get a real,
    // distinct SHAPE — not just a different color on an identical
    // rectangle). "brace" has no true tldraw equivalent and falls back to
    // rectangle, same as before this change.
    const GEO_FOR_KIND: Record<string, string> = {
      circle: "ellipse", diamond: "diamond", hexagon: "hexagon", cloud: "cloud",
    };
    return {
      type: "geo", x: s.bounds.x, y: s.bounds.y,
      props: {
        geo: GEO_FOR_KIND[s.kind] ?? "rectangle",
        w: s.bounds.w, h: s.bounds.h,
        richText: toRichText(s.text ?? ""),
        fill: "none", dash: "draw", size: "m", color, font: "draw",
      },
    };
  }
  // text-only (e.g. the hand-written title) — a bare handwritten line, not
  // boxed like a node, so it visibly reads as "the professor wrote a title"
  // rather than another diagram card.
  return {
    type: "text", x: s.x ?? 0, y: s.y ?? 0,
    props: { richText: toRichText(s.text ?? ""), font: "draw", size: "m", color: "black", autoSize: true, w: 300 },
  };
}
