// lib/reader/thoughtUnitDedup.ts
// Deduplication pipeline for Page Guide / ThoughtUnitNavigator entries.
//
// Three-layer dedup:
//   1. Canonical-hash dedup: exact same text → keep the higher-importance copy.
//   2. Prefix-similarity dedup: entries whose first 50 chars are identical share
//      the same canonical card slot.
//   3. Category-cap: no more than MAX_PER_CATEGORY cards of the same kind to
//      prevent dozens of near-identical "Why It Matters" or "Clinical Pearl" cards.
//
// Also enforces a minimum confidence threshold so synthetic / low-confidence
// entries are dropped before they reach the UI.

export interface DeduplicableEntry {
  id: string;
  text: string;
  kind?: string;
  canonicalType?: string;
  priorityTier?: number;
  importanceScore?: number;
  confidence?: number;
  groundingState?: string;
}

export interface DedupOptions {
  /**
   * Minimum semantic confidence to keep an entry (0–1).
   * Entries below this are dropped.
   * Default: 0  (no minimum — caller opt-in)
   */
  minConfidence?: number;
  /**
   * Maximum entries per category label (kind or canonicalType).
   * Default: 5
   */
  maxPerCategory?: number;
  /**
   * Number of leading characters to use for prefix-similarity dedup.
   * Default: 50
   */
  prefixLength?: number;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function normalizeText(text: string): string {
  return text.replace(/\s+/g, " ").trim().toLowerCase();
}

function canonicalHash(text: string): string {
  const n = normalizeText(text);
  return n.slice(0, 120); // first 120 chars as the hash key
}

function prefixKey(text: string, len: number): string {
  return normalizeText(text).slice(0, len);
}

function importanceRank(entry: DeduplicableEntry): number {
  if (typeof entry.importanceScore === "number") return entry.importanceScore;
  if (typeof entry.priorityTier === "number") return entry.priorityTier * 20; // tier 5→100
  return 0;
}

function categoryKey(entry: DeduplicableEntry): string {
  return entry.canonicalType ?? entry.kind ?? "unknown";
}

// ---------------------------------------------------------------------------
// deduplicateEntries
// ---------------------------------------------------------------------------

/**
 * Remove duplicate and near-duplicate ThoughtUnitNavigator entries.
 *
 * Returns a new array — the input is not mutated.
 * Order is preserved: first occurrence wins for exact duplicates; within a
 * prefix-similarity group the highest-importance entry wins.
 */
export function deduplicateEntries<T extends DeduplicableEntry>(
  entries: T[],
  opts: DedupOptions = {},
): T[] {
  const {
    minConfidence  = 0,
    maxPerCategory = 5,
    prefixLength   = 50,
  } = opts;

  // Step 0: confidence threshold
  const filtered = minConfidence > 0
    ? entries.filter((e) => (e.confidence ?? 1) >= minConfidence)
    : entries;

  // Step 1: canonical-hash dedup — keep highest-importance within identical text
  const hashMap = new Map<string, T>();
  for (const entry of filtered) {
    const key = canonicalHash(entry.text);
    const existing = hashMap.get(key);
    if (!existing || importanceRank(entry) > importanceRank(existing)) {
      hashMap.set(key, entry);
    }
  }

  // Step 2: prefix-similarity dedup — keep highest-importance within shared prefix
  const prefixMap = new Map<string, T>();
  for (const entry of hashMap.values()) {
    const key = prefixKey(entry.text, prefixLength);
    const existing = prefixMap.get(key);
    if (!existing || importanceRank(entry) > importanceRank(existing)) {
      prefixMap.set(key, entry);
    }
  }

  // Step 3: category cap — preserve original insertion order, cap per category
  const categoryCounts = new Map<string, number>();
  const result: T[] = [];

  // Re-apply the original input order (prefix winners may arrive out of order)
  const survivorIds = new Set(Array.from(prefixMap.values()).map((e) => e.id));

  for (const entry of filtered) {
    if (!survivorIds.has(entry.id)) continue;
    const cat = categoryKey(entry);
    const count = categoryCounts.get(cat) ?? 0;
    if (count >= maxPerCategory) continue;
    categoryCounts.set(cat, count + 1);
    result.push(entry);
  }

  return result;
}

// ---------------------------------------------------------------------------
// Synthetic entry guard
// ---------------------------------------------------------------------------

/**
 * Returns true for entries that have no PDF source anchor — they were
 * generated by AI without a grounded passage in the text layer.
 * Synthetic entries should never receive a PDF highlight.
 */
export function isSyntheticEntry(entry: DeduplicableEntry): boolean {
  return entry.groundingState === "synthetic";
}
