// lib/stores/pdrmStore.ts
// PDRM Store - Structured extraction system (Pattern/Decision/Risk/Mnemonic)
// Linked to highlights AND pages with incremental generation

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';

// ============================================================================
// PDRM Types - Structured extraction, NOT summaries
// ============================================================================

export type PDRMType = 'pattern' | 'decision' | 'risk' | 'mnemonic';
export type PDRMStatus = 'draft' | 'complete';
export type PDRMSourceType = 'highlight' | 'page';

// Structured PDRM fields - these are the REAL outputs
export interface PDRMFields {
  pattern: string;       // Recurring concept/category
  decisionRule: string;  // Rule/test/if-then implied
  risk: string;          // Common trap/mistake/contraindication/edge-case
  mnemonic: string;      // Short anchor phrase (or blank)
}

// Evidence linking back to source
export interface PDRMEvidence {
  quote: string;         // Short quote snippet
  pageNumber: number;
  documentId: string;
  highlightId?: string;  // Only for highlight-sourced PDRMs
}

// Full PDRM Entry
export interface PDRMEntry {
  id: string;
  
  // Source type: highlight-driven or page-driven
  sourceType: PDRMSourceType;
  
  // Status: draft (manual mode) or complete (auto mode)
  status: PDRMStatus;
  
  // Primary classification (which field is dominant)
  primaryType: PDRMType | 'general';
  
  // Structured PDRM fields
  fields: PDRMFields;
  
  // Evidence/source linking
  evidence: PDRMEvidence;
  
  // Metadata
  isAutoGenerated: boolean;
  confidence: number;  // 0-1
  
  // Timestamps
  createdAt: string;
  updatedAt: string;
}

// Page cache to prevent re-generation
export interface PageCache {
  documentId: string;
  pageNumber: number;
  processedAt: string;
  entryIds: string[];
}

// ============================================================================
// Store State
// ============================================================================

interface PDRMState {
  // All PDRM entries by ID
  entries: Record<string, PDRMEntry>;
  
  // Auto vs Manual mode (persisted)
  autoMode: boolean;
  
  // Page cache: `${docId}_${pageNumber}` -> PageCache
  pageCache: Record<string, PageCache>;
  
  // Currently generating (for UI indicator)
  generatingFor: string | null;  // `page_${docId}_${page}` or `highlight_${id}`
  
  // Actions - Mode
  setAutoMode: (enabled: boolean) => void;
  toggleAutoMode: () => void;
  
  // Actions - CRUD
  addEntry: (entry: Omit<PDRMEntry, 'id' | 'createdAt' | 'updatedAt'>) => string;
  updateEntry: (id: string, updates: Partial<Omit<PDRMEntry, 'id' | 'createdAt'>>) => void;
  deleteEntry: (id: string) => void;
  
  // Actions - Draft (Manual mode)
  createDraftFromHighlight: (evidence: PDRMEvidence) => string;
  completeDraft: (id: string, fields: PDRMFields, primaryType: PDRMType) => void;
  
  // Actions - Page cache
  markPageProcessed: (documentId: string, pageNumber: number, entryIds: string[]) => void;
  isPageProcessed: (documentId: string, pageNumber: number) => boolean;
  clearPageCache: (documentId: string, pageNumber?: number) => void;
  
  // Actions - Generation tracking
  setGenerating: (key: string | null) => void;
  
  // Queries
  getEntryById: (id: string) => PDRMEntry | undefined;
  getEntriesByHighlight: (highlightId: string) => PDRMEntry[];
  getEntriesByPage: (documentId: string, pageNumber: number) => PDRMEntry[];
  getEntriesByDocument: (documentId: string) => PDRMEntry[];
  getDraftEntries: (documentId: string) => PDRMEntry[];
  
  // Stats
  getStats: (documentId: string) => {
    total: number;
    drafts: number;
    byType: Record<PDRMType | 'general', number>;
    byPage: Record<number, number>;
  };
}

// ============================================================================
// Helpers
// ============================================================================

function generateId(): string {
  return `pdrm_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

function now(): string {
  return new Date().toISOString();
}

function pageCacheKey(documentId: string, pageNumber: number): string {
  return `${documentId}_${pageNumber}`;
}

// ============================================================================
// Store Implementation
// ============================================================================

export const usePdrmStore = create<PDRMState>()(
  persist(
    (set, get) => ({
      entries: {},
      autoMode: true,
      pageCache: {},
      generatingFor: null,
      
      // ---- Mode Actions ----
      setAutoMode: (enabled) => set({ autoMode: enabled }),
      
      toggleAutoMode: () => set((state) => ({ autoMode: !state.autoMode })),
      
      // ---- CRUD Actions ----
      addEntry: (entryData) => {
        const id = generateId();
        const timestamp = now();
        
        const entry: PDRMEntry = {
          ...entryData,
          id,
          createdAt: timestamp,
          updatedAt: timestamp
        };
        
        set((state) => ({
          entries: { ...state.entries, [id]: entry }
        }));
        
        return id;
      },
      
      updateEntry: (id, updates) => {
        set((state) => {
          const existing = state.entries[id];
          if (!existing) return state;
          
          return {
            entries: {
              ...state.entries,
              [id]: {
                ...existing,
                ...updates,
                updatedAt: now()
              }
            }
          };
        });
      },
      
      deleteEntry: (id) => {
        set((state) => {
          const { [id]: removed, ...rest } = state.entries;
          return { entries: rest };
        });
      },
      
      // ---- Draft Actions (Manual Mode) ----
      createDraftFromHighlight: (evidence) => {
        const id = generateId();
        const timestamp = now();
        
        const draft: PDRMEntry = {
          id,
          sourceType: 'highlight',
          status: 'draft',
          primaryType: 'general',
          fields: {
            pattern: '',
            decisionRule: '',
            risk: '',
            mnemonic: ''
          },
          evidence,
          isAutoGenerated: false,
          confidence: 0,
          createdAt: timestamp,
          updatedAt: timestamp
        };
        
        set((state) => ({
          entries: { ...state.entries, [id]: draft }
        }));
        
        return id;
      },
      
      completeDraft: (id, fields, primaryType) => {
        set((state) => {
          const existing = state.entries[id];
          if (!existing) return state;
          
          return {
            entries: {
              ...state.entries,
              [id]: {
                ...existing,
                status: 'complete',
                fields,
                primaryType,
                confidence: 1.0,
                updatedAt: now()
              }
            }
          };
        });
      },
      
      // ---- Page Cache Actions ----
      markPageProcessed: (documentId, pageNumber, entryIds) => {
        const key = pageCacheKey(documentId, pageNumber);
        set((state) => ({
          pageCache: {
            ...state.pageCache,
            [key]: {
              documentId,
              pageNumber,
              processedAt: now(),
              entryIds
            }
          }
        }));
      },
      
      isPageProcessed: (documentId, pageNumber) => {
        const key = pageCacheKey(documentId, pageNumber);
        return !!get().pageCache[key];
      },
      
      clearPageCache: (documentId, pageNumber) => {
        set((state) => {
          if (pageNumber !== undefined) {
            const key = pageCacheKey(documentId, pageNumber);
            const { [key]: removed, ...rest } = state.pageCache;
            return { pageCache: rest };
          }
          // Clear all pages for document
          const newCache: Record<string, PageCache> = {};
          for (const [key, cache] of Object.entries(state.pageCache)) {
            if (cache.documentId !== documentId) {
              newCache[key] = cache;
            }
          }
          return { pageCache: newCache };
        });
      },
      
      // ---- Generation Tracking ----
      setGenerating: (key) => set({ generatingFor: key }),
      
      // ---- Queries ----
      getEntryById: (id) => get().entries[id],
      
      getEntriesByHighlight: (highlightId) => {
        return Object.values(get().entries).filter(
          e => e.evidence.highlightId === highlightId
        );
      },
      
      getEntriesByPage: (documentId, pageNumber) => {
        return Object.values(get().entries).filter(
          e => e.evidence.documentId === documentId && e.evidence.pageNumber === pageNumber
        );
      },
      
      getEntriesByDocument: (documentId) => {
        return Object.values(get().entries).filter(
          e => e.evidence.documentId === documentId
        );
      },
      
      getDraftEntries: (documentId) => {
        return Object.values(get().entries).filter(
          e => e.evidence.documentId === documentId && e.status === 'draft'
        );
      },
      
      // ---- Stats ----
      getStats: (documentId) => {
        const entries = get().getEntriesByDocument(documentId);
        
        const byType: Record<PDRMType | 'general', number> = {
          pattern: 0,
          decision: 0,
          risk: 0,
          mnemonic: 0,
          general: 0
        };
        
        const byPage: Record<number, number> = {};
        let drafts = 0;
        
        for (const entry of entries) {
          byType[entry.primaryType]++;
          byPage[entry.evidence.pageNumber] = (byPage[entry.evidence.pageNumber] || 0) + 1;
          if (entry.status === 'draft') drafts++;
        }
        
        return {
          total: entries.length,
          drafts,
          byType,
          byPage
        };
      }
    }),
    {
      name: 'pdrm-storage-v2',
      storage: createJSONStorage(() => {
        if (typeof window === 'undefined') {
          return {
            getItem: () => null,
            setItem: () => {},
            removeItem: () => {},
          };
        }
        return localStorage;
      }),
      partialize: (state) => ({
        entries: state.entries,
        autoMode: state.autoMode,
        pageCache: state.pageCache
      }),
      skipHydration: typeof window === 'undefined',
    }
  )
);

// ============================================================================
// PDRM UI Helpers
// ============================================================================

export function getPdrmTypeColor(type: PDRMType | 'general'): string {
  switch (type) {
    case 'pattern': return '#8b5cf6';   // Purple
    case 'decision': return '#3b82f6';  // Blue
    case 'risk': return '#ef4444';      // Red
    case 'mnemonic': return '#f59e0b';  // Yellow/Orange
    case 'general': return '#6b7280';   // Gray
  }
}

export function getPdrmTypeIcon(type: PDRMType | 'general'): string {
  switch (type) {
    case 'pattern': return '🔷';
    case 'decision': return '⚖️';
    case 'risk': return '⚠️';
    case 'mnemonic': return '💡';
    case 'general': return '📝';
  }
}

export function getPdrmTypeLabel(type: PDRMType | 'general'): string {
  switch (type) {
    case 'pattern': return 'Pattern';
    case 'decision': return 'Decision Rule';
    case 'risk': return 'Risk/Trap';
    case 'mnemonic': return 'Mnemonic';
    case 'general': return 'General';
  }
}

// Determine primary type from fields
export function determinePrimaryType(fields: PDRMFields): PDRMType | 'general' {
  // Priority order: decision > risk > pattern > mnemonic > general
  if (fields.decisionRule && fields.decisionRule.trim().length > 5) return 'decision';
  if (fields.risk && fields.risk.trim().length > 5) return 'risk';
  if (fields.pattern && fields.pattern.trim().length > 5) return 'pattern';
  if (fields.mnemonic && fields.mnemonic.trim().length > 2) return 'mnemonic';
  return 'general';
}
