// lib/stores/pdrmStore.ts
// PDRM Store - Manages Pattern/Decision/Risk/Mnemonic entries
// Linked to highlights with page-level grouping

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';

// ============================================================================
// Types
// ============================================================================

export type PDRMClassification = 'pattern' | 'decision' | 'risk' | 'mnemonic' | 'general';

export interface PDRMSource {
  documentId: string;
  documentName?: string;
  pageNumber: number;
  chapterTitle?: string;
  highlightId: string;
  quote: string;  // Original highlighted text
}

export interface PDRMEntry {
  id: string;
  classification: PDRMClassification;
  source: PDRMSource;
  
  // Condensed summary (important-only)
  summary: string;  // 1-3 bullet points or single compact line
  keyPoints: string[];  // Extracted key facts
  
  // Confidence and metadata
  confidence: number;  // 0-1
  isAutoGenerated: boolean;
  isImportant: boolean;  // Whether this passed "important-only" filter
  
  // Timestamps
  createdAt: string;
  updatedAt: string;
}

export interface PDRMDocument {
  documentId: string;
  documentName: string;
  entries: PDRMEntry[];
  lastUpdated: string;
}

interface PDRMState {
  // Data
  documents: Record<string, PDRMDocument>;  // documentId -> document
  autoMode: boolean;  // Auto vs Manual classification mode
  
  // Active context
  activeDocumentId: string | null;
  
  // Actions
  setAutoMode: (enabled: boolean) => void;
  setActiveDocument: (documentId: string) => void;
  
  // CRUD
  addEntry: (entry: Omit<PDRMEntry, 'id' | 'createdAt' | 'updatedAt'>) => string;
  updateEntry: (id: string, updates: Partial<PDRMEntry>) => void;
  deleteEntry: (id: string) => void;
  
  // Queries
  getEntriesByDocument: (documentId: string) => PDRMEntry[];
  getEntriesByPage: (documentId: string, pageNumber: number) => PDRMEntry[];
  getEntriesByClassification: (documentId: string, classification: PDRMClassification) => PDRMEntry[];
  getEntryByHighlightId: (highlightId: string) => PDRMEntry | undefined;
  
  // Grouping for PDRM Tab
  getEntriesGroupedByChapter: (documentId: string) => Record<string, PDRMEntry[]>;
  getEntriesGroupedByPage: (documentId: string) => Record<number, PDRMEntry[]>;
  
  // Stats
  getStats: (documentId: string) => {
    total: number;
    byClassification: Record<PDRMClassification, number>;
    important: number;
  };
}

// ============================================================================
// Helper Functions
// ============================================================================

function generateId(): string {
  return `pdrm_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

function now(): string {
  return new Date().toISOString();
}

// ============================================================================
// Store
// ============================================================================

export const usePdrmStore = create<PDRMState>()(
  persist(
    (set, get) => ({
      documents: {},
      autoMode: true,
      activeDocumentId: null,
      
      setAutoMode: (enabled) => {
        set({ autoMode: enabled });
      },
      
      setActiveDocument: (documentId) => {
        set({ activeDocumentId: documentId });
      },
      
      addEntry: (entryData) => {
        const id = generateId();
        const timestamp = now();
        
        const entry: PDRMEntry = {
          ...entryData,
          id,
          createdAt: timestamp,
          updatedAt: timestamp
        };
        
        set((state) => {
          const docId = entry.source.documentId;
          const existingDoc = state.documents[docId];
          
          const updatedDoc: PDRMDocument = existingDoc 
            ? {
                ...existingDoc,
                entries: [...existingDoc.entries, entry],
                lastUpdated: timestamp
              }
            : {
                documentId: docId,
                documentName: entry.source.documentName || docId,
                entries: [entry],
                lastUpdated: timestamp
              };
          
          return {
            documents: {
              ...state.documents,
              [docId]: updatedDoc
            }
          };
        });
        
        return id;
      },
      
      updateEntry: (id, updates) => {
        set((state) => {
          const newDocuments = { ...state.documents };
          
          for (const docId of Object.keys(newDocuments)) {
            const doc = newDocuments[docId];
            const entryIndex = doc.entries.findIndex(e => e.id === id);
            
            if (entryIndex !== -1) {
              const updatedEntries = [...doc.entries];
              updatedEntries[entryIndex] = {
                ...updatedEntries[entryIndex],
                ...updates,
                updatedAt: now()
              };
              
              newDocuments[docId] = {
                ...doc,
                entries: updatedEntries,
                lastUpdated: now()
              };
              break;
            }
          }
          
          return { documents: newDocuments };
        });
      },
      
      deleteEntry: (id) => {
        set((state) => {
          const newDocuments = { ...state.documents };
          
          for (const docId of Object.keys(newDocuments)) {
            const doc = newDocuments[docId];
            const filteredEntries = doc.entries.filter(e => e.id !== id);
            
            if (filteredEntries.length !== doc.entries.length) {
              newDocuments[docId] = {
                ...doc,
                entries: filteredEntries,
                lastUpdated: now()
              };
              break;
            }
          }
          
          return { documents: newDocuments };
        });
      },
      
      getEntriesByDocument: (documentId) => {
        const doc = get().documents[documentId];
        return doc?.entries || [];
      },
      
      getEntriesByPage: (documentId, pageNumber) => {
        const entries = get().getEntriesByDocument(documentId);
        return entries.filter(e => e.source.pageNumber === pageNumber);
      },
      
      getEntriesByClassification: (documentId, classification) => {
        const entries = get().getEntriesByDocument(documentId);
        return entries.filter(e => e.classification === classification);
      },
      
      getEntryByHighlightId: (highlightId) => {
        const { documents } = get();
        for (const doc of Object.values(documents)) {
          const entry = doc.entries.find(e => e.source.highlightId === highlightId);
          if (entry) return entry;
        }
        return undefined;
      },
      
      getEntriesGroupedByChapter: (documentId) => {
        const entries = get().getEntriesByDocument(documentId);
        const grouped: Record<string, PDRMEntry[]> = {};
        
        for (const entry of entries) {
          const chapter = entry.source.chapterTitle || 'Unknown Chapter';
          if (!grouped[chapter]) grouped[chapter] = [];
          grouped[chapter].push(entry);
        }
        
        return grouped;
      },
      
      getEntriesGroupedByPage: (documentId) => {
        const entries = get().getEntriesByDocument(documentId);
        const grouped: Record<number, PDRMEntry[]> = {};
        
        for (const entry of entries) {
          const page = entry.source.pageNumber;
          if (!grouped[page]) grouped[page] = [];
          grouped[page].push(entry);
        }
        
        return grouped;
      },
      
      getStats: (documentId) => {
        const entries = get().getEntriesByDocument(documentId);
        
        const byClassification: Record<PDRMClassification, number> = {
          pattern: 0,
          decision: 0,
          risk: 0,
          mnemonic: 0,
          general: 0
        };
        
        let important = 0;
        
        for (const entry of entries) {
          byClassification[entry.classification]++;
          if (entry.isImportant) important++;
        }
        
        return {
          total: entries.length,
          byClassification,
          important
        };
      }
    }),
    {
      name: 'pdrm-storage',
      storage: createJSONStorage(() => localStorage)
    }
  )
);

// ============================================================================
// PDRM Generation Utilities
// ============================================================================

// "Important-only" heuristics
export function isHighlightImportant(text: string): boolean {
  // Skip very short text (likely accidental)
  if (text.length < 15) return false;
  
  // Skip common/generic words only
  const genericPatterns = [
    /^(the|a|an|this|that|these|those|is|are|was|were|be|been|being)\s*$/i,
    /^\d+\.?\s*$/,  // Just numbers
    /^[\s\W]+$/,    // Just whitespace/punctuation
  ];
  
  if (genericPatterns.some(p => p.test(text))) return false;
  
  // Check for high-signal indicators
  const importantIndicators = [
    /\b(key|important|critical|essential|remember|note|caution|warning)\b/i,
    /\b(principle|concept|definition|formula|rule|law)\b/i,
    /\b(treatment|diagnosis|symptom|sign|cause|effect|mechanism)\b/i,
    /\d+%/,  // Percentages
    /\b\d+\s*(mg|ml|g|kg|mmHg|cm|mm)\b/i,  // Medical values
    /\b(first|second|third|always|never|must|should)\b/i,
  ];
  
  const hasImportantIndicator = importantIndicators.some(p => p.test(text));
  
  // Text with numbers/values is often important
  const hasNumbers = /\d/.test(text);
  
  // Multiple words suggests meaningful content
  const wordCount = text.split(/\s+/).length;
  const isMeaningfulLength = wordCount >= 3 && wordCount <= 100;
  
  return (hasImportantIndicator || hasNumbers) && isMeaningfulLength;
}

// Generate compact summary
export function generateCompactSummary(text: string, maxLength: number = 200): string {
  // Clean up text
  const cleaned = text
    .replace(/\s+/g, ' ')
    .replace(/\n+/g, ' ')
    .trim();
  
  if (cleaned.length <= maxLength) return cleaned;
  
  // Try to break at sentence boundary
  const sentences = cleaned.match(/[^.!?]+[.!?]+/g) || [cleaned];
  let result = '';
  
  for (const sentence of sentences) {
    if ((result + sentence).length <= maxLength) {
      result += sentence;
    } else {
      break;
    }
  }
  
  if (!result) {
    // No complete sentence fits, truncate with ellipsis
    result = cleaned.substring(0, maxLength - 3) + '...';
  }
  
  return result.trim();
}

// Extract key points from text
export function extractKeyPoints(text: string, maxPoints: number = 3): string[] {
  const points: string[] = [];
  
  // Look for numbered lists
  const numberedItems = text.match(/\d+[.)]\s*[^.!?\n]+[.!?]?/g);
  if (numberedItems) {
    points.push(...numberedItems.slice(0, maxPoints).map(s => s.trim()));
  }
  
  // Look for key phrases
  if (points.length < maxPoints) {
    const keyPhrases = [
      /\b(is defined as|refers to|means)\s+([^.!?]+[.!?])/gi,
      /\b(characterized by|consists of)\s+([^.!?]+[.!?])/gi,
      /\b(treatment|management|approach)\s+(is|includes?)\s+([^.!?]+[.!?])/gi,
    ];
    
    for (const pattern of keyPhrases) {
      const matches = text.matchAll(pattern);
      for (const match of matches) {
        if (points.length >= maxPoints) break;
        const phrase = match[0].trim();
        if (phrase.length > 10 && !points.includes(phrase)) {
          points.push(phrase);
        }
      }
    }
  }
  
  // Fallback: first meaningful sentences
  if (points.length < maxPoints) {
    const sentences = text.match(/[^.!?]+[.!?]+/g) || [];
    for (const sentence of sentences) {
      if (points.length >= maxPoints) break;
      const trimmed = sentence.trim();
      if (trimmed.length > 20 && !points.includes(trimmed)) {
        points.push(trimmed);
      }
    }
  }
  
  return points.slice(0, maxPoints);
}

// Get classification color
export function getPdrmColor(classification: PDRMClassification): string {
  switch (classification) {
    case 'pattern': return '#8b5cf6';   // Purple
    case 'decision': return '#3b82f6';  // Blue
    case 'risk': return '#ef4444';      // Red
    case 'mnemonic': return '#f59e0b';  // Orange/Yellow
    case 'general': return '#6b7280';   // Gray
    default: return '#6b7280';
  }
}

// Get classification icon
export function getPdrmIcon(classification: PDRMClassification): string {
  switch (classification) {
    case 'pattern': return '🔷';
    case 'decision': return '⚖️';
    case 'risk': return '⚠️';
    case 'mnemonic': return '💡';
    case 'general': return '📝';
    default: return '📝';
  }
}

// Get classification label
export function getPdrmLabel(classification: PDRMClassification): string {
  switch (classification) {
    case 'pattern': return 'Pattern';
    case 'decision': return 'Decision Rule';
    case 'risk': return 'Risk/Mistake';
    case 'mnemonic': return 'Mnemonic';
    case 'general': return 'General';
    default: return 'General';
  }
}
