// lib/semantic/packs/biology.ts
// Biology subject pack — structure/function/pathway lens for life science textbooks.

import type { SemanticPack, SemanticLabelDefinition } from "../types";

const BIOLOGY_LABELS: SemanticLabelDefinition[] = [
  {
    id: "biology:definition",
    canonicalType: "definition",
    label: "Definition",
    shortLabel: "Def",
    icon: "📖",
    priority: 1,
    maxPerPage: 5,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "biology:core-concept",
    canonicalType: "core-concept",
    label: "Structure",
    shortLabel: "Struct",
    icon: "🧬",
    priority: 2,
    maxPerPage: 4,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
    examples: ["The mitochondrion is a double-membraned organelle."],
  },
  {
    id: "biology:mechanism",
    canonicalType: "mechanism",
    label: "Pathway",
    shortLabel: "Pathway",
    icon: "🔄",
    priority: 2,
    maxPerPage: 5,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
    examples: ["Glycolysis converts glucose → pyruvate, yielding 2 ATP net."],
  },
  {
    id: "biology:process",
    canonicalType: "process",
    label: "Function",
    shortLabel: "Fn",
    icon: "⚙️",
    priority: 3,
    maxPerPage: 4,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "biology:relationship",
    canonicalType: "relationship",
    label: "Regulation",
    shortLabel: "Reg",
    icon: "🔗",
    priority: 3,
    maxPerPage: 4,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
    examples: ["Negative feedback suppresses insulin release when blood glucose falls."],
  },
  {
    id: "biology:exception",
    canonicalType: "exception",
    label: "Exception",
    shortLabel: "Except",
    icon: "🚩",
    priority: 2,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "biology:common-error",
    canonicalType: "common-error",
    label: "Common Mistake",
    shortLabel: "Error",
    icon: "⚠️",
    priority: 2,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "biology:high-yield",
    canonicalType: "high-yield",
    label: "Key Fact",
    shortLabel: "Key",
    icon: "🎯",
    priority: 1,
    maxPerPage: 4,
    requiresExactSourceSpan: true,
    allowPageSynthesis: true,
  },
  {
    id: "biology:memory-anchor",
    canonicalType: "memory-anchor",
    label: "Memory Hook",
    shortLabel: "Hook",
    icon: "💎",
    priority: 3,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: true,
  },
];

export const BIOLOGY_PACK: SemanticPack = {
  id: "biology",
  label: "Biology",
  labels: BIOLOGY_LABELS,
  promptInstructions: [
    "Identify biological structures, their functions, regulatory pathways, and relationships.",
    "Pathways must preserve sequence — glucose → pyruvate → acetyl-CoA, not just the endpoint.",
    "Distinguish structure from function: what it is vs. what it does.",
    "Flag exceptions (anomalies that violate the general rule) and common student mistakes.",
  ],
  rankingRules: [
    { canonicalType: "mechanism",    boostFactor: 1.4, reason: "pathways are the core of bio exams" },
    { canonicalType: "exception",    boostFactor: 1.3, reason: "exceptions are high-yield trap material" },
    { canonicalType: "high-yield",   boostFactor: 1.5, reason: "board priority" },
    { canonicalType: "relationship", boostFactor: 1.2, reason: "regulation links concepts" },
    { canonicalType: "common-error", boostFactor: 1.2 },
  ],
  minimumConfidence: 0.55,
  fallbackPackId: "general",
  tierLabels: { master: "STRUCTURE", step: "PATHWAY", decision: "FUNCTION", danger: "EXCEPTION", pearl: "KEY FACT" },
  whiteboardGrammar: "pathway",
};
