// lib/semantic/packs/history.ts
// History & Humanities pack — event / cause / consequence / theme lens.

import type { SemanticPack, SemanticLabelDefinition } from "../types";

const HISTORY_LABELS: SemanticLabelDefinition[] = [
  {
    id: "history:definition",
    canonicalType: "definition",
    label: "Definition",
    shortLabel: "Def",
    icon: "📖",
    priority: 1,
    maxPerPage: 4,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "history:core-concept",
    canonicalType: "core-concept",
    label: "Concept",
    shortLabel: "Concept",
    icon: "⭐",
    priority: 1,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
    examples: ["Manifest Destiny was the 19th-century belief that U.S. expansion was inevitable."],
  },
  {
    id: "history:cause",
    canonicalType: "cause",
    label: "Cause",
    shortLabel: "Cause",
    icon: "🔄",
    priority: 2,
    maxPerPage: 5,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "history:effect",
    canonicalType: "effect",
    label: "Consequence",
    shortLabel: "Effect",
    icon: "➡️",
    priority: 2,
    maxPerPage: 5,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "history:evidence",
    canonicalType: "evidence",
    label: "Key Event",
    shortLabel: "Event",
    icon: "📅",
    priority: 2,
    maxPerPage: 6,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "history:relationship",
    canonicalType: "relationship",
    label: "Theme",
    shortLabel: "Theme",
    icon: "🔗",
    priority: 2,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "history:exception",
    canonicalType: "exception",
    label: "Debate / Revision",
    shortLabel: "Debate",
    icon: "🚩",
    priority: 3,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
    examples: ["Revisionist historians argue the New Deal prolonged, not shortened, the Depression."],
  },
  {
    id: "history:high-yield",
    canonicalType: "high-yield",
    label: "Key Figure / Date",
    shortLabel: "Key",
    icon: "🎯",
    priority: 1,
    maxPerPage: 5,
    requiresExactSourceSpan: true,
    allowPageSynthesis: true,
  },
  {
    id: "history:memory-anchor",
    canonicalType: "memory-anchor",
    label: "Connecting Thread",
    shortLabel: "Thread",
    icon: "💎",
    priority: 3,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: true,
  },
];

export const HISTORY_PACK: SemanticPack = {
  id: "history",
  label: "History & Humanities",
  labels: HISTORY_LABELS,
  promptInstructions: [
    "Identify causes, key events, consequences, key figures/dates, and interpretive themes.",
    "Causes precede the event; consequences follow from it — maintain temporal direction.",
    "Debates or historiographical revisions are high-yield on essay exams — flag them as exceptions.",
    "Themes connect multiple events across time — identify the thread, not just the individual fact.",
  ],
  rankingRules: [
    { canonicalType: "cause",       boostFactor: 1.3, reason: "causation is the core of history essays" },
    { canonicalType: "effect",      boostFactor: 1.3, reason: "consequences show significance" },
    { canonicalType: "evidence",    boostFactor: 1.2, reason: "specific events anchor claims" },
    { canonicalType: "high-yield",  boostFactor: 1.5, reason: "facts that always appear on exams" },
    { canonicalType: "exception",   boostFactor: 1.2, reason: "historiographic debates earn essay points" },
    { canonicalType: "relationship",boostFactor: 1.2, reason: "themes provide analytical framework" },
  ],
  minimumConfidence: 0.55,
  fallbackPackId: "general",
  tierLabels: { master: "CONCEPT", step: "CAUSE", decision: "EFFECT", danger: "DEBATE", pearl: "KEY FACT" },
  whiteboardGrammar: "timeline",
};
