// lib/semantic/packs/law.ts
// Law pack — rule / analysis / application lens for legal textbooks and case materials.

import type { SemanticPack, SemanticLabelDefinition } from "../types";

const LAW_LABELS: SemanticLabelDefinition[] = [
  {
    id: "law:definition",
    canonicalType: "definition",
    label: "Legal Definition",
    shortLabel: "Def",
    icon: "📖",
    priority: 1,
    maxPerPage: 5,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "law:core-concept",
    canonicalType: "core-concept",
    label: "Rule of Law",
    shortLabel: "Rule",
    icon: "⚖️",
    priority: 1,
    maxPerPage: 4,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
    examples: ["Negligence requires duty, breach, causation, and damages."],
  },
  {
    id: "law:evidence",
    canonicalType: "evidence",
    label: "Precedent",
    shortLabel: "Case",
    icon: "📋",
    priority: 2,
    maxPerPage: 4,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "law:process",
    canonicalType: "process",
    label: "Analysis Step",
    shortLabel: "Analysis",
    icon: "🔍",
    priority: 2,
    maxPerPage: 5,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "law:exception",
    canonicalType: "exception",
    label: "Exception",
    shortLabel: "Except",
    icon: "🚩",
    priority: 2,
    maxPerPage: 4,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
    examples: ["The business judgment rule is an exception to director liability."],
  },
  {
    id: "law:decision-point",
    canonicalType: "decision-point",
    label: "Application",
    shortLabel: "Apply",
    icon: "⚡",
    priority: 2,
    maxPerPage: 4,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "law:common-error",
    canonicalType: "common-error",
    label: "Exam Trap",
    shortLabel: "Trap",
    icon: "⚠️",
    priority: 2,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "law:high-yield",
    canonicalType: "high-yield",
    label: "Bar High Yield",
    shortLabel: "Bar HY",
    icon: "🎯",
    priority: 1,
    maxPerPage: 4,
    requiresExactSourceSpan: true,
    allowPageSynthesis: true,
  },
  {
    id: "law:memory-anchor",
    canonicalType: "memory-anchor",
    label: "Key Distinction",
    shortLabel: "Distinct",
    icon: "💎",
    priority: 3,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: true,
  },
];

export const LAW_PACK: SemanticPack = {
  id: "law",
  label: "Law",
  labels: LAW_LABELS,
  promptInstructions: [
    "Identify rules of law, precedents, exceptions, and application steps using the IRAC lens.",
    "Rules must be stated precisely — exact elements and conjunctive/disjunctive structure matter.",
    "Exceptions narrow rules; flag them clearly — they are the most common exam traps.",
    "Precedents link the rule to its origin case; capture the case name and holding when available.",
    "Application steps show how to map facts to elements — include the conditional logic.",
  ],
  rankingRules: [
    { canonicalType: "core-concept",    boostFactor: 1.5, reason: "black-letter rules are exam core" },
    { canonicalType: "exception",       boostFactor: 1.4, reason: "exceptions are heavily tested" },
    { canonicalType: "evidence",        boostFactor: 1.3, reason: "precedents frame rules" },
    { canonicalType: "common-error",    boostFactor: 1.3, reason: "bar exam trap patterns" },
    { canonicalType: "decision-point",  boostFactor: 1.2, reason: "application is the answer" },
    { canonicalType: "high-yield",      boostFactor: 1.5, reason: "bar priority" },
  ],
  minimumConfidence: 0.55,
  fallbackPackId: "general",
  tierLabels: { master: "RULE", step: "ANALYSIS", decision: "APPLY", danger: "EXCEPTION", pearl: "PRECEDENT" },
  whiteboardGrammar: "case-map",
};
