// lib/semantic/packs/mathematics.ts
// Mathematics pack — theorem / proof / application lens.

import type { SemanticPack, SemanticLabelDefinition } from "../types";

const MATHEMATICS_LABELS: SemanticLabelDefinition[] = [
  {
    id: "mathematics:definition",
    canonicalType: "definition",
    label: "Definition",
    shortLabel: "Def",
    icon: "📖",
    priority: 1,
    maxPerPage: 5,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "mathematics:core-concept",
    canonicalType: "core-concept",
    label: "Theorem",
    shortLabel: "Thm",
    icon: "⭐",
    priority: 1,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
    examples: ["The Pythagorean theorem: a² + b² = c² for right triangles."],
  },
  {
    id: "mathematics:formula",
    canonicalType: "formula",
    label: "Formula",
    shortLabel: "Formula",
    icon: "🧮",
    priority: 2,
    maxPerPage: 8,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "mathematics:process",
    canonicalType: "process",
    label: "Proof Step",
    shortLabel: "Proof",
    icon: "🔢",
    priority: 3,
    maxPerPage: 6,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "mathematics:worked-example",
    canonicalType: "worked-example",
    label: "Worked Example",
    shortLabel: "Ex",
    icon: "📝",
    priority: 3,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "mathematics:exception",
    canonicalType: "exception",
    label: "Edge Case",
    shortLabel: "Edge",
    icon: "🚩",
    priority: 2,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
  },
  {
    id: "mathematics:common-error",
    canonicalType: "common-error",
    label: "Common Error",
    shortLabel: "Error",
    icon: "⚠️",
    priority: 2,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: false,
    examples: ["Confusing 0/0 indeterminate form with the limit value."],
  },
  {
    id: "mathematics:high-yield",
    canonicalType: "high-yield",
    label: "Exam Tip",
    shortLabel: "Tip",
    icon: "🎯",
    priority: 1,
    maxPerPage: 4,
    requiresExactSourceSpan: true,
    allowPageSynthesis: true,
  },
  {
    id: "mathematics:memory-anchor",
    canonicalType: "memory-anchor",
    label: "Mnemonic",
    shortLabel: "Memo",
    icon: "💎",
    priority: 3,
    maxPerPage: 3,
    requiresExactSourceSpan: true,
    allowPageSynthesis: true,
  },
];

export const MATHEMATICS_PACK: SemanticPack = {
  id: "general",
  label: "Mathematics",
  labels: MATHEMATICS_LABELS,
  promptInstructions: [
    "Identify theorems (proved claims), formulas (computational rules), proof steps (logical sequence), and worked examples.",
    "Every formula must include its variable definitions when the source provides them.",
    "Edge cases and common errors are high-priority — note precisely when a rule fails.",
    "Worked examples must use exact source text; do not reconstruct or skip steps.",
  ],
  rankingRules: [
    { canonicalType: "formula",       boostFactor: 1.5, reason: "formulas are the operational core" },
    { canonicalType: "core-concept",  boostFactor: 1.4, reason: "theorems frame the entire section" },
    { canonicalType: "exception",     boostFactor: 1.3, reason: "edge cases appear on exams" },
    { canonicalType: "common-error",  boostFactor: 1.3, reason: "predictable student mistakes" },
    { canonicalType: "worked-example",boostFactor: 1.2, reason: "procedural fluency" },
  ],
  minimumConfidence: 0.55,
  fallbackPackId: "general",
  tierLabels: { master: "THEOREM", step: "PROOF", decision: "APPLY", danger: "ERROR", pearl: "EXAMPLE" },
  whiteboardGrammar: "worked-solution",
};
