// lib/datApex/blueprints/dat-2025.ts
// Official DAT blueprint effective March 2025.
//
// Sources:
//   ADA Dental Admission Test Program Guide (effective March 2025)
//   ADA scoring change announcement (March 2025) — new scaled score reporting
//   ADA announcement of updated Organic Chemistry specifications for 2026
//
// Do NOT edit this file when the ADA publishes new specifications.
// Instead, create lib/datApex/blueprints/dat-2026.ts and update the
// active blueprint pointer in lib/datApex/activeBlueprint.ts.

import type { DatExamBlueprint } from "../blueprint";

export const DAT_BLUEPRINT_2025: DatExamBlueprint = {
  version:             "2025.1",
  effectiveDate:       "2025-03-01",
  scoringModelVersion: "ada-2025",
  sourceReference:     "ADA Dental Admission Test Program, official specifications effective March 2025. New scoring report format introduced March 2025.",
  totalAdministrationMinutes: 315,  // ~5 hours 15 minutes
  tutorialMinutes:     15,
  upcomingChanges: [
    "Organic Chemistry content specifications are updated for 2026 (ADA announcement). Create dat-2026.ts with the revised topicWeights for organic-chemistry when the official specification is published.",
  ],

  sectionFamilyOrder: [
    "natural-sciences",
    "perceptual-ability",
    "reading-comprehension",
    "quantitative-reasoning",
  ],

  breaks: [
    {
      afterSectionFamily: "perceptual-ability",
      durationMinutes:    15,
      optional:           true,
    },
  ],

  sections: [
    {
      family:         "natural-sciences",
      label:          "Survey of the Natural Sciences",
      totalItemCount: 100,
      timeLimitMinutes: 90,
      subSections: [
        {
          id:                    "biology",
          label:                 "Biology",
          itemCount:             40,
          specificationVersion:  "2025",
          topicWeights: [
            { topicId: "cell-biology",              targetPct: 17,  tolerancePct: 5 },
            { topicId: "vertebrate-anatomy",        targetPct: 10,  tolerancePct: 5 },
            { topicId: "developmental-biology",     targetPct: 5,   tolerancePct: 3 },
            { topicId: "genetics",                  targetPct: 15,  tolerancePct: 5 },
            { topicId: "evolution-ecology",         targetPct: 8,   tolerancePct: 3 },
            { topicId: "microbiology",              targetPct: 8,   tolerancePct: 3 },
            { topicId: "diversity-of-life",         targetPct: 5,   tolerancePct: 3 },
            { topicId: "plant-biology",             targetPct: 5,   tolerancePct: 3 },
            { topicId: "animal-systems",            targetPct: 20,  tolerancePct: 5 },
            { topicId: "biochemistry",              targetPct: 7,   tolerancePct: 3 },
          ],
        },
        {
          id:                    "general-chemistry",
          label:                 "General Chemistry",
          itemCount:             30,
          specificationVersion:  "2025",
          topicWeights: [
            { topicId: "stoichiometry",             targetPct: 10,  tolerancePct: 5 },
            { topicId: "gases",                     targetPct: 10,  tolerancePct: 5 },
            { topicId: "liquids-and-solids",        targetPct: 10,  tolerancePct: 5 },
            { topicId: "solutions",                 targetPct: 10,  tolerancePct: 5 },
            { topicId: "acids-and-bases",           targetPct: 15,  tolerancePct: 5 },
            { topicId: "equilibria",                targetPct: 10,  tolerancePct: 5 },
            { topicId: "electrochemistry",          targetPct: 10,  tolerancePct: 5 },
            { topicId: "thermodynamics",            targetPct: 10,  tolerancePct: 5 },
            { topicId: "kinetics",                  targetPct: 10,  tolerancePct: 5 },
            { topicId: "atomic-structure",          targetPct: 5,   tolerancePct: 3 },
          ],
        },
        {
          id:                    "organic-chemistry",
          label:                 "Organic Chemistry",
          itemCount:             30,
          specificationVersion:  "2025",  // 2026 spec updates pending — see upcomingChanges
          topicWeights: [
            { topicId: "mechanisms",                targetPct: 25,  tolerancePct: 5 },
            { topicId: "functional-groups",         targetPct: 20,  tolerancePct: 5 },
            { topicId: "stereochemistry",           targetPct: 15,  tolerancePct: 5 },
            { topicId: "reactions",                 targetPct: 20,  tolerancePct: 5 },
            { topicId: "lab-techniques",            targetPct: 10,  tolerancePct: 3 },
            { topicId: "spectroscopy",              targetPct: 10,  tolerancePct: 3 },
          ],
        },
      ],
    },

    {
      family:           "perceptual-ability",
      label:            "Perceptual Ability",
      totalItemCount:   90,
      timeLimitMinutes: 60,
      subSections: [
        {
          id:                    "perceptual-ability",
          label:                 "Perceptual Ability",
          itemCount:             90,
          specificationVersion:  "2025",
          topicWeights: [
            { topicId: "keyholes",                  targetPct: 17,  tolerancePct: 3 },
            { topicId: "top-front-end",             targetPct: 17,  tolerancePct: 3 },
            { topicId: "angle-ranking",             targetPct: 16,  tolerancePct: 3 },
            { topicId: "hole-punching",             targetPct: 17,  tolerancePct: 3 },
            { topicId: "cube-counting",             targetPct: 16,  tolerancePct: 3 },
            { topicId: "pattern-folding",           targetPct: 17,  tolerancePct: 3 },
          ],
        },
      ],
    },

    {
      family:           "reading-comprehension",
      label:            "Reading Comprehension",
      totalItemCount:   50,
      timeLimitMinutes: 60,
      subSections: [
        {
          id:                    "reading-comprehension",
          label:                 "Reading Comprehension",
          itemCount:             50,
          specificationVersion:  "2025",
          topicWeights: [
            { topicId: "main-idea",                 targetPct: 20,  tolerancePct: 5 },
            { topicId: "detail",                    targetPct: 30,  tolerancePct: 5 },
            { topicId: "inference",                 targetPct: 20,  tolerancePct: 5 },
            { topicId: "tone-and-purpose",          targetPct: 15,  tolerancePct: 5 },
            { topicId: "application",               targetPct: 15,  tolerancePct: 5 },
          ],
        },
      ],
    },

    {
      family:           "quantitative-reasoning",
      label:            "Quantitative Reasoning",
      totalItemCount:   40,
      timeLimitMinutes: 45,
      subSections: [
        {
          id:                    "quantitative-reasoning",
          label:                 "Quantitative Reasoning",
          itemCount:             40,
          specificationVersion:  "2025",
          topicWeights: [
            { topicId: "algebra",                   targetPct: 30,  tolerancePct: 5 },
            { topicId: "numerical-calculations",    targetPct: 20,  tolerancePct: 5 },
            { topicId: "conversions",               targetPct: 10,  tolerancePct: 3 },
            { topicId: "geometry",                  targetPct: 15,  tolerancePct: 5 },
            { topicId: "trigonometry",              targetPct: 10,  tolerancePct: 3 },
            { topicId: "applied-math",              targetPct: 15,  tolerancePct: 5 },
          ],
        },
      ],
    },
  ],
};
