"use client";

/**
 * AutoGeneratedNotesPanel - Memo.cards-style auto-generated notes
 *
 * Features:
 * - Auto-generates notes per chapter/page using universalExtractor
 * - 1-sentence default per concept + exception triggers A-H
 * - Attachments: Procedure/Example/Visual
 * - Left sidebar filters: Patterns/Decisions/Rules/Mnemonics/Flashcards/Highlights
 * - Main list of cards grouped by chapter
 * - Search + Sort functionality
 * - Caches results to avoid regeneration
 */

import React, { useState, useMemo, useEffect, useCallback } from 'react';
import { useConceptStore } from '@/lib/stores/conceptStore';
import {
  extractConceptsFromPage,
  classifyPageType,
  type ConceptOutput,
  type PageType,
  type ExceptionTrigger,
} from '@/lib/universalExtractor';
import {
  processCognitiveStructure,
  type CognitiveProcessingResult,
  type CognitiveGroup,
  type GeneratedDecisionRule,
} from '@/lib/notelab/cognitiveProcessor';

// ============================================================================
// Types
// ============================================================================

interface AutoGeneratedNote {
  id: string;
  conceptId: string;
  coreSentence: string;
  exceptions: Array<{ trigger: ExceptionTrigger; content: string; label: string }>;
  attachments: Array<{ type: 'procedure' | 'example' | 'visual'; content: string }>;
  pageNumber: number;
  chapterId?: string;
  chapterTitle?: string;
  pageType: PageType;
  category: NoteCategory;
  createdAt: number;
}

type NoteCategory = 'pattern' | 'decision' | 'rule' | 'mnemonic' | 'flashcard' | 'highlight' | 'all';
type SortType = 'recent' | 'page' | 'chapter';
type GroupByType = 'chapter' | 'type' | 'none';

interface AutoGeneratedNotesPanelProps {
  documentId: string;
  documentTitle: string;
  chapters: Array<{ id: string; title: string; pageNumber: number; endPage?: number }>;
  currentPage: number;
  getPageText: (pageNumber: number) => Promise<string>;
  onNavigateToPage?: (pageNumber: number) => void;
  onCreateFlashcard?: (note: AutoGeneratedNote) => void;
}

// ============================================================================
// Category Detection
// ============================================================================

function detectCategory(concept: ConceptOutput): NoteCategory {
  const text = concept.core_sentence.toLowerCase();
  const exceptionTypes = concept.exceptions.map(e => e.trigger);

  // Pattern detection
  if (
    /\b(pattern|characteristic|hallmark|typical|pathognomonic|classic)\b/i.test(text) ||
    exceptionTypes.includes('E_ENUMERATION')
  ) {
    return 'pattern';
  }

  // Decision rule detection
  if (
    /\b(if|when|should|must|criteria|indicated|contraindicated)\b/i.test(text) ||
    exceptionTypes.includes('A_CONDITIONAL')
  ) {
    return 'decision';
  }

  // Rule detection
  if (
    /\b(always|never|rule|principle|law|theorem)\b/i.test(text) ||
    exceptionTypes.includes('C_CAUSATION')
  ) {
    return 'rule';
  }

  // Mnemonic detection
  if (
    /\b(remember|mnemonic|acronym|[A-Z]{3,})\b/i.test(text) ||
    concept.page_type === 'DEFINITION'
  ) {
    return 'mnemonic';
  }

  return 'highlight';
}

// ============================================================================
// Note Generation Cache
// ============================================================================

const noteCache = new Map<string, AutoGeneratedNote[]>();

function getCacheKey(documentId: string, pageNumber: number): string {
  return `${documentId}:page:${pageNumber}`;
}

// ============================================================================
// Sub-components
// ============================================================================

function CategoryBadge({ category }: { category: NoteCategory }) {
  const styles: Record<NoteCategory, { bg: string; text: string; icon: string }> = {
    pattern: { bg: 'bg-purple-900/30', text: 'text-purple-400', icon: 'P' },
    decision: { bg: 'bg-blue-900/30', text: 'text-blue-400', icon: 'D' },
    rule: { bg: 'bg-red-900/30', text: 'text-red-400', icon: 'R' },
    mnemonic: { bg: 'bg-yellow-900/30', text: 'text-yellow-400', icon: 'M' },
    flashcard: { bg: 'bg-green-900/30', text: 'text-green-400', icon: 'F' },
    highlight: { bg: 'bg-gray-700', text: 'text-gray-400', icon: 'H' },
    all: { bg: 'bg-gray-700', text: 'text-gray-400', icon: '*' },
  };

  const style = styles[category];
  return (
    <span className={`px-2 py-0.5 rounded text-xs font-bold ${style.bg} ${style.text}`}>
      {style.icon}
    </span>
  );
}

function NoteCard({
  note,
  isExpanded,
  onToggle,
  onNavigate,
  onCreateFlashcard,
}: {
  note: AutoGeneratedNote;
  isExpanded: boolean;
  onToggle: () => void;
  onNavigate?: () => void;
  onCreateFlashcard?: () => void;
}) {
  return (
    <div className="bg-gray-800 rounded-lg border border-gray-700 overflow-hidden">
      {/* Header */}
      <div
        className="flex items-center gap-3 px-4 py-3 cursor-pointer hover:bg-gray-750"
        onClick={onToggle}
      >
        <CategoryBadge category={note.category} />
        <div className="flex-1 min-w-0">
          <p className={`text-sm text-white ${isExpanded ? '' : 'line-clamp-2'}`}>
            {note.coreSentence}
          </p>
        </div>
        <div className="flex items-center gap-2 text-xs text-gray-500">
          <span>p.{note.pageNumber}</span>
          <span className={`transform transition-transform ${isExpanded ? 'rotate-180' : ''}`}>
            ▼
          </span>
        </div>
      </div>

      {/* Expanded Content */}
      {isExpanded && (
        <div className="px-4 pb-4 border-t border-gray-700/50">
          {/* Exceptions */}
          {note.exceptions.length > 0 && (
            <div className="mt-3 space-y-2">
              <p className="text-xs text-gray-500 uppercase">Exceptions</p>
              {note.exceptions.map((exc, idx) => (
                <div key={idx} className="pl-3 border-l-2 border-gray-600">
                  <span className="text-xs text-gray-400">[{exc.label}]</span>
                  <p className="text-sm text-gray-300">{exc.content}</p>
                </div>
              ))}
            </div>
          )}

          {/* Attachments */}
          {note.attachments.length > 0 && (
            <div className="mt-3 space-y-2">
              <p className="text-xs text-gray-500 uppercase">Attachments</p>
              {note.attachments.map((att, idx) => (
                <div
                  key={idx}
                  className={`p-2 rounded text-sm ${
                    att.type === 'procedure'
                      ? 'bg-blue-900/20 text-blue-300'
                      : att.type === 'example'
                      ? 'bg-green-900/20 text-green-300'
                      : 'bg-purple-900/20 text-purple-300'
                  }`}
                >
                  <span className="text-xs uppercase opacity-70">{att.type}: </span>
                  {att.content}
                </div>
              ))}
            </div>
          )}

          {/* Actions */}
          <div className="mt-3 flex gap-2">
            {onNavigate && (
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onNavigate();
                }}
                className="px-3 py-1 bg-gray-700 hover:bg-gray-600 rounded text-xs"
              >
                Go to Page
              </button>
            )}
            {onCreateFlashcard && (
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onCreateFlashcard();
                }}
                className="px-3 py-1 bg-green-700 hover:bg-green-600 rounded text-xs"
              >
                + Flashcard
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

function FilterButton({
  active,
  onClick,
  icon,
  label,
  count,
}: {
  active: boolean;
  onClick: () => void;
  icon: string;
  label: string;
  count: number;
}) {
  return (
    <button
      onClick={onClick}
      className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-sm transition-colors ${
        active ? 'bg-purple-600 text-white' : 'text-gray-300 hover:bg-gray-700'
      }`}
    >
      <span>
        {icon} {label}
      </span>
      <span
        className={`text-xs px-2 py-0.5 rounded ${active ? 'bg-purple-500' : 'bg-gray-700'}`}
      >
        {count}
      </span>
    </button>
  );
}

// ============================================================================
// Main Component
// ============================================================================

export default function AutoGeneratedNotesPanel({
  documentId,
  documentTitle,
  chapters,
  currentPage,
  getPageText,
  onNavigateToPage,
  onCreateFlashcard,
}: AutoGeneratedNotesPanelProps) {
  // State
  const [notes, setNotes] = useState<AutoGeneratedNote[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationProgress, setGenerationProgress] = useState(0);
  const [activeFilter, setActiveFilter] = useState<NoteCategory>('all');
  const [sortBy, setSortBy] = useState<SortType>('page');
  const [groupBy, setGroupBy] = useState<GroupByType>('chapter');
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());

  // Cognitive processing state
  const [cognitiveResult, setCognitiveResult] = useState<CognitiveProcessingResult | null>(null);
  const [showCognitiveView, setShowCognitiveView] = useState(false);

  // Generate notes for current chapter on mount
  useEffect(() => {
    generateNotesForCurrentChapter();
  }, [currentPage, documentId]);

  // Find current chapter
  const currentChapter = useMemo(() => {
    const sortedChapters = [...chapters].sort((a, b) => b.pageNumber - a.pageNumber);
    return sortedChapters.find((ch) => ch.pageNumber <= currentPage);
  }, [chapters, currentPage]);

  // Generate notes for current chapter
  const generateNotesForCurrentChapter = useCallback(async () => {
    if (!currentChapter) return;

    const startPage = currentChapter.pageNumber;
    const endPage = currentChapter.endPage || startPage + 20; // Default 20 pages per chapter

    // Check cache first
    const cachedNotes: AutoGeneratedNote[] = [];
    const pagesToGenerate: number[] = [];

    for (let p = startPage; p <= Math.min(endPage, startPage + 20); p++) {
      const cacheKey = getCacheKey(documentId, p);
      const cached = noteCache.get(cacheKey);
      if (cached) {
        cachedNotes.push(...cached);
      } else {
        pagesToGenerate.push(p);
      }
    }

    // If we have cached notes, add them
    if (cachedNotes.length > 0) {
      setNotes((prev) => {
        const existingIds = new Set(prev.map((n) => n.id));
        const newNotes = cachedNotes.filter((n) => !existingIds.has(n.id));
        return [...prev, ...newNotes];
      });
    }

    // Generate for uncached pages
    if (pagesToGenerate.length > 0) {
      setIsGenerating(true);
      setGenerationProgress(0);

      try {
        for (let i = 0; i < pagesToGenerate.length; i++) {
          const pageNum = pagesToGenerate[i];
          const text = await getPageText(pageNum);

          if (text && text.length > 100) {
            const concepts = extractConceptsFromPage(text, pageNum);
            const pageNotes: AutoGeneratedNote[] = concepts.map((concept) => ({
              id: `note_${concept.id}`,
              conceptId: concept.id,
              coreSentence: concept.core_sentence,
              exceptions: concept.exceptions,
              attachments: concept.attachments.map((a) => ({
                type: a.trigger === 'P_PROCEDURE' ? 'procedure' : a.trigger === 'X_EXAMPLE' ? 'example' : 'visual',
                content: a.content,
              })),
              pageNumber: pageNum,
              chapterId: currentChapter.id,
              chapterTitle: currentChapter.title,
              pageType: concept.page_type,
              category: detectCategory(concept),
              createdAt: Date.now(),
            }));

            // Cache and add notes
            const cacheKey = getCacheKey(documentId, pageNum);
            noteCache.set(cacheKey, pageNotes);

            setNotes((prev) => {
              const existingIds = new Set(prev.map((n) => n.id));
              const newNotes = pageNotes.filter((n) => !existingIds.has(n.id));
              return [...prev, ...newNotes];
            });
          }

          setGenerationProgress(Math.round(((i + 1) / pagesToGenerate.length) * 100));
        }
      } catch (error) {
        console.error('Error generating notes:', error);
      } finally {
        setIsGenerating(false);
      }
    }
  }, [currentChapter, documentId, getPageText]);

  // Process notes cognitively when they change
  useEffect(() => {
    if (notes.length >= 3) {
      console.log('🧠 Running cognitive processing on', notes.length, 'notes');
      const result = processCognitiveStructure(
        notes.map(n => ({
          id: n.id,
          coreSentence: n.coreSentence,
          category: n.category,
          pageNumber: n.pageNumber,
          chapterId: n.chapterId,
        }))
      );
      setCognitiveResult(result);
      console.log('🧠 Cognitive result:', {
        groups: result.groups.length,
        links: result.links.length,
        rules: result.decisionRules.length,
        highYield: result.highYieldNotes.length,
      });
    }
  }, [notes]);

  // Filter and sort notes
  const filteredNotes = useMemo(() => {
    let result = [...notes];

    // Filter by category
    if (activeFilter !== 'all') {
      result = result.filter((n) => n.category === activeFilter);
    }

    // Filter by search
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      result = result.filter(
        (n) =>
          n.coreSentence.toLowerCase().includes(query) ||
          n.exceptions.some((e) => e.content.toLowerCase().includes(query))
      );
    }

    // Sort
    switch (sortBy) {
      case 'recent':
        result.sort((a, b) => b.createdAt - a.createdAt);
        break;
      case 'page':
        result.sort((a, b) => a.pageNumber - b.pageNumber);
        break;
      case 'chapter':
        result.sort((a, b) => (a.chapterTitle || '').localeCompare(b.chapterTitle || ''));
        break;
    }

    return result;
  }, [notes, activeFilter, searchQuery, sortBy]);

  // Group notes
  const groupedNotes = useMemo(() => {
    if (groupBy === 'none') {
      return { 'All Notes': filteredNotes };
    }

    const groups: Record<string, AutoGeneratedNote[]> = {};

    filteredNotes.forEach((note) => {
      let key: string;
      if (groupBy === 'chapter') {
        key = note.chapterTitle || 'Uncategorized';
      } else {
        key = note.category.charAt(0).toUpperCase() + note.category.slice(1) + 's';
      }

      if (!groups[key]) groups[key] = [];
      groups[key].push(note);
    });

    return groups;
  }, [filteredNotes, groupBy]);

  // Stats
  const stats = useMemo(() => {
    const counts: Record<NoteCategory, number> = {
      all: notes.length,
      pattern: notes.filter((n) => n.category === 'pattern').length,
      decision: notes.filter((n) => n.category === 'decision').length,
      rule: notes.filter((n) => n.category === 'rule').length,
      mnemonic: notes.filter((n) => n.category === 'mnemonic').length,
      flashcard: notes.filter((n) => n.category === 'flashcard').length,
      highlight: notes.filter((n) => n.category === 'highlight').length,
    };
    return counts;
  }, [notes]);

  // Toggle expand
  const toggleExpand = (id: string) => {
    setExpandedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  return (
    <div className="h-full flex bg-gray-900" data-testid="auto-notes-panel">
      {/* Sidebar Filters */}
      <div className="w-64 border-r border-gray-700 flex flex-col bg-gray-800">
        {/* Header */}
        <div className="p-4 border-b border-gray-700">
          <h2 className="text-lg font-semibold text-white mb-1">Auto-Generated Notes</h2>
          <p className="text-sm text-gray-400 truncate">{documentTitle}</p>
        </div>

        {/* Generation Progress */}
        {isGenerating && (
          <div className="px-4 py-2 bg-blue-900/30 border-b border-blue-800/30">
            <div className="flex items-center gap-2 text-sm text-blue-400">
              <div className="w-4 h-4 border-2 border-blue-400 border-t-transparent rounded-full animate-spin" />
              Generating... {generationProgress}%
            </div>
          </div>
        )}

        {/* Current Chapter */}
        {currentChapter && (
          <div className="px-4 py-2 bg-purple-900/30 border-b border-purple-800/30">
            <p className="text-xs text-purple-400">
              Current: <span className="text-white font-medium">{currentChapter.title}</span>
            </p>
          </div>
        )}

        {/* Filter Buttons */}
        <div className="flex-1 overflow-auto p-3 space-y-1">
          <p className="text-xs text-gray-500 uppercase mb-2">Filters</p>

          <FilterButton
            active={activeFilter === 'all'}
            onClick={() => setActiveFilter('all')}
            icon="*"
            label="All Notes"
            count={stats.all}
          />
          <FilterButton
            active={activeFilter === 'pattern'}
            onClick={() => setActiveFilter('pattern')}
            icon="P"
            label="Patterns"
            count={stats.pattern}
          />
          <FilterButton
            active={activeFilter === 'decision'}
            onClick={() => setActiveFilter('decision')}
            icon="D"
            label="Decisions"
            count={stats.decision}
          />
          <FilterButton
            active={activeFilter === 'rule'}
            onClick={() => setActiveFilter('rule')}
            icon="R"
            label="Rules"
            count={stats.rule}
          />
          <FilterButton
            active={activeFilter === 'mnemonic'}
            onClick={() => setActiveFilter('mnemonic')}
            icon="M"
            label="Mnemonics"
            count={stats.mnemonic}
          />
          <FilterButton
            active={activeFilter === 'highlight'}
            onClick={() => setActiveFilter('highlight')}
            icon="H"
            label="Highlights"
            count={stats.highlight}
          />
        </div>

        {/* Generate Button */}
        <div className="p-3 border-t border-gray-700">
          <button
            onClick={generateNotesForCurrentChapter}
            disabled={isGenerating}
            className="w-full px-4 py-2 bg-purple-600 hover:bg-purple-500 disabled:opacity-50 rounded-lg text-sm font-medium"
          >
            {isGenerating ? 'Generating...' : 'Regenerate Chapter'}
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex flex-col">
        {/* Search & Controls */}
        <div className="p-4 border-b border-gray-700 bg-gray-800 flex items-center gap-4">
          <div className="flex-1 relative">
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search notes..."
              className="w-full px-4 py-2 pl-10 bg-gray-900 border border-gray-700 rounded-lg focus:outline-none focus:border-purple-500 text-white"
            />
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500">S</span>
          </div>

          <select
            value={sortBy}
            onChange={(e) => setSortBy(e.target.value as SortType)}
            className="px-3 py-2 bg-gray-900 border border-gray-700 rounded-lg text-sm text-white"
          >
            <option value="page">By Page</option>
            <option value="recent">Recent First</option>
            <option value="chapter">By Chapter</option>
          </select>

          <select
            value={groupBy}
            onChange={(e) => setGroupBy(e.target.value as GroupByType)}
            className="px-3 py-2 bg-gray-900 border border-gray-700 rounded-lg text-sm text-white"
          >
            <option value="chapter">Group by Chapter</option>
            <option value="type">Group by Type</option>
            <option value="none">No Grouping</option>
          </select>

          {/* Cognitive View Toggle */}
          <button
            onClick={() => setShowCognitiveView(!showCognitiveView)}
            className={`px-3 py-2 rounded-lg text-sm font-medium transition-colors ${
              showCognitiveView
                ? 'bg-purple-600 text-white'
                : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
            }`}
          >
            {showCognitiveView ? '🧠 Cognitive' : '🧠 Insights'}
          </button>
        </div>

        {/* Cognitive Insights Panel */}
        {showCognitiveView && cognitiveResult && (
          <div className="p-4 border-b border-gray-700 bg-gradient-to-r from-purple-900/30 to-blue-900/30 space-y-4">
            {/* Decision Rules */}
            {cognitiveResult.decisionRules.length > 0 && (
              <div>
                <h4 className="text-sm font-medium text-purple-400 mb-2">
                  📋 Generated Decision Rules ({cognitiveResult.decisionRules.length})
                </h4>
                <div className="space-y-2">
                  {cognitiveResult.decisionRules.slice(0, 3).map((rule) => (
                    <div key={rule.id} className="p-2 bg-gray-800/50 rounded border border-purple-700/30">
                      <p className="text-xs text-gray-300">
                        <span className="text-blue-400">IF:</span> {rule.condition}
                      </p>
                      <p className="text-xs text-gray-300">
                        <span className="text-green-400">THEN:</span> {rule.action}
                      </p>
                      {rule.exceptions.length > 0 && (
                        <p className="text-xs text-amber-400 mt-1">
                          ⚠️ {rule.exceptions.length} exception(s)
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* High-Yield Notes */}
            {cognitiveResult.highYieldNotes.length > 0 && (
              <div>
                <h4 className="text-sm font-medium text-yellow-400 mb-2">
                  ⭐ High-Yield ({cognitiveResult.highYieldNotes.length})
                </h4>
                <p className="text-xs text-gray-400">
                  {cognitiveResult.highYieldNotes.length} notes marked as high-yield for exam focus
                </p>
              </div>
            )}

            {/* Weak Areas */}
            {cognitiveResult.weakAreas.length > 0 && (
              <div>
                <h4 className="text-sm font-medium text-red-400 mb-2">
                  ⚠️ Weak Areas ({cognitiveResult.weakAreas.length})
                </h4>
                <ul className="text-xs text-gray-400 space-y-1">
                  {cognitiveResult.weakAreas.slice(0, 3).map((area, idx) => (
                    <li key={idx}>• {area}</li>
                  ))}
                </ul>
              </div>
            )}

            {/* Cognitive Groups Summary */}
            <div>
              <h4 className="text-sm font-medium text-teal-400 mb-2">
                🔗 Cognitive Groups ({cognitiveResult.groups.length})
              </h4>
              <div className="flex flex-wrap gap-2">
                {cognitiveResult.groups.slice(0, 5).map((group) => (
                  <span
                    key={group.id}
                    className={`px-2 py-1 rounded text-xs ${
                      group.highYield
                        ? 'bg-yellow-900/30 text-yellow-400'
                        : 'bg-gray-700 text-gray-300'
                    }`}
                  >
                    {group.title} ({group.noteIds.length})
                  </span>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Content */}
        <div className="flex-1 overflow-auto p-4">
          {filteredNotes.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-gray-500">
              <div className="text-6xl mb-4">📝</div>
              <p className="text-lg">No notes generated yet</p>
              <p className="text-sm mt-2">
                {isGenerating
                  ? 'Generating notes from page content...'
                  : 'Click "Regenerate Chapter" to auto-generate notes'}
              </p>
            </div>
          ) : (
            <div className="space-y-6">
              {Object.entries(groupedNotes).map(([groupName, groupNotes]) => (
                <div key={groupName}>
                  {groupBy !== 'none' && (
                    <h3 className="text-sm font-medium text-gray-400 mb-3 sticky top-0 bg-gray-900 py-2">
                      {groupName} ({groupNotes.length})
                    </h3>
                  )}

                  <div className="space-y-3">
                    {groupNotes.map((note) => (
                      <NoteCard
                        key={note.id}
                        note={note}
                        isExpanded={expandedIds.has(note.id)}
                        onToggle={() => toggleExpand(note.id)}
                        onNavigate={onNavigateToPage ? () => onNavigateToPage(note.pageNumber) : undefined}
                        onCreateFlashcard={onCreateFlashcard ? () => onCreateFlashcard(note) : undefined}
                      />
                    ))}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
