/**
 * Pattern-Driven Reading Model (PDRM) 2.0 Engine
 * Automatically generates structured PDRM entries from text analysis
 */

import { enhancedHybridAnalysisEngine, type ComprehensiveAnalysisResult } from './enhancedHybridAnalysis';
import { getPatternById, DAT_PATTERNS, type Pattern } from '@/types/patterns';
import { generateMnemonic } from './mnemonicAI';
import summarizeText from './aiSummary';

export interface PDRMEntry {
  id: string;
  userId: string;
  bookId: string;
  thoughtUnitId: string;
  page: number;
  sourceText: string;
  
  // Core PDRM 2.0 fields
  pattern: {
    id: string;
    name: string;
    confidence: number;
    category: string;
  };
  decisionRule: string;
  whyItWorks: string;
  understandingDetail: string[];
  applicationExample: string;
  crossLink: string[];
  reflectionPrompt: string;
  
  // Metadata
  confidenceScore: number;
  autoGenerated: boolean;
  manuallyEdited: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PDRMGenerationOptions {
  enableAutoAnalysis: boolean;
  enhanceUnderstandingDetail: boolean;
  generateCrossLinks: boolean;
  includeReflectionPrompts: boolean;
  maxUnderstandingDetails: number;
  maxCrossLinks: number;
}

class PDRMEngine {
  private analysisCache = new Map<string, ComprehensiveAnalysisResult>();

  /**
   * Generate PDRM entry from selected text
   */
  async generatePDRMEntry(
    sourceText: string,
    context: {
      userId: string;
      bookId: string;
      thoughtUnitId: string;
      page: number;
    },
    options: PDRMGenerationOptions = {
      enableAutoAnalysis: true,
      enhanceUnderstandingDetail: true,
      generateCrossLinks: true,
      includeReflectionPrompts: true,
      maxUnderstandingDetails: 5,
      maxCrossLinks: 3
    }
  ): Promise<PDRMEntry> {
    const startTime = Date.now();

    // Step 1: Analyze text for patterns and structure
    const analysisResult = await enhancedHybridAnalysisEngine.analyzeText(sourceText, {
      userId: context.userId,
      enableSemanticClustering: true,
      confidenceThreshold: 0.6,
      maxTopicClusters: 3,
      semanticSimilarityThreshold: 0.4,
      includePersonalization: true,
      enableProgressiveRefinement: true,
      generateLearningObjectives: true,
      assessCognitiveLoad: true,
      provideTutorialGuidance: true,
      adaptToUserLevel: true,
      cacheResults: true,
      detailedMetrics: true
    });

    // Step 2: Identify most relevant pattern
    const detectedPattern = await this.identifyBestPattern(sourceText, analysisResult);

    // Step 3: Generate PDRM fields
    const decisionRule = await this.generateDecisionRule(detectedPattern, sourceText, analysisResult);
    const whyItWorks = await this.generateWhyExplanation(detectedPattern, sourceText, analysisResult);
    const understandingDetail = await this.generateUnderstandingDetail(
      sourceText, 
      analysisResult, 
      options.maxUnderstandingDetails
    );
    const applicationExample = await this.generateApplicationExample(detectedPattern, sourceText);
    const crossLink = options.generateCrossLinks ? 
      await this.generateCrossLinks(detectedPattern, analysisResult, options.maxCrossLinks) : [];
    const reflectionPrompt = options.includeReflectionPrompts ? 
      this.generateReflectionPrompt(detectedPattern, sourceText) : "";

    // Step 4: Calculate confidence and create entry
    const confidenceScore = this.calculateOverallConfidence(
      detectedPattern,
      analysisResult.confidenceScores
    );

    const pdrmEntry: PDRMEntry = {
      id: `pdrm-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      userId: context.userId,
      bookId: context.bookId,
      thoughtUnitId: context.thoughtUnitId,
      page: context.page,
      sourceText,
      pattern: {
        id: detectedPattern.pattern.id,
        name: detectedPattern.pattern.name,
        confidence: detectedPattern.confidence,
        category: detectedPattern.pattern.category
      },
      decisionRule,
      whyItWorks,
      understandingDetail,
      applicationExample,
      crossLink,
      reflectionPrompt,
      confidenceScore,
      autoGenerated: true,
      manuallyEdited: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    return pdrmEntry;
  }

  /**
   * Identify the best matching pattern for the text
   */
  private async identifyBestPattern(
    text: string, 
    analysisResult: ComprehensiveAnalysisResult
  ): Promise<{ pattern: Pattern; confidence: number; reasoning: string }> {
    const lowerText = text.toLowerCase();
    const patternScores: { pattern: Pattern; score: number; reasoning: string }[] = [];

    // Analyze each available pattern
    for (const pattern of DAT_PATTERNS) {
      let score = 0;
      let reasoning = "";

      // Keyword matching
      const keywordMatches = this.countKeywordMatches(lowerText, pattern);
      score += keywordMatches * 0.3;

      // Semantic similarity with pattern description
      const semanticScore = this.calculateSemanticSimilarity(text, pattern.description);
      score += semanticScore * 0.4;

      // Structure matching
      const structureScore = this.calculateStructureMatch(text, pattern, analysisResult);
      score += structureScore * 0.3;

      reasoning = `Keywords: ${keywordMatches}, Semantic: ${semanticScore.toFixed(2)}, Structure: ${structureScore.toFixed(2)}`;
      
      patternScores.push({ pattern, score, reasoning });
    }

    // Sort by score and return best match
    patternScores.sort((a, b) => b.score - a.score);
    const bestMatch = patternScores[0];

    return {
      pattern: bestMatch.pattern,
      confidence: Math.min(bestMatch.score, 1.0),
      reasoning: bestMatch.reasoning
    };
  }

  /**
   * Generate decision rule for the pattern
   */
  private async generateDecisionRule(
    patternMatch: { pattern: Pattern; confidence: number },
    sourceText: string,
    analysisResult: ComprehensiveAnalysisResult
  ): Promise<string> {
    const pattern = patternMatch.pattern;
    
    // Use pattern's existing rules as foundation
    const baseRules = pattern.rules.map(rule => `${rule.key}: ${rule.description}`).join('\n');
    
    // Enhance with context-specific reasoning
    const contextualEnhancement = this.generateContextualReasoning(sourceText, analysisResult);
    
    return `**${pattern.name} Decision Framework:**\n\n${baseRules}\n\n**Applied to this context:**\n${contextualEnhancement}`;
  }

  /**
   * Generate why explanation
   */
  private async generateWhyExplanation(
    patternMatch: { pattern: Pattern; confidence: number },
    sourceText: string,
    analysisResult: ComprehensiveAnalysisResult
  ): Promise<string> {
    const pattern = patternMatch.pattern;
    const complexity = analysisResult.comprehensiveInsights.overallComplexity;
    const cognitiveLoad = analysisResult.comprehensiveInsights.cognitiveLoad.totalLoad;

    let explanation = `This pattern works here because:\n\n`;
    
    // Pattern-specific reasoning
    explanation += `1. **Pattern Match**: The text exhibits ${pattern.name} characteristics with ${Math.round(patternMatch.confidence * 100)}% confidence.\n\n`;
    
    // Cognitive alignment
    explanation += `2. **Cognitive Alignment**: The ${complexity} complexity level aligns with pattern application (cognitive load: ${Math.round(cognitiveLoad * 100)}%).\n\n`;
    
    // Structural reasoning
    const mainIdea = analysisResult.enhancedMainIdeaAnalysis.primaryIdea;
    explanation += `3. **Structural Fit**: The main idea "${mainIdea.substring(0, 100)}..." follows the pattern's logic flow.\n\n`;
    
    // Learning effectiveness
    explanation += `4. **Learning Enhancement**: This pattern helps break down complex information into manageable, memorable components.`;

    return explanation;
  }

  /**
   * Generate enhanced understanding details
   */
  private async generateUnderstandingDetail(
    sourceText: string,
    analysisResult: ComprehensiveAnalysisResult,
    maxDetails: number
  ): Promise<string[]> {
    const details: string[] = [];
    
    // Extract from main idea analysis
    const mainPoints = analysisResult.enhancedMainIdeaAnalysis.supportingPoints.slice(0, 2);
    details.push(...mainPoints.map(point => `**Key Point**: ${point}`));
    
    // Extract from support analysis
    const evidenceItems = analysisResult.supportAnalysis.classifications
      .filter(c => c.type === 'evidence')
      .slice(0, 2)
      .map(c => `**Evidence**: ${c.text.substring(0, 100)}...`);
    details.push(...evidenceItems);
    
    // Add learning objectives insights
    const learningInsights = analysisResult.comprehensiveInsights.learningObjectives
      .slice(0, 2)
      .map(obj => `**Learning Focus**: ${obj.objective}`);
    details.push(...learningInsights);
    
    // Add comprehension strategies
    const strategyInsights = analysisResult.comprehensiveInsights.comprehensionStrategies
      .filter(s => s.applicability > 0.7)
      .slice(0, 1)
      .map(s => `**Study Strategy**: ${s.description}`);
    details.push(...strategyInsights);

    return details.slice(0, maxDetails);
  }

  /**
   * Generate application example
   */
  private async generateApplicationExample(
    patternMatch: { pattern: Pattern; confidence: number },
    sourceText: string
  ): Promise<string> {
    const pattern = patternMatch.pattern;
    
    // Use pattern's existing examples as inspiration
    const patternExample = pattern.examples[0] || "Apply this pattern to similar content";
    
    // Create contextual application
    const textPreview = sourceText.substring(0, 200);
    
    return `**Pattern Application:**\n\nUsing ${pattern.name} with this content:\n"${textPreview}..."\n\n**How to apply:**\n${patternExample}\n\n**Practice tip:** Look for similar structures in other texts and apply the same reasoning framework.`;
  }

  /**
   * Generate cross-links to related patterns/concepts
   */
  private async generateCrossLinks(
    patternMatch: { pattern: Pattern; confidence: number },
    analysisResult: ComprehensiveAnalysisResult,
    maxLinks: number
  ): Promise<string[]> {
    const crossLinks: string[] = [];
    const currentCategory = patternMatch.pattern.category;
    
    // Find related patterns in same category
    const relatedPatterns = DAT_PATTERNS
      .filter(p => p.category === currentCategory && p.id !== patternMatch.pattern.id)
      .slice(0, 2);
    
    crossLinks.push(...relatedPatterns.map(p => `Related Pattern: ${p.name}`));
    
    // Add concept connections from analysis
    const conceptConnections = analysisResult.enhancedMainIdeaAnalysis.topicClusters
      .slice(0, maxLinks - relatedPatterns.length)
      .map(cluster => `Connected Concept: ${cluster.topicName}`);
    
    crossLinks.push(...conceptConnections);
    
    return crossLinks.slice(0, maxLinks);
  }

  /**
   * Generate reflection prompt
   */
  private generateReflectionPrompt(
    patternMatch: { pattern: Pattern; confidence: number },
    sourceText: string
  ): string {
    const pattern = patternMatch.pattern;
    
    const prompts = [
      `How does the ${pattern.name} pattern help you understand this concept better?`,
      `What would happen if you applied a different pattern to this same text?`,
      `Can you identify where this pattern might be useful in other contexts?`,
      `What aspects of this text made the ${pattern.name} pattern most applicable?`,
      `How confident are you in applying this pattern to similar content?`
    ];
    
    // Select prompt based on pattern category and complexity
    const promptIndex = (pattern.category.length + sourceText.length) % prompts.length;
    return prompts[promptIndex];
  }

  /**
   * Count keyword matches for pattern
   */
  private countKeywordMatches(text: string, pattern: Pattern): number {
    let matches = 0;
    const keywords = [
      ...pattern.name.toLowerCase().split(' '),
      ...pattern.description.toLowerCase().split(' ').filter(word => word.length > 3),
      ...pattern.examples.join(' ').toLowerCase().split(' ').filter(word => word.length > 3)
    ];
    
    keywords.forEach(keyword => {
      if (text.includes(keyword)) matches++;
    });
    
    return Math.min(matches / keywords.length, 1.0);
  }

  /**
   * Calculate semantic similarity (simplified)
   */
  private calculateSemanticSimilarity(text1: string, text2: string): number {
    const words1 = new Set(text1.toLowerCase().split(/\W+/).filter(w => w.length > 3));
    const words2 = new Set(text2.toLowerCase().split(/\W+/).filter(w => w.length > 3));
    
    const intersection = new Set([...words1].filter(word => words2.has(word)));
    const union = new Set([...words1, ...words2]);
    
    return union.size > 0 ? intersection.size / union.size : 0;
  }

  /**
   * Calculate structure match score
   */
  private calculateStructureMatch(
    text: string, 
    pattern: Pattern, 
    analysisResult: ComprehensiveAnalysisResult
  ): number {
    let score = 0;
    
    // Check if text structure matches pattern expectations
    const hasDefinitions = text.toLowerCase().includes('defined as') || text.toLowerCase().includes('means');
    const hasExamples = text.toLowerCase().includes('for example') || text.toLowerCase().includes('such as');
    const hasEvidence = text.toLowerCase().includes('research') || text.toLowerCase().includes('studies');
    
    // Score based on pattern category
    if ((pattern.category === 'organic-chemistry' || pattern.category === 'general-chemistry') && (hasDefinitions || hasExamples)) score += 0.3;
    if (pattern.category === 'biology' && hasEvidence) score += 0.3;
    if (pattern.category === 'pat' && (hasDefinitions || hasEvidence)) score += 0.3;
    if (pattern.category === 'reading-comprehension' && (hasExamples || hasEvidence)) score += 0.3;
    
    // Add coherence score from analysis
    score += analysisResult.comprehensiveInsights.structuralCoherence * 0.7;
    
    return Math.min(score, 1.0);
  }

  /**
   * Generate contextual reasoning
   */
  private generateContextualReasoning(
    sourceText: string,
    analysisResult: ComprehensiveAnalysisResult
  ): string {
    const complexity = analysisResult.comprehensiveInsights.overallComplexity;
    const mainIdea = analysisResult.enhancedMainIdeaAnalysis.primaryIdea;
    const supportCount = analysisResult.supportAnalysis.classifications.length;
    
    return `Given the ${complexity} complexity and ${supportCount} supporting elements, this pattern applies because the main idea "${mainIdea.substring(0, 150)}..." demonstrates the key characteristics expected in this framework.`;
  }

  /**
   * Calculate overall confidence score
   */
  private calculateOverallConfidence(
    patternMatch: { pattern: Pattern; confidence: number },
    analysisScores: any
  ): number {
    const patternConfidence = patternMatch.confidence;
    const analysisQuality = analysisScores?.overallAnalysisQuality || 0.7;
    
    return (patternConfidence * 0.6 + analysisQuality * 0.4);
  }

  /**
   * Update PDRM entry with manual edits
   */
  async updatePDRMEntry(entryId: string, updates: Partial<PDRMEntry>): Promise<PDRMEntry> {
    // In a real implementation, this would update the database
    const updatedEntry: PDRMEntry = {
      ...updates as PDRMEntry,
      manuallyEdited: true,
      updatedAt: new Date().toISOString()
    };
    
    return updatedEntry;
  }

  /**
   * Enhance understanding detail automatically
   */
  async enhanceUnderstandingDetail(
    currentDetails: string[],
    sourceText: string,
    analysisResult?: ComprehensiveAnalysisResult
  ): Promise<string[]> {
    if (!analysisResult) {
      analysisResult = await enhancedHybridAnalysisEngine.analyzeText(sourceText);
    }

    const enhancedDetails = [...currentDetails];
    
    // Add insights from cognitive load analysis
    if (analysisResult.comprehensiveInsights.cognitiveLoad.recommendations.length > 0) {
      enhancedDetails.push(`**Study Tip**: ${analysisResult.comprehensiveInsights.cognitiveLoad.recommendations[0]}`);
    }
    
    // Add comprehension strategies
    const topStrategy = analysisResult.comprehensiveInsights.comprehensionStrategies
      .find(s => s.applicability > 0.8);
    if (topStrategy) {
      enhancedDetails.push(`**Comprehension Strategy**: ${topStrategy.description}`);
    }
    
    // Add connection insights
    if (analysisResult.enhancedMainIdeaAnalysis.supportingPoints.length > 0) {
      const keyConnection = analysisResult.enhancedMainIdeaAnalysis.supportingPoints[0];
      enhancedDetails.push(`**Key Connection**: ${keyConnection}`);
    }
    
    return enhancedDetails.slice(0, 7); // Limit to 7 details max
  }
}

// Export singleton instance
export const pdrmEngine = new PDRMEngine();
export default pdrmEngine;
