// lib/notelab/canonicalStudyGuideBuilder.ts
// Zero-AI Adaptive Study Guide builder grounded in canonical thought units.
//
// Converts CanonicalEntryInput[] → AdaptiveStudySheet without an API call.
// Sections are ordered following the cognitive learning sequence:
//
//   ORIENT → UNDERSTAND → CONNECT → APPLY → RECALL → REVIEW
//
// Section content is derived directly from the canonical unit's text, label,
// and canonicalType rather than generated by a language model. This makes the
// guide instantly available, deterministic, and traceable back to source units.
//
// The subject-profile system (studySheetProfiles.ts) determines which section
// labels are used so the output is compatible with AdaptiveStudySheetCard.tsx.

import { resolveImportanceLevel } from "@/lib/reader/importanceBadge";
import type { ProfileId } from "./studySheetProfiles";
import type { AdaptiveStudySheet, StudySheetSection } from "./adaptiveStudySheet";

// ---------------------------------------------------------------------------
// Input / option types
// ---------------------------------------------------------------------------

export interface CanonicalGuideEntry {
  id: string;
  text: string;
  title?: string;
  canonicalType?: string;
  importanceScore?: number;
  priorityTier?: number;
}

export type LearnerLevel = "new" | "intermediate" | "advanced";

export interface CanonicalGuideOpts {
  /** Force a specific profile. Auto-detected from entry types when omitted. */
  profileId?: ProfileId;
  /** New learners get fuller explanations; advanced get nuance + exceptions. */
  learnerLevel?: LearnerLevel;
  /** Unit ids recently missed in recall — those units are surfaced first. */
  weakUnitIds?: string[];
  topic?: string;
  subject?: string;
  pageNumber?: number;
}

// ---------------------------------------------------------------------------
// Cognitive phase ordering
//
// Each canonical type belongs to a learning phase.
// Lower phase number = shown earlier in the guide.
// ---------------------------------------------------------------------------

const PHASE: Partial<Record<string, number>> = {
  // 0 — ORIENT
  "definition":        0,
  "core-concept":      0,

  // 1 — UNDERSTAND
  "cause":             1,
  "effect":            1,
  "process":           1,
  "mechanism":         1,

  // 2 — CONNECT
  "relationship":      2,
  "evidence":          2,
  "classification":    2,

  // 3 — APPLY
  "indication":        3,
  "treatment":         3,
  "clinical-pearl":    3,
  "worked-example":    3,
  "decision-point":    3,

  // 4 — RECALL
  "warning":           4,
  "contraindication":  4,
  "high-yield":        4,
  "exception":         4,
  "common-error":      4,
  "memory-anchor":     4,
  "formula":           4,
};

const phaseOf = (ct?: string): number => PHASE[ct ?? ""] ?? 2;

// ---------------------------------------------------------------------------
// Section metadata per canonical type
// Labels and icons align with the existing StudySheetProfile section specs
// so the same AdaptiveStudySheetCard can render both AI and canonical guides.
// ---------------------------------------------------------------------------

interface SectionMeta {
  label: string;
  icon: string;
}

const SECTION_META: Partial<Record<string, SectionMeta>> = {
  "definition":        { label: "Core Concept",          icon: "🎯" },
  "core-concept":      { label: "Core Concept",          icon: "🎯" },
  "cause":             { label: "Cause",                 icon: "↩️" },
  "effect":            { label: "Effect",                icon: "↪️" },
  "process":           { label: "Sequence",              icon: "📋" },
  "mechanism":         { label: "Mechanism",             icon: "⚙️" },
  "relationship":      { label: "Connection",            icon: "🔗" },
  "evidence":          { label: "Evidence",              icon: "📊" },
  "classification":    { label: "Classification",        icon: "🗂️" },
  "indication":        { label: "Indication",            icon: "✅" },
  "treatment":         { label: "Treatment",             icon: "💊" },
  "clinical-pearl":    { label: "Clinical Pearl",        icon: "💎" },
  "worked-example":    { label: "Worked Example",        icon: "🧮" },
  "decision-point":    { label: "Decision Point",        icon: "🌳" },
  "warning":           { label: "Common Trap",           icon: "⚠️" },
  "contraindication":  { label: "Contraindication",      icon: "🚫" },
  "high-yield":        { label: "High-Yield Fact",       icon: "⭐" },
  "exception":         { label: "Exception",             icon: "⚠️" },
  "common-error":      { label: "Mistakes to Avoid",     icon: "❌" },
  "memory-anchor":     { label: "Memory Hook",           icon: "🧠" },
  "formula":           { label: "Key Formula",           icon: "📐" },
  "complication":      { label: "Complication / Risk",   icon: "🚧" },
};

const DEFAULT_META: SectionMeta = { label: "Key Point", icon: "📌" };

// ---------------------------------------------------------------------------
// Subject auto-detection from canonical type cluster
// ---------------------------------------------------------------------------

function detectProfileId(entries: CanonicalGuideEntry[]): ProfileId {
  const types = new Set(entries.map((e) => e.canonicalType ?? ""));
  if (types.has("formula") || types.has("worked-example")) return "chemistry";
  if (types.has("indication") || types.has("contraindication") || types.has("clinical-pearl") || types.has("treatment")) return "dental";
  if (types.has("mechanism") && types.has("process")) return "biology";
  return "general";
}

// ---------------------------------------------------------------------------
// Content generation per learner level
//
// New       → show full text + label context
// Intermediate → show text, compress to first 2 sentences
// Advanced  → show only exceptions, traps, nuance; skip basic definitions
// ---------------------------------------------------------------------------

const IMPORTANCE_RANK = { critical: 0, high: 1, medium: 2, reference: 3 } as const;

function shouldIncludeForLevel(
  canonicalType: string | undefined,
  level: LearnerLevel,
): boolean {
  if (level !== "advanced") return true;
  // Advanced learners skip basic definitions — they already know them.
  return canonicalType !== "definition" && canonicalType !== "core-concept";
}

function formatContent(text: string, level: LearnerLevel): string {
  if (level === "new") return text;
  // Intermediate / advanced: cap at 2 sentences
  const sentences = text.match(/[^.!?]+[.!?]+/g) ?? [text];
  return sentences.slice(0, 2).join(" ").trim();
}

// ---------------------------------------------------------------------------
// buildStudyGuideFromCanonical
// ---------------------------------------------------------------------------

/**
 * Build an AdaptiveStudySheet from canonical thought units without any AI call.
 *
 * The guide follows the cognitive sequence:
 *   Orient → Understand → Connect → Apply → Recall → Review
 *
 * Units are sorted by:
 *   1. Weak units (recently missed in recall) first
 *   2. Phase (orient before recall)
 *   3. Importance (critical before reference)
 *
 * The returned sheet is compatible with AdaptiveStudySheetCard.tsx and can be
 * stored in UltraNote.adaptiveStudySheet via saveUltraNote().
 */
export function buildStudyGuideFromCanonical(
  entries: CanonicalGuideEntry[],
  opts: CanonicalGuideOpts = {},
): AdaptiveStudySheet {
  const {
    profileId,
    learnerLevel = "intermediate",
    weakUnitIds  = [],
    topic        = "Concept",
    subject      = "",
    pageNumber,
  } = opts;

  const weakSet = new Set(weakUnitIds);
  const resolvedProfile = profileId ?? detectProfileId(entries);

  // Sort: weak units first, then phase order, then importance
  const sorted = [...entries].sort((a, b) => {
    const aWeak = weakSet.has(a.id) ? -1 : 0;
    const bWeak = weakSet.has(b.id) ? -1 : 0;
    if (aWeak !== bWeak) return aWeak - bWeak;

    const phaseA = phaseOf(a.canonicalType);
    const phaseB = phaseOf(b.canonicalType);
    if (phaseA !== phaseB) return phaseA - phaseB;

    const levelA = resolveImportanceLevel(a.importanceScore, a.priorityTier);
    const levelB = resolveImportanceLevel(b.importanceScore, b.priorityTier);
    return IMPORTANCE_RANK[levelA] - IMPORTANCE_RANK[levelB];
  });

  // Extract the core idea from the first definition/core-concept unit
  const coreUnit =
    sorted.find((e) => e.canonicalType === "definition" || e.canonicalType === "core-concept")
    ?? sorted[0];
  const coreIdea = coreUnit
    ? (coreUnit.text.match(/^[^.!?]+[.!?]/)?.[0]?.trim() ?? coreUnit.text.slice(0, 120).trim())
    : "See source material for core concept.";

  // Build sections
  const sections: StudySheetSection[] = [];
  const seenLabels = new Set<string>();

  for (const entry of sorted) {
    const ct = entry.canonicalType;
    if (!shouldIncludeForLevel(ct, learnerLevel)) continue;

    const meta = (ct && SECTION_META[ct]) ?? DEFAULT_META;

    // Merge same-type sections for new learners; keep only first for advanced
    const dedupeKey = ct ?? entry.id;
    if (learnerLevel === "advanced" && seenLabels.has(dedupeKey)) continue;
    seenLabels.add(dedupeKey);

    const content = formatContent(entry.text, learnerLevel);
    const label   = entry.title ? `${meta.label}: ${entry.title}` : meta.label;

    // For process/sequence types, split on → or numbered steps if present
    const subItems = extractSubItems(entry.text, ct);

    sections.push({
      label,
      icon:       meta.icon,
      content,
      subItems:   subItems.length > 0 ? subItems : null,
      anchorId:   null,
      sourcePage: pageNumber ?? null,
      sourceText: entry.text.length > 200 ? entry.text : null,
    });
  }

  // Recall section — always last: one recall question per critical/high unit
  const recallUnits = sorted.filter((e) => {
    const level = resolveImportanceLevel(e.importanceScore, e.priorityTier);
    return level === "critical" || level === "high";
  }).slice(0, 3);

  if (recallUnits.length > 0) {
    const recallContent = recallUnits
      .map((e) => buildRecallQuestion(e))
      .join("\n");
    sections.push({
      label:      "Recall Check",
      icon:       "🔁",
      content:    recallContent,
      subItems:   recallUnits.map((e) => buildRecallQuestion(e)),
      anchorId:   null,
      sourcePage: pageNumber ?? null,
      sourceText: null,
    });
  }

  return {
    profileId:         resolvedProfile,
    documentType:      subject || resolvedProfile,
    sheetStyle:        sheetStyleForProfile(resolvedProfile),
    concept:           topic,
    subjectArea:       subject || resolvedProfile,
    coreIdea,
    sections,
    formula:           extractFormula(entries),
    diagram:           null,
    practiceQuestions: null,
    connections:       buildConnections(entries),
    relatedTopics:     null,
    canonicalSourcePage:  pageNumber ?? null,
    detectedProfileId: resolvedProfile,
    selectedProfileId: resolvedProfile,
    generatorVersion:  "canonical-v1",
    profileVersion:    null,
    schemaVersion:     1,
    generatedAt:       new Date().toISOString(),
    modelId:           "canonical",  // no model — derived from units
    sourceDocumentId:  null,
    validationIssues:  null,
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sheetStyleForProfile(profileId: ProfileId): AdaptiveStudySheet["sheetStyle"] {
  if (profileId === "dental") return "clinical";
  if (profileId === "law") return "legal";
  if (profileId === "dat" || profileId === "chemistry" || profileId === "math") return "exam-prep";
  return "reference";
}

function extractSubItems(text: string, canonicalType?: string): string[] {
  if (canonicalType !== "process" && canonicalType !== "sequence" && canonicalType !== "decision-point") return [];
  // Split on arrow sequences or numbered/lettered lists
  const arrowSplit = text.split(/\s*→\s*/);
  if (arrowSplit.length > 1) return arrowSplit.map((s) => s.trim()).filter(Boolean);
  const numberedMatch = text.match(/\d+[.)]\s+[^\d.]+/g);
  if (numberedMatch && numberedMatch.length > 1) return numberedMatch.map((s) => s.trim());
  return [];
}

function buildRecallQuestion(entry: CanonicalGuideEntry): string {
  const label = entry.title ?? entry.text.slice(0, 50).trim();
  const ct = entry.canonicalType;
  if (ct === "cause")          return `What is the primary cause of ${label}?`;
  if (ct === "effect")         return `What is the direct result of ${label}?`;
  if (ct === "mechanism")      return `Explain the mechanism of ${label}.`;
  if (ct === "process")        return `List the steps in ${label}.`;
  if (ct === "warning"
    || ct === "contraindication") return `What is the key warning about ${label}?`;
  if (ct === "indication")     return `When is ${label} indicated?`;
  if (ct === "treatment")      return `What is the treatment approach for ${label}?`;
  if (ct === "formula")        return `State the formula for ${label}.`;
  return `What is the key point about ${label}?`;
}

function extractFormula(entries: CanonicalGuideEntry[]): AdaptiveStudySheet["formula"] {
  const formulaEntry = entries.find((e) => e.canonicalType === "formula");
  if (!formulaEntry) return null;
  return {
    expression:  formulaEntry.title ?? formulaEntry.text.slice(0, 60),
    description: formulaEntry.text,
    variables:   null,
    anchorId:    null,
    sourcePage:  null,
  };
}

function buildConnections(
  entries: CanonicalGuideEntry[],
): AdaptiveStudySheet["connections"] {
  // Build cause→effect and process→mechanism links from the unit set.
  const byType = new Map<string, CanonicalGuideEntry[]>();
  for (const e of entries) {
    const ct = e.canonicalType ?? "core-concept";
    const arr = byType.get(ct) ?? [];
    arr.push(e);
    byType.set(ct, arr);
  }

  const pairs: Array<[string, string]> = [
    ["cause", "effect"],
    ["process", "mechanism"],
    ["indication", "contraindication"],
  ];

  const conns: NonNullable<AdaptiveStudySheet["connections"]> = [];
  for (const [fromType, toType] of pairs) {
    const from = byType.get(fromType)?.[0];
    const to   = byType.get(toType)?.[0];
    if (!from || !to) continue;
    conns.push({
      from:       from.title ?? from.text.slice(0, 40),
      to:         to.title   ?? to.text.slice(0, 40),
      connection: `${fromType} → ${toType}`,
    });
  }
  return conns.length > 0 ? conns : null;
}
