// lib/notelab/ultraNoteStore.ts
// localStorage-backed store for Ultra Notes generated from the right panel.
// Primary entry point: buildNoteFromStudyModel — consumes PageBrain directly.

import type { CurrentPageStudyModel } from "@/lib/insights/currentPageStudyModel";

export type NoteSubject = "Biology" | "Calculus" | "Dental / Clinical" | "General Notes";

export interface UltraNoteFolder {
  id: string;
  name: string;
  sourceBookId: string;
  subject: NoteSubject;
  createdAt: number;
}

/** Infer subject from bookId or title keywords */
export function inferSubject(bookId: string): NoteSubject {
  const lower = bookId.toLowerCase();
  if (/bio(logy)?|anatomy|physiology|genetics|cell|organism/.test(lower)) return "Biology";
  if (/calc|math|algebra|geometry|trig|statistic|linear|differential/.test(lower)) return "Calculus";
  if (/dental|dent|medical|med|clinical|nursing|pharma|patho|histology/.test(lower)) return "Dental / Clinical";
  return "General Notes";
}

export interface UltraNoteConcept {
  ordinal: number;
  title: string;
  pattern: string;
  surgicalReason: string;
  trap: string;
  rule: string;
}

/** OpenAI professor-layer study notes — the 6 dedicated teaching sections */
export interface ProfessorNotes {
  whyItMatters?: string;
  keyMechanism?: string;
  commonConfusion?: string;
  memoryAnchor?: string;
  reasoningFlow?: string;
  examSignal?: string;
}

/** One named section in a PageBrain-sourced structured note */
export interface NoteSection {
  label: string;
  content: string;
}

export interface UltraNote {
  id: string;
  bookId: string;
  bookTitle?: string;
  pageNumber: number;
  topic: string;
  coreIdea: string;
  concepts: UltraNoteConcept[];
  memoryShortcuts: string[];
  subject: NoteSubject;
  createdAt: number;
  /** Structured PageBrain sections — present when note was built via buildNoteFromStudyModel */
  sections?: NoteSection[];
  /** OpenAI-generated professor teaching notes — present when synthesis resolved */
  professorNotes?: ProfessorNotes;
  /** OpenAI page thesis — authoritative one-sentence governing idea */
  pageThesis?: string;
  /** OpenAI synthesis mini-test questions for this page */
  miniTest?: string[];
  /** Resolved cross-links from synthesis — kept for backward compat with saved notes */
  crossLinks?: Array<{ label: string; resolvedPage?: number }>;
  /** External study links generated by OpenAI — full with searchQuery for constructing URLs */
  externalStudyLinks?: Array<{ label: string; searchQuery: string; type: string }>;
  /** Related teaching video search queries from OpenAI */
  relatedVideoQueries?: string[];
  /** OpenAI highlight anchors — source spans selected for left-panel highlights */
  highlightAnchors?: Array<{ text: string; anchorType: string; reason: string }>;
}

// ── Storage constants ─────────────────────────────────────────────────────
// New DB name avoids inheriting a broken schema from any old version-1 database.
const IDB_DB_NAME    = "avrrio_notes_v2";
const IDB_STORE_NAME = "notes";
const LS_MIRROR_KEY  = "ultraNotes_mirror_v2";

// ── Compact ───────────────────────────────────────────────────────────────

function compact(note: UltraNote): UltraNote {
  return {
    ...note,
    relatedVideoQueries: undefined,
    highlightAnchors: note.highlightAnchors?.slice(0, 5).map((a) => ({
      text: a.text.slice(0, 50),
      anchorType: a.anchorType,
      reason: a.reason.slice(0, 60),
    })),
    miniTest: note.miniTest?.slice(0, 4),
    externalStudyLinks: note.externalStudyLinks?.slice(0, 3),
    concepts: note.concepts.slice(0, 8).map((c) => ({
      ...c,
      pattern: c.pattern.slice(0, 300),
      surgicalReason: c.surgicalReason.slice(0, 200),
      trap: c.trap.slice(0, 200),
      rule: c.rule.slice(0, 200),
    })),
    sections: note.sections?.slice(0, 8).map((s) => ({
      label: s.label,
      content: s.content.slice(0, 500),
    })),
  };
}

// ── IDB helpers ───────────────────────────────────────────────────────────

function openNoteIDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    if (typeof indexedDB === "undefined") { reject(new Error("IDB unavailable")); return; }
    const req = indexedDB.open(IDB_DB_NAME, 1);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(IDB_STORE_NAME)) {
        db.createObjectStore(IDB_STORE_NAME, { keyPath: "id" });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror   = () => reject(req.error);
    req.onblocked = () => reject(new Error("IDB blocked"));
  });
}

async function idbPutNote(note: UltraNote): Promise<void> {
  const db = await openNoteIDB();
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(IDB_STORE_NAME, "readwrite");
    const req = tx.objectStore(IDB_STORE_NAME).put(note); // keyPath="id" — inline key
    req.onerror   = () => reject(req.error);
    tx.oncomplete = () => resolve();
    tx.onerror    = () => reject(tx.error);
  });
}

async function idbDeleteNote(id: string): Promise<void> {
  const db = await openNoteIDB();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(IDB_STORE_NAME, "readwrite");
    tx.objectStore(IDB_STORE_NAME).delete(id);
    tx.oncomplete = () => resolve();
    tx.onerror    = () => reject(tx.error);
  });
}

async function idbGetAllNotes(): Promise<UltraNote[]> {
  const db = await openNoteIDB();
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(IDB_STORE_NAME, "readonly");
    const req = tx.objectStore(IDB_STORE_NAME).getAll();
    req.onsuccess = () => resolve((req.result as UltraNote[]) ?? []);
    req.onerror   = () => reject(req.error);
  });
}

// ── localStorage mirror (sync read, best-effort write) ───────────────────

function lsRead(): UltraNote[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(LS_MIRROR_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch { return []; }
}

function lsWrite(notes: UltraNote[]): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(LS_MIRROR_KEY, JSON.stringify(notes.slice(0, 100).map(compact)));
  } catch { /* quota — mirror is optional */ }
}

function lsUpsert(note: UltraNote): void {
  const all = lsRead();
  const idx = all.findIndex((n) => n.id === note.id);
  if (idx >= 0) all[idx] = note; else all.unshift(note);
  lsWrite(all);
}

function lsRemove(id: string): void {
  lsWrite(lsRead().filter((n) => n.id !== id));
}

// ── Public API ────────────────────────────────────────────────────────────

/** Async read from IDB (authoritative). Falls back to LS mirror on IDB error. */
export async function getAllUltraNotesAsync(): Promise<UltraNote[]> {
  try {
    const notes = await idbGetAllNotes();
    // Sort newest first
    notes.sort((a, b) => b.createdAt - a.createdAt);
    console.log("[NOTELAB_RENDER_COUNT]", { total: notes.length, driver: "indexeddb" });
    return notes;
  } catch (e) {
    console.warn("[NOTELAB_IDB_READ_FAIL]", String(e), "— falling back to LS mirror");
    return lsRead();
  }
}

/** Sync read from LS mirror — for legacy callers only. */
export function getAllUltraNotes(): UltraNote[] {
  return lsRead();
}

export function getNotesByBook(bookId: string): UltraNote[] {
  return lsRead().filter((n) => n.bookId === bookId);
}

export async function isUltraNotePersisted(id: string): Promise<boolean> {
  try {
    const notes = await idbGetAllNotes();
    return notes.some((n) => n.id === id);
  } catch {
    return lsRead().some((n) => n.id === id);
  }
}

function isValidReaderSource(note: UltraNote): boolean {
  if (!note.bookId || note.bookId.trim().length < 3) return false;
  const lower = note.bookId.toLowerCase().trim();
  if (/^(dev|test|debug|app|demo|sample|mock|fake|placeholder|generic|untitled|default|temp|tmp)$/.test(lower)) return false;
  if (note.pageNumber < 1) return false;
  return true;
}

export async function saveUltraNote(note: UltraNote): Promise<void> {
  if (!isValidReaderSource(note)) {
    console.warn("[NOTELAB_INVALID_SOURCE_BLOCKED]", { bookId: note.bookId, pageNumber: note.pageNumber, topic: note.topic });
    return;
  }

  console.log("[NOTELAB_SOURCE_USED]", { bookId: note.bookId, pageNumber: note.pageNumber, bookTitle: note.bookTitle ?? "(none)" });

  const c = compact(note);

  // Validate schema: must have at minimum a coreIdea or sections
  const hasContent = !!(c.coreIdea || (c.sections && c.sections.length > 0) || c.concepts.length > 0);
  if (!hasContent) {
    console.warn("[NOTELAB_SCHEMA_INVALID]", { id: c.id, reason: "no coreIdea, sections, or concepts" });
    return;
  }
  console.log("[NOTELAB_SCHEMA_VALID]", { id: c.id, sectionCount: c.sections?.length ?? 0, conceptCount: c.concepts.length });

  // Remove stale entry for same book+page with a different id (e.g. from old Date.now() ids)
  try {
    const existing = await idbGetAllNotes();
    const stale = existing.filter(
      (n) => n.bookId === c.bookId && n.pageNumber === c.pageNumber && n.id !== c.id
    );
    for (const n of stale) {
      await idbDeleteNote(n.id);
      lsRemove(n.id);
    }
  } catch { /* non-fatal */ }

  // Primary: IDB — on failure, fall back to the localStorage mirror so the note
  // is not silently lost (consistent with saveRecallSet's IDB-failure fallback).
  try {
    await idbPutNote(c);
    console.log("[NOTE_SAVE_SUCCESS]", { id: c.id, page: c.pageNumber, bookId: c.bookId, driver: "indexeddb" });
  } catch (e) {
    console.error("[NOTELAB_IDB_PUT_FAIL]", { id: c.id, error: String(e) }, "— falling back to localStorage mirror");
  }

  // Mirror: LS — always written so reads via getAllUltraNotes() stay consistent
  // even when IDB failed.
  lsUpsert(c);

  if (typeof window !== "undefined") window.dispatchEvent(new Event("note-lab-updated"));
}

export async function deleteUltraNote(id: string): Promise<void> {
  console.log("[NOTELAB_IDB_DELETE]", { id });
  try {
    await idbDeleteNote(id);
  } catch (e) {
    console.error("[NOTELAB_IDB_DELETE_FAIL]", { id, error: String(e) });
    throw e; // re-throw so UI can show error
  }

  console.log("[NOTELAB_LOCAL_DELETE]", { id });
  lsRemove(id);

  if (typeof window !== "undefined") window.dispatchEvent(new Event("note-lab-updated"));
}

export function buildUltraNote(
  bookId: string,
  pageNumber: number,
  topic: string,
  coreIdea: string,
  concepts: UltraNoteConcept[],
  bookTitle?: string,
  professorNotes?: ProfessorNotes,
  pageThesis?: string,
  miniTest?: string[],
  crossLinks?: Array<{ label: string; resolvedPage?: number }>,
  externalStudyLinks?: Array<{ label: string; searchQuery: string; type: string }>,
  relatedVideoQueries?: string[],
  highlightAnchors?: Array<{ text: string; anchorType: string; reason: string }>,
): UltraNote {
  const memoryShortcuts = concepts
    .filter((c) => c.rule && c.rule.length > 10)
    .map((c) => `${c.title}: ${c.rule}`)
    .slice(0, 3);

  return {
    id: `note-${bookId}-p${pageNumber}-${Date.now()}`,
    bookId,
    bookTitle: bookTitle || undefined,
    pageNumber,
    topic,
    coreIdea,
    concepts,
    memoryShortcuts,
    subject: inferSubject(bookId),
    createdAt: Date.now(),
    professorNotes: professorNotes ?? undefined,
    pageThesis: pageThesis || undefined,
    miniTest: miniTest?.length ? miniTest : undefined,
    crossLinks: crossLinks?.length ? crossLinks : undefined,
    externalStudyLinks: externalStudyLinks?.length ? externalStudyLinks : undefined,
    relatedVideoQueries: relatedVideoQueries?.length ? relatedVideoQueries : undefined,
    highlightAnchors: highlightAnchors?.length ? highlightAnchors : undefined,
  };
}

/**
 * Primary NoteLab entry point — builds a structured note directly from PageBrain.
 * Produces 6 explicit sections matching the cognitive architecture:
 *   1. Page Thesis  2. Key Mechanisms  3. Definitions
 *   4. Confusions & Traps  5. Exam Signals  6. Summary
 *
 * All content comes from the same StudyModel that powers the right panel and
 * left-panel highlights — NoteLab is a different view of the same brain.
 */
export function buildNoteFromStudyModel(
  model: CurrentPageStudyModel,
  opts: { bookId: string; pageNumber: number; topic: string; bookTitle?: string },
): UltraNote {
  const { bookId, pageNumber, topic, bookTitle } = opts;
  const sn = model.studyNotes;
  const sections: NoteSection[] = [];

  // 1. Core Idea — 1-sentence governing idea
  if (model.pageThesis) {
    sections.push({ label: "Core Idea", content: model.pageThesis });
  }

  // 2. Must Know — 3 bullets max (why it matters, key mechanism, first concept principle)
  const mustKnowItems = [
    sn.whyThisMatters,
    sn.keyMechanism,
    model.conceptBlocks[0]?.pattern ?? null,
  ].filter((v): v is string => typeof v === "string" && v.length > 10).slice(0, 3);
  if (mustKnowItems.length) {
    sections.push({ label: "Must Know", content: mustKnowItems.map((b) => `• ${b}`).join("\n") });
  }

  // 3. Mechanism — numbered steps from keyMechanism + concept mechanisms
  const mechanismParts = [
    sn.keyMechanism,
    ...model.conceptBlocks.map((b) => b.mechanism).filter(Boolean),
  ].filter((v): v is string => typeof v === "string" && v.length > 10).slice(0, 5);
  if (mechanismParts.length) {
    sections.push({ label: "Mechanism", content: mechanismParts.map((m, i) => `${i + 1}. ${m}`).join("\n") });
  }

  // 4. DAT/Dental Trap — 1–2 traps
  const trapItems = [
    sn.commonConfusion,
    ...model.conceptBlocks.map((b) => b.trap).filter(Boolean),
  ].filter((v): v is string => typeof v === "string" && v.length > 10).slice(0, 2);
  if (trapItems.length) {
    sections.push({ label: "DAT/Dental Trap", content: trapItems.map((t) => `⚠ ${t}`).join("\n") });
  }

  // 5. Memory Hook — 1 mnemonic
  const memHook = sn.quickMemory
    ?? model.conceptBlocks.find((b) => b.rule && b.rule.length > 10)?.rule
    ?? null;
  if (memHook) {
    sections.push({ label: "Memory Hook", content: memHook });
  }

  // 6. Recall Questions — 3 questions from miniTest
  const recallQs = (model.miniTest ?? [])
    .filter((q): q is string => typeof q === "string" && q.length > 5)
    .slice(0, 3);
  if (recallQs.length) {
    sections.push({ label: "Recall Questions", content: recallQs.map((q, i) => `${i + 1}. ${q}`).join("\n") });
  }

  // 7. Source — book title, page, topic
  const sourceParts = [
    bookTitle ? `Book: ${bookTitle}` : null,
    `Page: ${pageNumber}`,
    topic ? `Topic: ${topic}` : null,
  ].filter(Boolean) as string[];
  sections.push({ label: "Source", content: sourceParts.join(" · ") });

  const concepts: UltraNoteConcept[] = model.conceptBlocks.map((b, i) => ({
    ordinal:        i + 1,
    title:          b.title,
    pattern:        b.pattern,
    surgicalReason: b.mechanism ?? "",
    trap:           b.trap ?? "",
    rule:           b.rule ?? "",
  }));

  const memoryShortcuts = concepts
    .filter((c) => c.rule && c.rule.length > 10)
    .map((c) => `${c.title}: ${c.rule}`)
    .slice(0, 3);

  const professorNotes: ProfessorNotes = {
    whyItMatters:    sn.whyThisMatters  ?? undefined,
    keyMechanism:    sn.keyMechanism    ?? undefined,
    commonConfusion: sn.commonConfusion ?? undefined,
    memoryAnchor:    sn.quickMemory     ?? undefined,
    reasoningFlow:   sn.reasoningFlow   ?? undefined,
    examSignal:      sn.examSignal      ?? undefined,
  };

  console.log("[NOTE_FROM_PAGEBRAIN]", {
    page: pageNumber,
    sectionCount: sections.length,
    sectionLabels: sections.map((s) => s.label),
    conceptCount: concepts.length,
  });

  return {
    id:               `note-${bookId}-p${pageNumber}`,
    bookId,
    bookTitle:        bookTitle || undefined,
    pageNumber,
    topic,
    coreIdea:         model.pageThesis,
    concepts,
    memoryShortcuts,
    sections,
    subject:          inferSubject(bookId),
    createdAt:        Date.now(),
    professorNotes,
    pageThesis:       model.pageThesis,
    miniTest:         model.miniTest?.length           ? model.miniTest           : undefined,
    externalStudyLinks: model.externalStudyLinks?.length ? model.externalStudyLinks : undefined,
    relatedVideoQueries: model.relatedVideoQueries?.length ? model.relatedVideoQueries : undefined,
    highlightAnchors: model.highlightAnchors?.length   ? model.highlightAnchors   : undefined,
  };
}

export function formatUltraNoteText(note: UltraNote): string {
  const lines: string[] = [
    `⚡ STUDY NOTE — ${note.topic} (Page ${note.pageNumber})`,
    ``,
  ];

  // PageBrain structured sections (present on notes built via buildNoteFromStudyModel)
  if (note.sections?.length) {
    const SECTION_ICONS: Record<string, string> = {
      "Page Thesis":       "🎯",
      "Key Mechanisms":    "⚙️",
      "Definitions":       "📖",
      "Confusions & Traps": "⚠️",
      "Exam Signals":      "🎓",
      "Summary":           "📝",
    };
    for (const sec of note.sections) {
      const icon = SECTION_ICONS[sec.label] ?? "•";
      lines.push(`${icon} ${sec.label.toUpperCase()}`);
      lines.push(`  ${sec.content.replace(/\n/g, "\n  ")}`);
      lines.push(``);
    }
  } else {
    // Legacy format — notes saved before PageBrain sections were introduced
    lines.push(`🎯 CORE IDEA`, note.coreIdea, ``);
    if (note.professorNotes) {
      const pn = note.professorNotes;
      if (pn.whyItMatters)    lines.push(`💡 WHY THIS MATTERS\n  ${pn.whyItMatters}`, ``);
      if (pn.keyMechanism)    lines.push(`⚙️ KEY MECHANISM\n  ${pn.keyMechanism}`, ``);
      if (pn.commonConfusion) lines.push(`⚠️ COMMON CONFUSION\n  ${pn.commonConfusion}`, ``);
      if (pn.memoryAnchor)    lines.push(`🧠 MEMORY ANCHOR\n  ${pn.memoryAnchor}`, ``);
      if (pn.reasoningFlow)   lines.push(`🔗 REASONING FLOW\n  ${pn.reasoningFlow}`, ``);
      if (pn.examSignal)      lines.push(`🎓 EXAM SIGNAL\n  ${pn.examSignal}`, ``);
    }
    note.concepts.forEach((c) => {
      lines.push(`🧩 ${c.ordinal}️⃣ ${c.title}`);
      if (c.pattern)        lines.push(`P — Pattern\n  ${c.pattern}`);
      if (c.surgicalReason) lines.push(`⚡ Surgical Reason\n  ${c.surgicalReason}`);
      if (c.trap)           lines.push(`❗ Trap\n  ${c.trap}`);
      if (c.rule)           lines.push(`🔥 Rule\n  ${c.rule}`);
      lines.push(``);
    });
  }

  // Memory shortcuts — derived from concept rules, shown in both formats
  if (note.memoryShortcuts?.length) {
    lines.push(`🧠 MEMORY SHORTCUTS`);
    note.memoryShortcuts.forEach((s) => lines.push(`  👉 ${s}`));
    lines.push(``);
  }

  if (note.miniTest?.length) {
    lines.push(`📝 MINI TEST`);
    note.miniTest.forEach((q, i) => lines.push(`${i + 1}. ${q}`));
    lines.push(``);
  }

  if (note.externalStudyLinks?.length) {
    lines.push(`📚 EXTERNAL STUDY LINKS`);
    note.externalStudyLinks.forEach((l) => lines.push(`↗ ${l.label} (${l.searchQuery})`));
    lines.push(``);
  } else if (note.crossLinks?.length) {
    lines.push(`🔗 CROSS-LINKS`);
    note.crossLinks.forEach((cl) => lines.push(`↗ ${cl.label}${cl.resolvedPage ? ` · p.${cl.resolvedPage}` : ""}`));
    lines.push(``);
  }

  if (note.relatedVideoQueries?.length) {
    lines.push(`📺 RELATED TEACHING VIDEOS`);
    note.relatedVideoQueries.forEach((q) => lines.push(`▶ ${q}`));
    lines.push(``);
  }

  return lines.join("\n");
}
