// lib/notelab/ultraNoteStore.ts
// localStorage-backed store for Ultra Notes generated from the right panel.
// Primary entry point: buildNoteFromStudyModel — consumes PageBrain directly.

import type { CurrentPageStudyModel, VisualAnchor } from "@/lib/insights/currentPageStudyModel";
import type { NoteCard } from "@/lib/insights/synthesizeTeachingOutput";
import type { DATStudySheet } from "@/lib/notelab/datStudySheet";
import type { AdaptiveStudySheet } from "@/lib/notelab/adaptiveStudySheet";
import { inferNoteSubject, type NoteSubject } from "@/lib/canonical/classifier";
import type { VisualNotebookScene } from "@/lib/notelab/notebookScene";
import { currentFirebaseUid, listNotebookSemanticStates, saveNotebookSemanticState, deleteNotebookSemanticState } from "@/lib/firebase/durableState";

// Re-export NoteSubject so callers that import it from here don't need to change.
export type { NoteSubject };

export interface UltraNoteFolder {
  id: string;
  name: string;
  sourceBookId: string;
  subject: NoteSubject;
  createdAt: number;
}

/** Infer NoteSubject from bookId — delegates to the canonical classifier. */
export function inferSubject(bookId: string, bookTitle?: string): NoteSubject {
  return inferNoteSubject(bookId, bookTitle);
}

export interface UltraNoteConcept {
  ordinal: number;
  title: string;
  pattern: string;
  surgicalReason: string;
  trap: string;
  rule: string;
}

/** OpenAI professor-layer study notes — the 6 dedicated teaching sections */
export interface ProfessorNotes {
  whyItMatters?: string;
  keyMechanism?: string;
  commonConfusion?: string;
  memoryAnchor?: string;
  reasoningFlow?: string;
  examSignal?: string;
}

/** One named section in a PageBrain-sourced structured note */
export interface NoteSection {
  label: string;
  content: string;
}

export interface UltraNote {
  id: string;
  bookId: string;
  bookTitle?: string;
  pageNumber: number;
  topic: string;
  coreIdea: string;
  concepts: UltraNoteConcept[];
  memoryShortcuts: string[];
  subject: NoteSubject;
  createdAt: number;
  /** Structured PageBrain sections — present when note was built via buildNoteFromStudyModel */
  sections?: NoteSection[];
  /** OpenAI-generated professor teaching notes — present when synthesis resolved */
  professorNotes?: ProfessorNotes;
  /** OpenAI page thesis — authoritative one-sentence governing idea */
  pageThesis?: string;
  /** OpenAI synthesis mini-test questions for this page */
  miniTest?: string[];
  /** Resolved cross-links from synthesis — kept for backward compat with saved notes */
  crossLinks?: Array<{ label: string; resolvedPage?: number }>;
  /** External study links generated by OpenAI — full with searchQuery for constructing URLs */
  externalStudyLinks?: Array<{ label: string; searchQuery: string; type: string }>;
  /** Related teaching video search queries from OpenAI */
  relatedVideoQueries?: string[];
  /** OpenAI highlight anchors — source spans selected for left-panel highlights */
  highlightAnchors?: Array<{ text: string; anchorType: string; reason: string }>;
  /** Ordinals of concepts the reader has starred/bookmarked within this note */
  starredConcepts?: number[];
  /** Adaptive Notebook cards — AI-curated (or derived) variable card set for this page */
  noteCards?: NoteCard[];
  /** Raw LeftPanel thought units this note was built from — lets NoteLab's own
   *  left nav (ThoughtUnitNavigator) bind to a saved note instead of only its
   *  lossy highlightAnchors summary. */
  visualAnchors?: VisualAnchor[];
  /** Free-form topic tags, surfaced as a badge row and included in exports. */
  tags?: string[];
  /** DAT Study Sheet — kept for backward compat with previously generated sheets. */
  datStudySheet?: DATStudySheet;
  /** Adaptive Study Sheet — profile-driven replacement for datStudySheet. */
  adaptiveStudySheet?: AdaptiveStudySheet;
  // ── Knowledge Graph references (KG PR 1) ──────────────────────────────────
  // Optional — notes created before KG PR 1 will not have these fields.
  // Never renamed or removed; back-filled incrementally via resolveOrCreateNode.
  knowledgeNodeId?:    string;
  canonicalAnchorId?:  string;
  chapterCandidateId?: string;
  // ── Document/page identity (C2 — Phase 0 audit) ───────────────────────────
  // Optional, same reasoning as the KG fields above: notes saved before this
  // fix will not have these, and that's fine — they simply can't be linked
  // by resolved identity yet. Back-filled the same way knowledgeNodeId/
  // canonicalAnchorId are: set right before saveUltraNote() at each call
  // site, never inferred from bookId (a filename), which is a DIFFERENT
  // identity space — see lib/insights/resolveDocumentIdentity.ts.
  /** Resolved, collision-resistant document identity. */
  documentId?: string;
  /** `${documentId}::${pageNumber}::${textReady}` — lib/useActivePageIntelligence.ts's buildPageTruthKey convention. */
  pageTruthKey?: string;
  /** CanonicalThoughtUnit ids this note is actually grounded in. */
  thoughtUnitIds?: string[];
  /** Student-authored layer. AI regeneration never overwrites this field. */
  studentNotes?: string;
  /** Optional printed-page label when it differs from the electronic PDF page. */
  printedPageLabel?: string;
  // ── N3 — adaptive tldraw notebook ─────────────────────────────────────────
  /** NotebookPlanner's composed scene for this page (see
   *  lib/notelab/notebookScene.ts) — the input NotebookCanvas.tsx renders
   *  onto a real, persistent, student-editable tldraw canvas. Optional and
   *  additive: notes saved before N3 (or any page the planner hasn't run
   *  for yet) simply have none, and UltraNotesList only offers the
   *  notebook-view toggle when this is present. Never generated in this
   *  phase — that's a later increment; N3 is the renderer. */
  notebookScene?: VisualNotebookScene;
  /** Correction (NoteLab pipeline diagnostics) — "show an explicit
   *  recoverable error and diagnostics rather than reverting to the old
   *  card view." Set by composeNoteNotebookSceneInBackground's own catch
   *  block (RightPanel.tsx) when live notebookScene synthesis throws;
   *  cleared (undefined) the next time synthesis succeeds. A page with
   *  zero canonical units to ground a synthesis in is NOT an error (no
   *  deterministic fallback is invented for that case, per the
   *  correction's own instruction) — only a genuine thrown failure sets
   *  this. */
  notebookSceneError?: string;
  /** L13 (NoteLab visual-execution correction) — "'Nothing composed here
   *  yet' should almost never appear after the user has already saved
   *  material from Reader... either render the visual note or explicitly
   *  say generation failed and give Retry." Before this field, a note whose
   *  background composition hadn't finished yet, one whose composition
   *  genuinely had nothing to compose (a legitimately sparse page), and one
   *  whose composition threw an error all rendered the SAME silent "Nothing
   *  composed here yet" empty state as a note nobody had touched — this
   *  field lets UltraNotesList tell those apart:
   *   - "pending": set the moment the primary save fires, before the
   *     background compose has resolved — the notebook is actively being
   *     built, not empty.
   *   - "ready": composition produced a real notebookScene (blocks.length > 0).
   *   - "empty": composition genuinely found nothing to compose (no
   *     canonical units AND no deterministic content) — a real, non-error
   *     outcome; the "Nothing composed here yet" copy stays accurate here.
   *   - "failed": composition threw (see notebookSceneError) — shown with
   *     an explicit failure banner and a Retry action, never silently.
   *  Optional/undefined for any note saved before this field existed — those
   *  fall back to the pre-existing "empty" treatment, unchanged. */
  notebookSceneStatus?: "pending" | "ready" | "empty" | "failed";
}

// ── Legacy note migration ─────────────────────────────────────────────────

/** Labels from the retired dashboard/card implementations are translated at
 * the NoteLab boundary. The original persisted fields remain on UltraNote so
 * migration is non-destructive and older exports/integrations can still read
 * them; the learner-facing notebook never renders those old layouts. */
const CANONICAL_SECTION_LABELS: Record<string, string | null> = {
  "Chief Concern / Problem": "Big Idea",
  "Chief Concern / Core Problem": "Big Idea",
  "Core Idea": "Big Idea",
  "Page Thesis": "Big Idea",
  "Why This Matters": "Clinical / Application Connection",
  "Why This Matters Clinically": "Clinical / Application Connection",
  "Diagnostic Reasoning": "Clinical Reasoning",
  "Procedure Logic": "Mechanism / Process",
  "Key Mechanism": "Mechanism / Process",
  "Mechanism": "Mechanism / Process",
  "Decision Tree": "Decision / Concept Map",
  "Connection Map": "Decision / Concept Map",
  "Danger Zone": "Common Mistakes / Clinical Risks",
  "Complication Risk": "Common Mistakes / Clinical Risks",
  "Common Mistake": "Common Mistakes / Clinical Risks",
  "Common Mistakes": "Common Mistakes / Clinical Risks",
  "Confusions & Traps": "Common Mistakes / Clinical Risks",
  "DAT/Dental Trap": "Common Mistakes / Clinical Risks",
  "Clinical Pearl": "Key Facts / Clinical Pearls",
  "Must Know": "Key Facts / Clinical Pearls",
  "Exam Strategy": "Exam-Important Concepts",
  "Exam Signal": "Exam-Important Concepts",
  "Memory Hook": "Memory Trick",
  "Case-Style Recall Questions": "Recall Questions",
  "Summary": "Structured Notes",
  // Provenance is rendered by the expandable evidence inspector, never as a
  // competing notebook section.
  "Source": null,
  "Source Evidence": null,
};

function pushCanonicalSection(target: Map<string, string[]>, label: string, content?: string | null): void {
  const clean = content?.trim();
  if (!clean) return;
  const canonicalLabel = Object.prototype.hasOwnProperty.call(CANONICAL_SECTION_LABELS, label)
    ? CANONICAL_SECTION_LABELS[label]
    : label;
  if (!canonicalLabel) return;
  const values = target.get(canonicalLabel) ?? [];
  if (!values.includes(clean)) values.push(clean);
  target.set(canonicalLabel, values);
}

/** Convert every historical UltraNote shape into the one canonical notebook
 * page model. This never invents facts and never deletes the legacy fields;
 * it only reorganizes content the student already saved. */
export function getCanonicalNotebookSections(note: UltraNote): NoteSection[] {
  const grouped = new Map<string, string[]>();

  for (const section of note.sections ?? []) {
    pushCanonicalSection(grouped, section.label, section.content);
  }

  if (!grouped.has("Big Idea")) {
    pushCanonicalSection(grouped, "Big Idea", note.pageThesis || note.coreIdea);
  }

  const professor = note.professorNotes;
  if (professor) {
    pushCanonicalSection(grouped, "Clinical / Application Connection", professor.whyItMatters);
    pushCanonicalSection(grouped, "Mechanism / Process", professor.keyMechanism);
    pushCanonicalSection(grouped, "Common Mistakes / Clinical Risks", professor.commonConfusion);
    pushCanonicalSection(grouped, "Memory Trick", professor.memoryAnchor);
    pushCanonicalSection(grouped, "Clinical Reasoning", professor.reasoningFlow);
    pushCanonicalSection(grouped, "Exam-Important Concepts", professor.examSignal);
  }

  if (note.concepts.length) {
    const facts = note.concepts.map((concept) => {
      const parts = [concept.title, concept.pattern].filter(Boolean);
      return parts.join(": ");
    }).filter(Boolean);
    pushCanonicalSection(grouped, "Key Facts / Clinical Pearls", facts.join("\n"));

    const mechanisms = note.concepts
      .filter((concept) => concept.surgicalReason)
      .map((concept) => `${concept.title}: ${concept.surgicalReason}`);
    pushCanonicalSection(grouped, "Mechanism / Process", mechanisms.join("\n"));

    const risks = note.concepts
      .filter((concept) => concept.trap)
      .map((concept) => `${concept.title}: ${concept.trap}`);
    pushCanonicalSection(grouped, "Common Mistakes / Clinical Risks", risks.join("\n"));

    const rules = note.concepts
      .filter((concept) => concept.rule)
      .map((concept) => `${concept.title}: ${concept.rule}`);
    pushCanonicalSection(grouped, "Exam-Important Concepts", rules.join("\n"));
  }

  pushCanonicalSection(grouped, "Memory Trick", note.memoryShortcuts.join("\n"));
  pushCanonicalSection(grouped, "Recall Questions", note.miniTest?.map((q, index) => `${index + 1}. ${q}`).join("\n"));

  const preferredOrder = [
    "Big Idea",
    "Structured Notes",
    "Key Facts / Clinical Pearls",
    "Definitions",
    "Mechanism / Process",
    "Clinical Reasoning",
    "Decision / Concept Map",
    "Clinical / Application Connection",
    "Common Mistakes / Clinical Risks",
    "Memory Trick",
    "Exam-Important Concepts",
    "Recall Questions",
  ];

  return [...grouped.entries()]
    .map(([label, values]) => ({ label, content: values.join("\n\n") }))
    .sort((a, b) => {
      const ai = preferredOrder.indexOf(a.label);
      const bi = preferredOrder.indexOf(b.label);
      return (ai === -1 ? preferredOrder.length : ai) - (bi === -1 ? preferredOrder.length : bi);
    });
}

// ── Storage constants ─────────────────────────────────────────────────────
// New DB name avoids inheriting a broken schema from any old version-1 database.
const IDB_DB_NAME    = "avrrio_notes_v2";
const IDB_STORE_NAME = "notes";
const LS_MIRROR_KEY  = "ultraNotes_mirror_v2";

// ── Compact ───────────────────────────────────────────────────────────────

function compact(note: UltraNote): UltraNote {
  return {
    ...note,
    relatedVideoQueries: undefined,
    highlightAnchors: note.highlightAnchors?.slice(0, 5).map((a) => ({
      text: a.text.slice(0, 50),
      anchorType: a.anchorType,
      reason: a.reason.slice(0, 60),
    })),
    miniTest: note.miniTest?.slice(0, 4),
    externalStudyLinks: note.externalStudyLinks?.slice(0, 3),
    concepts: note.concepts.slice(0, 8).map((c) => ({
      ...c,
      pattern: c.pattern.slice(0, 300),
      surgicalReason: c.surgicalReason.slice(0, 200),
      trap: c.trap.slice(0, 200),
      rule: c.rule.slice(0, 200),
    })),
    // Cap generous enough to cover every section buildNoteFromStudyModel can produce
    // (Core Idea/Must Know/Mechanism/Trap/Memory Hook/Recall Questions/5 Level-2
    // fields/Summary/Source = 13) — an 8-cap was silently dropping Summary and
    // Source since they're always pushed last.
    sections: note.sections?.slice(0, 16).map((s) => ({
      label: s.label,
      content: s.content.slice(0, 500),
    })),
    starredConcepts: note.starredConcepts?.slice(0, 8),
    noteCards: note.noteCards?.slice(0, 8).map((c) => ({
      ...c,
      body: c.body.slice(0, 600),
      sourceAnchorHints: c.sourceAnchorHints?.slice(0, 5) ?? null,
      visual: c.visual ? {
        ...c.visual,
        nodes: c.visual.nodes.slice(0, 12),
        arrows: c.visual.arrows.slice(0, 16),
      } : null,
    })),
    visualAnchors: note.visualAnchors?.slice(0, 12).map((a) => ({
      ...a,
      exactText: a.exactText.slice(0, 200),
      reason: a.reason.slice(0, 100),
    })),
    tags: note.tags?.slice(0, 8),
    studentNotes: note.studentNotes?.slice(0, 4000),
    // Strip both sheet types from LS mirror — they can be several KB; IDB holds the full copy.
    datStudySheet:     undefined,
    adaptiveStudySheet: undefined,
    // Same reasoning — a notebook scene's blocks can also run several KB; IDB holds the full copy.
    notebookScene: undefined,
  };
}

// ── IDB helpers ───────────────────────────────────────────────────────────

function openNoteIDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    if (typeof indexedDB === "undefined") { reject(new Error("IDB unavailable")); return; }
    const req = indexedDB.open(IDB_DB_NAME, 1);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(IDB_STORE_NAME)) {
        db.createObjectStore(IDB_STORE_NAME, { keyPath: "id" });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror   = () => reject(req.error);
    req.onblocked = () => reject(new Error("IDB blocked"));
  });
}

async function idbPutNote(note: UltraNote): Promise<void> {
  const db = await openNoteIDB();
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(IDB_STORE_NAME, "readwrite");
    const req = tx.objectStore(IDB_STORE_NAME).put(note); // keyPath="id" — inline key
    req.onerror   = () => reject(req.error);
    tx.oncomplete = () => resolve();
    tx.onerror    = () => reject(tx.error);
  });
}

async function idbDeleteNote(id: string): Promise<void> {
  const db = await openNoteIDB();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(IDB_STORE_NAME, "readwrite");
    tx.objectStore(IDB_STORE_NAME).delete(id);
    tx.oncomplete = () => resolve();
    tx.onerror    = () => reject(tx.error);
  });
}

async function idbGetAllNotes(): Promise<UltraNote[]> {
  const db = await openNoteIDB();
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(IDB_STORE_NAME, "readonly");
    const req = tx.objectStore(IDB_STORE_NAME).getAll();
    req.onsuccess = () => resolve((req.result as UltraNote[]) ?? []);
    req.onerror   = () => reject(req.error);
  });
}

// ── localStorage mirror (sync read, best-effort write) ───────────────────

function lsRead(): UltraNote[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(LS_MIRROR_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch { return []; }
}

function lsWrite(notes: UltraNote[]): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(LS_MIRROR_KEY, JSON.stringify(notes.slice(0, 100).map(compact)));
  } catch { /* quota — mirror is optional */ }
}

function lsUpsert(note: UltraNote): void {
  const all = lsRead();
  const idx = all.findIndex((n) => n.id === note.id);
  if (idx >= 0) all[idx] = note; else all.unshift(note);
  lsWrite(all);
}

function lsRemove(id: string): void {
  lsWrite(lsRead().filter((n) => n.id !== id));
}

// ── Public API ────────────────────────────────────────────────────────────

/** Async read from IDB (authoritative). Falls back to LS mirror on IDB error. */
export async function getAllUltraNotesAsync(): Promise<UltraNote[]> {
  let localNotes: UltraNote[];
  try {
    localNotes = await idbGetAllNotes();
  } catch (e) {
    console.warn("[NOTELAB_IDB_READ_FAIL]", String(e), "— falling back to LS mirror");
    localNotes = lsRead();
  }
  if (currentFirebaseUid()) {
    const cloudNotes = await listNotebookSemanticStates<UltraNote>();
    const merged = new Map(localNotes.map((note) => [note.id, note]));
    for (const note of cloudNotes) merged.set(note.id, note);
    localNotes = [...merged.values()];
    for (const note of cloudNotes) await idbPutNote(note).catch(() => {});
    for (const note of cloudNotes) lsUpsert(compact(note));
  }
  localNotes.sort((a, b) => b.createdAt - a.createdAt);
  console.log("[NOTELAB_RENDER_COUNT]", { total: localNotes.length, driver: currentFirebaseUid() ? "firebase+indexeddb" : "indexeddb" });
  return localNotes;
}

/** Sync read from LS mirror — for legacy callers only. */
export function getAllUltraNotes(): UltraNote[] {
  return lsRead();
}

export function getNotesByBook(bookId: string): UltraNote[] {
  return lsRead().filter((n) => n.bookId === bookId);
}

/** Async version that reads from IDB (authoritative), falling back to the LS
 *  mirror when IDB is unavailable or throws.  Use this in any code-path where
 *  correctness matters (exam generation); the sync version is fine for
 *  display-only note counts that run inside useMemo. */
export async function getNotesByBookAsync(bookId: string): Promise<UltraNote[]> {
  try {
    const notes = await idbGetAllNotes();
    return notes.filter((n) => n.bookId === bookId);
  } catch (e) {
    console.warn("[NOTELAB] getNotesByBookAsync IDB read failed, using LS mirror:", String(e));
    return lsRead().filter((n) => n.bookId === bookId);
  }
}

export async function isUltraNotePersisted(id: string): Promise<boolean> {
  try {
    const notes = await idbGetAllNotes();
    return notes.some((n) => n.id === id);
  } catch {
    return lsRead().some((n) => n.id === id);
  }
}

function isValidReaderSource(note: UltraNote): boolean {
  if (!note.bookId || note.bookId.trim().length < 3) return false;
  const lower = note.bookId.toLowerCase().trim();
  if (/^(dev|test|debug|app|demo|sample|mock|fake|placeholder|generic|untitled|default|temp|tmp)$/.test(lower)) return false;
  if (note.pageNumber < 1) return false;
  return true;
}

export async function saveUltraNote(note: UltraNote): Promise<void> {
  if (!isValidReaderSource(note)) {
    console.warn("[NOTELAB_INVALID_SOURCE_BLOCKED]", { bookId: note.bookId, pageNumber: note.pageNumber, topic: note.topic });
    return;
  }

  console.log("[NOTELAB_SOURCE_USED]", { bookId: note.bookId, pageNumber: note.pageNumber, bookTitle: note.bookTitle ?? "(none)" });

  // AI-generated page notes reuse a stable id. Preserve the student's own
  // layer when a generator sends a replacement object without that field.
  // An explicit `studentNotes` property (including undefined) still allows
  // the notebook editor to update or clear the field intentionally.
  let noteToSave = note;
  if (!Object.prototype.hasOwnProperty.call(note, "studentNotes")) {
    try {
      const existing = (await idbGetAllNotes()).find((candidate) =>
        candidate.id === note.id
        || (candidate.bookId === note.bookId && candidate.pageNumber === note.pageNumber)
      );
      if (existing?.studentNotes) noteToSave = { ...note, studentNotes: existing.studentNotes };
    } catch {
      const existing = lsRead().find((candidate) =>
        candidate.id === note.id
        || (candidate.bookId === note.bookId && candidate.pageNumber === note.pageNumber)
      );
      if (existing?.studentNotes) noteToSave = { ...note, studentNotes: existing.studentNotes };
    }
  }

  const c = compact(noteToSave);

  // Validate schema: must have at minimum a coreIdea or sections
  const hasContent = !!(c.coreIdea || (c.sections && c.sections.length > 0) || c.concepts.length > 0);
  if (!hasContent) {
    console.warn("[NOTELAB_SCHEMA_INVALID]", { id: c.id, reason: "no coreIdea, sections, or concepts" });
    return;
  }
  console.log("[NOTELAB_SCHEMA_VALID]", { id: c.id, sectionCount: c.sections?.length ?? 0, conceptCount: c.concepts.length });

  // Remove stale entry for same book+page with a different id (e.g. from old Date.now() ids)
  try {
    const existing = await idbGetAllNotes();
    const stale = existing.filter(
      (n) => n.bookId === c.bookId && n.pageNumber === c.pageNumber && n.id !== c.id
    );
    for (const n of stale) {
      await idbDeleteNote(n.id);
      lsRemove(n.id);
    }
  } catch { /* non-fatal */ }

  // Primary: IDB — full (uncompacted) note so large fields like adaptiveStudySheet
  // and datStudySheet survive. On failure, fall back to the localStorage mirror.
  try {
    await idbPutNote(noteToSave);
    console.log("[NOTE_SAVE_SUCCESS]", { id: noteToSave.id, page: noteToSave.pageNumber, bookId: noteToSave.bookId, driver: "indexeddb" });
  } catch (e) {
    console.error("[NOTELAB_IDB_PUT_FAIL]", { id: c.id, error: String(e) }, "— falling back to localStorage mirror");
  }

  // Mirror: LS — always written so reads via getAllUltraNotes() stay consistent
  // even when IDB failed.
  lsUpsert(c);

  // IDB is the offline/runtime cache. For a signed-in user, the same
  // canonical note and provenance are durably stored under their UID.
  if (currentFirebaseUid() && noteToSave.documentId && noteToSave.pageTruthKey) {
    await saveNotebookSemanticState({
      notebookId: noteToSave.id,
      documentId: noteToSave.documentId,
      pageId: noteToSave.pageTruthKey,
      pageTruthKey: noteToSave.pageTruthKey,
      semanticObjects: noteToSave,
      sourceAnchors: noteToSave.visualAnchors ?? noteToSave.highlightAnchors ?? [],
      canonicalUnitIds: noteToSave.thoughtUnitIds ?? [],
    });
  }

  if (typeof window !== "undefined") window.dispatchEvent(new Event("note-lab-updated"));
}

export async function deleteUltraNote(id: string): Promise<void> {
  // Cloud delete goes first: getAllUltraNotesAsync() merges every Firestore
  // notebook doc back into IDB/LS on each read for a signed-in user, so if
  // the local copies were removed first but the cloud delete then failed,
  // the "deleted" note would resurrect on the very next load.
  if (currentFirebaseUid()) {
    console.log("[NOTELAB_CLOUD_DELETE]", { id });
    try {
      await deleteNotebookSemanticState(id);
    } catch (e) {
      console.error("[NOTELAB_CLOUD_DELETE_FAIL]", { id, error: String(e) });
      throw e; // re-throw so UI can show error and keep the note visible
    }
  }

  console.log("[NOTELAB_IDB_DELETE]", { id });
  try {
    await idbDeleteNote(id);
  } catch (e) {
    console.error("[NOTELAB_IDB_DELETE_FAIL]", { id, error: String(e) });
    throw e; // re-throw so UI can show error
  }

  console.log("[NOTELAB_LOCAL_DELETE]", { id });
  lsRemove(id);

  if (typeof window !== "undefined") window.dispatchEvent(new Event("note-lab-updated"));
}

export function buildUltraNote(
  bookId: string,
  pageNumber: number,
  topic: string,
  coreIdea: string,
  concepts: UltraNoteConcept[],
  bookTitle?: string,
  professorNotes?: ProfessorNotes,
  pageThesis?: string,
  miniTest?: string[],
  crossLinks?: Array<{ label: string; resolvedPage?: number }>,
  externalStudyLinks?: Array<{ label: string; searchQuery: string; type: string }>,
  relatedVideoQueries?: string[],
  highlightAnchors?: Array<{ text: string; anchorType: string; reason: string }>,
): UltraNote {
  const memoryShortcuts = concepts
    .filter((c) => c.rule && c.rule.length > 10)
    .map((c) => `${c.title}: ${c.rule}`)
    .slice(0, 3);

  return {
    id: `note-${bookId}-p${pageNumber}-${Date.now()}`,
    bookId,
    bookTitle: bookTitle || undefined,
    pageNumber,
    topic,
    coreIdea,
    concepts,
    memoryShortcuts,
    subject: inferSubject(bookId),
    createdAt: Date.now(),
    professorNotes: professorNotes ?? undefined,
    pageThesis: pageThesis || undefined,
    miniTest: miniTest?.length ? miniTest : undefined,
    crossLinks: crossLinks?.length ? crossLinks : undefined,
    externalStudyLinks: externalStudyLinks?.length ? externalStudyLinks : undefined,
    relatedVideoQueries: relatedVideoQueries?.length ? relatedVideoQueries : undefined,
    highlightAnchors: highlightAnchors?.length ? highlightAnchors : undefined,
  };
}

/**
 * Primary NoteLab entry point — builds a structured note directly from PageBrain.
 *
 * N1 (NoteLab adaptivity correction) — this used to force EVERY page through
 * the same fixed 14-slot template (Chief Concern, Why This Matters Clinically,
 * Diagnostic Reasoning, Procedure Logic, Decision Tree, Danger Zone,
 * Complication Risk, Clinical Pearl, Common Mistake, Case-Style Recall
 * Questions, Connection Map, Exam Strategy, Memory Hook, Summary), each slot
 * either filled from a studyNotes.* field or simply omitted — never actually
 * varying WHICH kinds of content a page gets beyond that fixed skeleton. That
 * recreates the same "predefined card the knowledge must fit inside" problem
 * the Adaptive Notebook cards (model.noteCards) were built to solve.
 *
 * `sections` is now derived directly from model.noteCards — already the
 * genuinely adaptive path: AI-chosen when synthesis resolves it (2-5 cards,
 * whichever card TYPES the page actually calls for, from a 24-type schema),
 * or deterministically derived per populated field when it doesn't
 * (deriveNoteCardsFromStudyModel — see that file's own header comment: pure,
 * conditional-per-field, never manufactures filler for an empty field). A
 * sparse page legitimately gets fewer sections; a dense one gets more —
 * never a fixed count with generic content padded into whatever's left.
 *
 * All content comes from the same StudyModel that powers the right panel and
 * left-panel highlights — NoteLab is a different view of the same brain.
 */
export function buildNoteFromStudyModel(
  model: CurrentPageStudyModel,
  opts: {
    bookId: string; pageNumber: number; topic: string; bookTitle?: string;
    /** P0 stabilization, Tier 4 — when a caller has a page-specific thesis
     *  from a DIFFERENT, more authoritative pipeline than `model`'s own
     *  (e.g. WhiteboardPanel's Surgeon-sourced pageTitle, already what the
     *  panel displays), this replaces `model.pageThesis` in the note's
     *  content sections below — never both showing on the same page. Every
     *  other caller (Reader's own "Save to NoteLab", which already reads
     *  and displays THIS SAME model, no competing pipeline in play) omits
     *  it and gets the exact prior behavior. */
    pageThesisOverride?: string;
  },
): UltraNote {
  const { bookId, pageNumber, topic, bookTitle, pageThesisOverride } = opts;
  const effectiveThesis = pageThesisOverride || model.pageThesis;
  const sn = model.studyNotes;

  // N1 — a second, content-profile-gated fixed template ("Big Idea", "Core
  // Concepts", "Equations and Variables", "Worked Example", ... for
  // contentProfile.id === "math-textbook") used to live here as an early
  // return, alongside the generic 14-slot template below. Same anti-pattern,
  // just gated behind a detector instead of applying to every page — still a
  // predefined set of labeled slots content gets forced into. Content-
  // profile-aware adaptation belongs in the NotebookPlanner's primitive
  // selection (a genuinely adaptive per-page decision), not a second
  // hand-authored template competing with the first. Removed; the single
  // noteCards-derived path below already adapts per page without a profile
  // detector, since noteCards themselves already vary by what the page
  // (math, clinical, historical, or anything else) actually contains.
  const sections: NoteSection[] = (model.noteCards ?? []).map((c) => ({ label: c.title, content: c.body }));

  // Source — book title, page, topic. Always present: this is provenance,
  // never content forced to fit a slot the page doesn't call for.
  const sourceParts = [
    bookTitle ? `Book: ${bookTitle}` : null,
    `Page: ${pageNumber}`,
    topic ? `Topic: ${topic}` : null,
  ].filter(Boolean) as string[];
  sections.push({ label: "Source", content: sourceParts.join(" · ") });

  const concepts: UltraNoteConcept[] = model.conceptBlocks.map((b, i) => ({
    ordinal:        i + 1,
    title:          b.title,
    pattern:        b.pattern,
    surgicalReason: b.mechanism ?? "",
    trap:           b.trap ?? "",
    rule:           b.rule ?? "",
  }));

  const memoryShortcuts = concepts
    .filter((c) => c.rule && c.rule.length > 10)
    .map((c) => `${c.title}: ${c.rule}`)
    .slice(0, 3);

  const professorNotes: ProfessorNotes = {
    whyItMatters:    sn.whyThisMatters  ?? undefined,
    keyMechanism:    sn.keyMechanism    ?? undefined,
    commonConfusion: sn.commonConfusion ?? undefined,
    memoryAnchor:    sn.quickMemory     ?? undefined,
    reasoningFlow:   sn.reasoningFlow   ?? undefined,
    examSignal:      sn.examSignal      ?? undefined,
  };

  console.log("[NOTE_FROM_PAGEBRAIN]", {
    page: pageNumber,
    sectionCount: sections.length,
    sectionLabels: sections.map((s) => s.label),
    conceptCount: concepts.length,
  });

  return {
    id:               `note-${bookId}-p${pageNumber}`,
    bookId,
    bookTitle:        bookTitle || undefined,
    pageNumber,
    topic,
    coreIdea:         effectiveThesis,
    concepts,
    memoryShortcuts,
    sections,
    subject:          inferSubject(bookId),
    createdAt:        Date.now(),
    professorNotes,
    pageThesis:       effectiveThesis,
    miniTest:         model.miniTest?.length           ? model.miniTest           : undefined,
    externalStudyLinks: model.externalStudyLinks?.length ? model.externalStudyLinks : undefined,
    relatedVideoQueries: model.relatedVideoQueries?.length ? model.relatedVideoQueries : undefined,
    highlightAnchors: model.highlightAnchors?.length   ? model.highlightAnchors   : undefined,
    noteCards:        model.noteCards?.length          ? model.noteCards          : undefined,
    visualAnchors:    model.visualAnchors?.length      ? model.visualAnchors      : undefined,
  };
}

export function formatUltraNoteText(note: UltraNote): string {
  const lines: string[] = [
    `⚡ STUDY NOTE — ${note.topic} (Page ${note.pageNumber})`,
    ``,
  ];

  // PageBrain structured sections (present on notes built via buildNoteFromStudyModel)
  if (note.sections?.length) {
    const SECTION_ICONS: Record<string, string> = {
      "Page Thesis":       "🎯",
      "Key Mechanisms":    "⚙️",
      "Definitions":       "📖",
      "Confusions & Traps": "⚠️",
      "Exam Signals":      "🎓",
      "Summary":           "📝",
    };
    for (const sec of note.sections) {
      const icon = SECTION_ICONS[sec.label] ?? "•";
      lines.push(`${icon} ${sec.label.toUpperCase()}`);
      lines.push(`  ${sec.content.replace(/\n/g, "\n  ")}`);
      lines.push(``);
    }
  } else {
    // Legacy format — notes saved before PageBrain sections were introduced
    lines.push(`🎯 CORE IDEA`, note.coreIdea, ``);
    if (note.professorNotes) {
      const pn = note.professorNotes;
      if (pn.whyItMatters)    lines.push(`💡 WHY THIS MATTERS\n  ${pn.whyItMatters}`, ``);
      if (pn.keyMechanism)    lines.push(`⚙️ KEY MECHANISM\n  ${pn.keyMechanism}`, ``);
      if (pn.commonConfusion) lines.push(`⚠️ COMMON CONFUSION\n  ${pn.commonConfusion}`, ``);
      if (pn.memoryAnchor)    lines.push(`🧠 MEMORY ANCHOR\n  ${pn.memoryAnchor}`, ``);
      if (pn.reasoningFlow)   lines.push(`🔗 REASONING FLOW\n  ${pn.reasoningFlow}`, ``);
      if (pn.examSignal)      lines.push(`🎓 EXAM SIGNAL\n  ${pn.examSignal}`, ``);
    }
    note.concepts.forEach((c) => {
      lines.push(`🧩 ${c.ordinal}️⃣ ${c.title}`);
      if (c.pattern)        lines.push(`P — Pattern\n  ${c.pattern}`);
      if (c.surgicalReason) lines.push(`⚡ Surgical Reason\n  ${c.surgicalReason}`);
      if (c.trap)           lines.push(`❗ Trap\n  ${c.trap}`);
      if (c.rule)           lines.push(`🔥 Rule\n  ${c.rule}`);
      lines.push(``);
    });
  }

  // Memory shortcuts — derived from concept rules, shown in both formats
  if (note.memoryShortcuts?.length) {
    lines.push(`🧠 MEMORY SHORTCUTS`);
    note.memoryShortcuts.forEach((s) => lines.push(`  👉 ${s}`));
    lines.push(``);
  }

  if (note.miniTest?.length) {
    lines.push(`📝 MINI TEST`);
    note.miniTest.forEach((q, i) => lines.push(`${i + 1}. ${q}`));
    lines.push(``);
  }

  if (note.externalStudyLinks?.length) {
    lines.push(`📚 EXTERNAL STUDY LINKS`);
    note.externalStudyLinks.forEach((l) => lines.push(`↗ ${l.label} (${l.searchQuery})`));
    lines.push(``);
  } else if (note.crossLinks?.length) {
    lines.push(`🔗 CROSS-LINKS`);
    note.crossLinks.forEach((cl) => lines.push(`↗ ${cl.label}${cl.resolvedPage ? ` · p.${cl.resolvedPage}` : ""}`));
    lines.push(``);
  }

  if (note.relatedVideoQueries?.length) {
    lines.push(`📺 RELATED TEACHING VIDEOS`);
    note.relatedVideoQueries.forEach((q) => lines.push(`▶ ${q}`));
    lines.push(``);
  }

  return lines.join("\n");
}
