// lib/notelab/ultraNoteStore.ts
// localStorage-backed store for Ultra Notes generated from the right panel.
// Primary entry point: buildNoteFromStudyModel — consumes PageBrain directly.

import type { CurrentPageStudyModel } from "@/lib/insights/currentPageStudyModel";

export type NoteSubject = "Biology" | "Calculus" | "Dental / Clinical" | "General Notes";

export interface UltraNoteFolder {
  id: string;
  name: string;
  sourceBookId: string;
  subject: NoteSubject;
  createdAt: number;
}

/** Infer subject from bookId or title keywords */
export function inferSubject(bookId: string): NoteSubject {
  const lower = bookId.toLowerCase();
  if (/bio(logy)?|anatomy|physiology|genetics|cell|organism/.test(lower)) return "Biology";
  if (/calc|math|algebra|geometry|trig|statistic|linear|differential/.test(lower)) return "Calculus";
  if (/dental|dent|medical|med|clinical|nursing|pharma|patho|histology/.test(lower)) return "Dental / Clinical";
  return "General Notes";
}

export interface UltraNoteConcept {
  ordinal: number;
  title: string;
  pattern: string;
  surgicalReason: string;
  trap: string;
  rule: string;
}

/** OpenAI professor-layer study notes — the 6 dedicated teaching sections */
export interface ProfessorNotes {
  whyItMatters?: string;
  keyMechanism?: string;
  commonConfusion?: string;
  memoryAnchor?: string;
  reasoningFlow?: string;
  examSignal?: string;
}

/** One named section in a PageBrain-sourced structured note */
export interface NoteSection {
  label: string;
  content: string;
}

export interface UltraNote {
  id: string;
  bookId: string;
  bookTitle?: string;
  pageNumber: number;
  topic: string;
  coreIdea: string;
  concepts: UltraNoteConcept[];
  memoryShortcuts: string[];
  subject: NoteSubject;
  createdAt: number;
  /** Structured PageBrain sections — present when note was built via buildNoteFromStudyModel */
  sections?: NoteSection[];
  /** OpenAI-generated professor teaching notes — present when synthesis resolved */
  professorNotes?: ProfessorNotes;
  /** OpenAI page thesis — authoritative one-sentence governing idea */
  pageThesis?: string;
  /** OpenAI synthesis mini-test questions for this page */
  miniTest?: string[];
  /** Resolved cross-links from synthesis — kept for backward compat with saved notes */
  crossLinks?: Array<{ label: string; resolvedPage?: number }>;
  /** External study links generated by OpenAI — full with searchQuery for constructing URLs */
  externalStudyLinks?: Array<{ label: string; searchQuery: string; type: string }>;
  /** Related teaching video search queries from OpenAI */
  relatedVideoQueries?: string[];
  /** OpenAI highlight anchors — source spans selected for left-panel highlights */
  highlightAnchors?: Array<{ text: string; anchorType: string; reason: string }>;
}

const STORAGE_KEY = "ultraNotes_v1";

const IDB_DB_NAME = "avrrio_notes_v1";
const IDB_STORE_NAME = "notes";
const IDB_FLAG_KEY = "ultraNotes_in_idb";

function compact(note: UltraNote): UltraNote {
  const trim = (s: string | undefined, n: number): string | undefined => s?.slice(0, n);
  return {
    id:          note.id,
    bookId:      note.bookId,
    pageNumber:  note.pageNumber,
    topic:       note.topic.slice(0, 120),
    coreIdea:    note.coreIdea.slice(0, 300),
    subject:     note.subject,
    createdAt:   note.createdAt,
    memoryShortcuts: [],
    concepts: note.concepts.slice(0, 5).map((c) => ({
      ordinal:        c.ordinal,
      title:          c.title.slice(0, 80),
      pattern:        c.pattern.slice(0, 150),
      surgicalReason: c.surgicalReason.slice(0, 150),
      trap:           c.trap.slice(0, 150),
      rule:           c.rule.slice(0, 150),
    })),
    sections: note.sections?.slice(0, 5).map((s) => ({
      label:   s.label.slice(0, 60),
      content: s.content.slice(0, 300),
    })),
    professorNotes: note.professorNotes ? {
      whyItMatters:    trim(note.professorNotes.whyItMatters,    200),
      keyMechanism:    trim(note.professorNotes.keyMechanism,    200),
      commonConfusion: trim(note.professorNotes.commonConfusion, 200),
      memoryAnchor:    trim(note.professorNotes.memoryAnchor,    200),
      reasoningFlow:   trim(note.professorNotes.reasoningFlow,   200),
      examSignal:      trim(note.professorNotes.examSignal,      200),
    } : undefined,
    pageThesis: note.pageThesis?.slice(0, 200),
  };
}

function openNoteIDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(IDB_DB_NAME, 1);
    req.onupgradeneeded = () => {
      req.result.createObjectStore(IDB_STORE_NAME, { keyPath: "id" });
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function saveNotesToIDB(notes: UltraNote[]): Promise<void> {
  const db = await openNoteIDB();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(IDB_STORE_NAME, "readwrite");
    const store = tx.objectStore(IDB_STORE_NAME);
    store.clear();
    for (const n of notes) store.put(n);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

async function loadNotesFromIDB(): Promise<UltraNote[]> {
  try {
    const db = await openNoteIDB();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(IDB_STORE_NAME, "readonly");
      const req = tx.objectStore(IDB_STORE_NAME).getAll();
      req.onsuccess = () => resolve(req.result ?? []);
      req.onerror = () => reject(req.error);
    });
  } catch {
    return [];
  }
}

function loadAll(): UltraNote[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

async function saveAll(notes: UltraNote[]): Promise<void> {
  if (typeof window === "undefined") return;
  const compacted = notes.map(compact);
  const serialized = JSON.stringify(compacted);
  console.log("[NOTE_SAVE_KEY]", { key: STORAGE_KEY, count: compacted.length, bytes: serialized.length });
  try {
    localStorage.setItem(STORAGE_KEY, serialized);
    try { localStorage.removeItem(IDB_FLAG_KEY); } catch {}
    console.log("[NOTE_SAVE_SUCCESS]", { key: STORAGE_KEY, count: compacted.length });
    window.dispatchEvent(new Event("note-lab-updated"));
  } catch (lsErr) {
    console.warn("[NOTE_LS_QUOTA_FAIL]", String(lsErr));
    try {
      await saveNotesToIDB(compacted);
      try { localStorage.setItem(IDB_FLAG_KEY, "1"); } catch {}
      console.log("[NOTE_IDB_SUCCESS]", { count: compacted.length });
      window.dispatchEvent(new Event("note-lab-updated"));
    } catch (idbErr) {
      console.error("[NOTE_ALL_STORAGE_FAIL]", { ls: String(lsErr), idb: String(idbErr) });
      throw new Error(`Note storage failed: ${String(lsErr)}`);
    }
  }
}

export function getAllUltraNotes(): UltraNote[] {
  return loadAll();
}

export function getNotesByBook(bookId: string): UltraNote[] {
  return loadAll().filter((n) => n.bookId === bookId);
}

export async function isUltraNotePersisted(id: string): Promise<boolean> {
  const inLS = loadAll().find((n) => n.id === id);
  if (inLS) return true;
  try {
    const notes = await loadNotesFromIDB();
    return notes.some((n) => n.id === id);
  } catch {
    return false;
  }
}

export async function saveUltraNote(note: UltraNote): Promise<void> {
  const notes = loadAll();
  const idx = notes.findIndex((n) => n.bookId === note.bookId && n.pageNumber === note.pageNumber);
  if (idx >= 0) {
    notes[idx] = note;
  } else {
    notes.unshift(note);
  }
  await saveAll(notes.slice(0, 200));
}

export async function deleteUltraNote(id: string): Promise<void> {
  await saveAll(loadAll().filter((n) => n.id !== id));
}

export function buildUltraNote(
  bookId: string,
  pageNumber: number,
  topic: string,
  coreIdea: string,
  concepts: UltraNoteConcept[],
  bookTitle?: string,
  professorNotes?: ProfessorNotes,
  pageThesis?: string,
  miniTest?: string[],
  crossLinks?: Array<{ label: string; resolvedPage?: number }>,
  externalStudyLinks?: Array<{ label: string; searchQuery: string; type: string }>,
  relatedVideoQueries?: string[],
  highlightAnchors?: Array<{ text: string; anchorType: string; reason: string }>,
): UltraNote {
  const memoryShortcuts = concepts
    .filter((c) => c.rule && c.rule.length > 10)
    .map((c) => `${c.title}: ${c.rule}`)
    .slice(0, 3);

  return {
    id: `note-${bookId}-p${pageNumber}-${Date.now()}`,
    bookId,
    bookTitle: bookTitle || undefined,
    pageNumber,
    topic,
    coreIdea,
    concepts,
    memoryShortcuts,
    subject: inferSubject(bookId),
    createdAt: Date.now(),
    professorNotes: professorNotes ?? undefined,
    pageThesis: pageThesis || undefined,
    miniTest: miniTest?.length ? miniTest : undefined,
    crossLinks: crossLinks?.length ? crossLinks : undefined,
    externalStudyLinks: externalStudyLinks?.length ? externalStudyLinks : undefined,
    relatedVideoQueries: relatedVideoQueries?.length ? relatedVideoQueries : undefined,
    highlightAnchors: highlightAnchors?.length ? highlightAnchors : undefined,
  };
}

/**
 * Primary NoteLab entry point — builds a structured note directly from PageBrain.
 * Produces 6 explicit sections matching the cognitive architecture:
 *   1. Page Thesis  2. Key Mechanisms  3. Definitions
 *   4. Confusions & Traps  5. Exam Signals  6. Summary
 *
 * All content comes from the same StudyModel that powers the right panel and
 * left-panel highlights — NoteLab is a different view of the same brain.
 */
export function buildNoteFromStudyModel(
  model: CurrentPageStudyModel,
  opts: { bookId: string; pageNumber: number; topic: string; bookTitle?: string },
): UltraNote {
  const { bookId, pageNumber, topic, bookTitle } = opts;
  const sn = model.studyNotes;
  const sections: NoteSection[] = [];

  // 1. Page Thesis — governing idea for this page
  if (model.pageThesis) {
    sections.push({ label: "Page Thesis", content: model.pageThesis });
  }

  // 2. Key Mechanisms — studyNotes.keyMechanism + per-concept mechanism fields
  const mechanisms = [
    sn.keyMechanism,
    ...model.conceptBlocks.map((b) => b.mechanism).filter(Boolean),
  ].filter((v): v is string => !!v);
  if (mechanisms.length) {
    sections.push({ label: "Key Mechanisms", content: mechanisms.join("  ·  ") });
  }

  // 3. Definitions — one per concept block (title: pattern)
  const defs = model.conceptBlocks
    .filter((b) => b.pattern)
    .map((b) => `${b.title}: ${b.pattern}`);
  if (defs.length) {
    sections.push({ label: "Definitions", content: defs.join("\n") });
  }

  // 4. Confusions & Traps — studyNotes.commonConfusion + per-concept traps
  const traps = [
    sn.commonConfusion,
    ...model.conceptBlocks.map((b) => b.trap).filter(Boolean),
  ].filter((v): v is string => !!v);
  if (traps.length) {
    sections.push({ label: "Confusions & Traps", content: traps.join("  ·  ") });
  }

  // 5. Exam Signals — examSignal + concept rules
  const signals = [
    sn.examSignal,
    ...model.conceptBlocks.map((b) => b.rule).filter(Boolean),
  ].filter((v): v is string => !!v);
  if (signals.length) {
    sections.push({ label: "Exam Signals", content: signals.join("  ·  ") });
  }

  // 6. Summary — student-friendly synthesis from thesis + why it matters + quick memory
  const summaryParts = [model.pageThesis, sn.whyThisMatters, sn.quickMemory].filter(Boolean);
  if (summaryParts.length) {
    sections.push({ label: "Summary", content: summaryParts.slice(0, 2).join(" ") });
  }

  const concepts: UltraNoteConcept[] = model.conceptBlocks.map((b, i) => ({
    ordinal:        i + 1,
    title:          b.title,
    pattern:        b.pattern,
    surgicalReason: b.mechanism ?? "",
    trap:           b.trap ?? "",
    rule:           b.rule ?? "",
  }));

  const memoryShortcuts = concepts
    .filter((c) => c.rule && c.rule.length > 10)
    .map((c) => `${c.title}: ${c.rule}`)
    .slice(0, 3);

  const professorNotes: ProfessorNotes = {
    whyItMatters:    sn.whyThisMatters  ?? undefined,
    keyMechanism:    sn.keyMechanism    ?? undefined,
    commonConfusion: sn.commonConfusion ?? undefined,
    memoryAnchor:    sn.quickMemory     ?? undefined,
    reasoningFlow:   sn.reasoningFlow   ?? undefined,
    examSignal:      sn.examSignal      ?? undefined,
  };

  console.log("[NOTE_FROM_PAGEBRAIN]", {
    page: pageNumber,
    sectionCount: sections.length,
    sectionLabels: sections.map((s) => s.label),
    conceptCount: concepts.length,
    hasReasoningFlow: !!sn.reasoningFlow,
  });

  return {
    id:               `note-${bookId}-p${pageNumber}-${Date.now()}`,
    bookId,
    bookTitle:        bookTitle || undefined,
    pageNumber,
    topic,
    coreIdea:         model.pageThesis,
    concepts,
    memoryShortcuts,
    sections,
    subject:          inferSubject(bookId),
    createdAt:        Date.now(),
    professorNotes,
    pageThesis:       model.pageThesis,
    miniTest:         model.miniTest?.length           ? model.miniTest           : undefined,
    externalStudyLinks: model.externalStudyLinks?.length ? model.externalStudyLinks : undefined,
    relatedVideoQueries: model.relatedVideoQueries?.length ? model.relatedVideoQueries : undefined,
    highlightAnchors: model.highlightAnchors?.length   ? model.highlightAnchors   : undefined,
  };
}

export function formatUltraNoteText(note: UltraNote): string {
  const lines: string[] = [
    `⚡ STUDY NOTE — ${note.topic} (Page ${note.pageNumber})`,
    ``,
  ];

  // PageBrain structured sections (present on notes built via buildNoteFromStudyModel)
  if (note.sections?.length) {
    const SECTION_ICONS: Record<string, string> = {
      "Page Thesis":       "🎯",
      "Key Mechanisms":    "⚙️",
      "Definitions":       "📖",
      "Confusions & Traps": "⚠️",
      "Exam Signals":      "🎓",
      "Summary":           "📝",
    };
    for (const sec of note.sections) {
      const icon = SECTION_ICONS[sec.label] ?? "•";
      lines.push(`${icon} ${sec.label.toUpperCase()}`);
      lines.push(`  ${sec.content.replace(/\n/g, "\n  ")}`);
      lines.push(``);
    }
  } else {
    // Legacy format — notes saved before PageBrain sections were introduced
    lines.push(`🎯 CORE IDEA`, note.coreIdea, ``);
    if (note.professorNotes) {
      const pn = note.professorNotes;
      if (pn.whyItMatters)    lines.push(`💡 WHY THIS MATTERS\n  ${pn.whyItMatters}`, ``);
      if (pn.keyMechanism)    lines.push(`⚙️ KEY MECHANISM\n  ${pn.keyMechanism}`, ``);
      if (pn.commonConfusion) lines.push(`⚠️ COMMON CONFUSION\n  ${pn.commonConfusion}`, ``);
      if (pn.memoryAnchor)    lines.push(`🧠 MEMORY ANCHOR\n  ${pn.memoryAnchor}`, ``);
      if (pn.reasoningFlow)   lines.push(`🔗 REASONING FLOW\n  ${pn.reasoningFlow}`, ``);
      if (pn.examSignal)      lines.push(`🎓 EXAM SIGNAL\n  ${pn.examSignal}`, ``);
    }
    note.concepts.forEach((c) => {
      lines.push(`🧩 ${c.ordinal}️⃣ ${c.title}`);
      if (c.pattern)        lines.push(`P — Pattern\n  ${c.pattern}`);
      if (c.surgicalReason) lines.push(`⚡ Surgical Reason\n  ${c.surgicalReason}`);
      if (c.trap)           lines.push(`❗ Trap\n  ${c.trap}`);
      if (c.rule)           lines.push(`🔥 Rule\n  ${c.rule}`);
      lines.push(``);
    });
  }

  // Memory shortcuts — derived from concept rules, shown in both formats
  if (note.memoryShortcuts?.length) {
    lines.push(`🧠 MEMORY SHORTCUTS`);
    note.memoryShortcuts.forEach((s) => lines.push(`  👉 ${s}`));
    lines.push(``);
  }

  if (note.miniTest?.length) {
    lines.push(`📝 MINI TEST`);
    note.miniTest.forEach((q, i) => lines.push(`${i + 1}. ${q}`));
    lines.push(``);
  }

  if (note.externalStudyLinks?.length) {
    lines.push(`📚 EXTERNAL STUDY LINKS`);
    note.externalStudyLinks.forEach((l) => lines.push(`↗ ${l.label} (${l.searchQuery})`));
    lines.push(``);
  } else if (note.crossLinks?.length) {
    lines.push(`🔗 CROSS-LINKS`);
    note.crossLinks.forEach((cl) => lines.push(`↗ ${cl.label}${cl.resolvedPage ? ` · p.${cl.resolvedPage}` : ""}`));
    lines.push(``);
  }

  if (note.relatedVideoQueries?.length) {
    lines.push(`📺 RELATED TEACHING VIDEOS`);
    note.relatedVideoQueries.forEach((q) => lines.push(`▶ ${q}`));
    lines.push(``);
  }

  return lines.join("\n");
}
