// lib/syllabus/syllabusSchema.ts
// Type system for the Universal Adaptive Syllabus Engine.
// Separates deterministic extraction (StructureCandidate) from AI enrichment (AdaptiveChapter).
// The AI may reference only candidateIds that the server provides — never invent page ranges.

import { z } from "zod";

// ── Provenance ────────────────────────────────────────────────────────────

export type StructureSource =
  | "bookmark"    // PDF outline/bookmark
  | "toc"         // Detected table-of-contents page
  | "heading"     // Typography/position-based heading detection
  | "uploaded"    // User-supplied syllabus file
  | "ai-inferred"; // AI-generated structure (no document grounding)

// ── Structure candidates — server-owned, stable IDs ──────────────────────

export const StructureCandidateSchema = z.object({
  id:         z.string(),                   // "c0", "c1", ...  — never generated by AI
  title:      z.string(),
  level:      z.union([z.literal(1), z.literal(2), z.literal(3)]),
  startPage:  z.number().int().min(1),
  endPage:    z.number().int().min(1).optional(),
  source:     z.enum(["bookmark", "toc", "heading", "uploaded", "ai-inferred"]),
  confidence: z.number().min(0).max(1),
});
export type StructureCandidate = z.infer<typeof StructureCandidateSchema>;

// ── Document classification ───────────────────────────────────────────────

export const DocumentClassificationSchema = z.object({
  docType:             z.string(),   // "Medical Textbook", "Programming Book", ...
  discipline:          z.string(),   // "Medicine", "Computer Science", ...
  isMultiDisciplinary: z.boolean(),
  confidence:          z.number().min(0).max(1),
  signal:              z.string(),   // human-readable match description
  detectedProfileId:   z.string(),   // maps to ExpertProfile (studySheetProfiles)
});
export type DocumentClassification = z.infer<typeof DocumentClassificationSchema>;

// ── AI generation output schema (what zodTextFormat constrains the model to) ──

export const AdaptiveChapterAISchema = z.object({
  candidateId:         z.string(),   // MUST be a provided candidate ID
  importance:          z.number().int().min(0).max(100),
  difficulty:          z.number().int().min(0).max(100),
  estimatedStudyHours: z.number().min(0).max(200),
  reviewFrequency:     z.enum(["once", "twice", "frequent"]),
  prerequisites:       z.array(z.string()),  // candidateIds only
  recommendedOrder:    z.number().int().min(1),
  concepts:            z.array(z.string()),  // 3-6 key concepts in this chapter
  confidence:          z.number().min(0).max(1),
});
export type AdaptiveChapterAI = z.infer<typeof AdaptiveChapterAISchema>;

export const PrerequisiteEdgeSchema = z.object({
  fromCandidateId: z.string(),
  toCandidateId:   z.string(),
  strength:        z.enum(["required", "recommended", "helpful"]),
  reason:          z.string(),
});
export type PrerequisiteEdge = z.infer<typeof PrerequisiteEdgeSchema>;

export const SyllabusGenerationOutputSchema = z.object({
  chapters:         z.array(AdaptiveChapterAISchema),
  prerequisites:    z.array(PrerequisiteEdgeSchema),
  recommendedOrder: z.array(z.string()),   // ordered candidateIds
  studyRoadmap:     z.array(z.string()),   // phase labels: ["Foundation", "Core", ...]
});
export type SyllabusGenerationOutput = z.infer<typeof SyllabusGenerationOutputSchema>;

// ── Validation ────────────────────────────────────────────────────────────

export interface SyllabusValidationIssue {
  code:        string;
  message:     string;
  candidateId?: string;
}

// ── Fully hydrated chapter (candidates merged with AI enrichment) ──────────

export interface AdaptiveChapter {
  candidateId:         string;
  title:               string;
  level:               1 | 2 | 3;
  startPage:           number;
  endPage?:            number;
  source:              StructureSource;
  importance:          number;          // 0–100
  difficulty:          number;          // 0–100
  estimatedStudyHours: number;
  reviewFrequency:     "once" | "twice" | "frequent";
  prerequisites:       string[];        // candidateIds
  recommendedOrder:    number;
  concepts:            string[];
  confidence:          number;
}

// ── Full adaptive syllabus (stored per bookId) ────────────────────────────

export interface AdaptiveSyllabus {
  bookId:    string;
  bookTitle: string;

  classification:    DocumentClassification;
  selectedProfileId: string;    // may differ from classification.detectedProfileId if user overrode

  structureCandidates: StructureCandidate[];  // server-owned ground truth
  chapters:            AdaptiveChapter[];     // hydrated from candidates + AI
  prerequisites:       PrerequisiteEdge[];

  recommendedOrder: string[];   // candidateIds in recommended study order
  studyRoadmap:     string[];   // human-readable phase labels

  totalPages:       number;
  generatedAt:      string;     // ISO timestamp (server-stamped)
  generatorVersion: string;
  schemaVersion:    number;

  validationIssues: SyllabusValidationIssue[] | null;
}
